### ISSUE TITLE
apiv2 POST /beatmaps/{beatmap}/attributes returns incorrect star_rating with mods

### ISSUE THREAD

**Issue by grumd** [ppy/osu-web#10294]
It seems like the only mod affecting star_rating in the API is DT. HR doesn't affect the star_rating value.

nomod: 4.43
DT: 5.92
HR: 4.43
DTHR: 5.92

![image](https://github.com/ppy/osu-api/assets/5869818/b28ca71e-6302-41d0-aff0-ff9129d6696a)

**Comment by tsunyoku** [comment]
looked into this one locally, can reproduce but it seems the issue does not lie in osu-web. the mods that are passed on the web request to the difficulty cache API are correct, and does include HR. the same issue occurs even when providing the ruleset so it's not that. i presume this is an issue with the diff attribs which are stored in the database (and how they're calculated)?

another thing i observed, and @grumd's original report also displays, is that the `great_hit_window` attribute (specific to taiko) is updated when HR is passed as a mod

i tried to reproduce this with all modes: the SR (as well as any other attributes) were updated correctly for osu!std, osu!fruits and osu!mania. so it seems this issue is specific to taiko

i'm not sure what would coerce it to calculate HR and nomod as the same SR - HR [is registed as a difficulty increasing mod](https://github.com/ppy/osu/blob/f90f2491c349c58f5a038ab83e9934ca4b483787/osu.Game.Rulesets.Taiko/Difficulty/TaikoDifficultyCalculator.cs#L49) for taiko. will require a deeper look to see why this is happening, but the cause is definitely not to do with osu-web

**Comment by peppy** [comment]
cc @smoogipoo

**Comment by smoogipoo** [comment]
This is working as intended. If there's an issue here, it's with the difficulty calculator implementation and not the/any server-side components.

**Comment by nanaya** [comment]
The api always passes ruleset to the difficulty calculator. Please provide example showing otherwise.
