### ISSUE TITLE
Add ability to make/edit forum voting

### ISSUE THREAD

**Issue by Furozzu** [ppy/osu-web#10372]
it will be nice if you can make/edit voting in forum to gain some sort of engagements with everyone

![Screenshot_2023-07-15-21-58-30-33_40deb401b9ffe8e1df2f1cc5ba480b12](https://github.com/ppy/osu-web/assets/29659076/83768eae-02e8-4a57-9e0e-a38abbc75e54)

before, i can add/edit it using old website, but after it got deprecated, i cant change/add any voting in my forum

**Comment by cl8n** [comment]
polls are available on some forums, but not all. for example try making one on this forum https://osu.ppy.sh/community/forums/52

**Comment by peppy** [comment]
If you want it added to a specific forum, please let us know and we can consider it.

**Comment by cl8n** [comment]
sorry @Furozzu I just learned my comment above is incorrect, I got it mixed up with a different feature. polls are available anywhere -- it's just that you can only add or edit a poll during a short grace period after the topic is posted.

I think it's to prevent the topic from becoming misleading, if a significant amount of poll stats are removed/changed. but im not entirely sure because I don't see a documented reason

so if you want to open a new poll, you can make a new topic for it
