### ISSUE TITLE
Converted classic osu! score does not match score multiplier

### ISSUE THREAD

**Issue by ilsubyeega** [ppy/osu-web#10441]
![image](https://github.com/ppy/osu-web/assets/37479424/81ef1129-d048-44a6-9fe9-a81a319c3727)
![image](https://github.com/ppy/osu-web/assets/37479424/4898c55d-8681-4b1e-931c-98f4029df168)

(Classic), (Classic HD), (Classic HDHR) is same score as 1mil, but HD and HDHR should be have more scores through
Map: https://lazer.ppy.sh/beatmapsets/1944151#osu/4021908

**Comment by peppy** [comment]
This is out of scope of osu-web, and should be fixed from lazer / score processor's end I believe.

@smoogipoo do you have any knowledge of this one? Is it already resolved?

**Comment by smoogipoo** [comment]
Interesting. I believe this was a bug with the importer.

This is the 2023.407.0 tag (last deployed importer): https://github.com/ppy/osu-queue-score-statistics/blob/572e762cd19c3d6c5c140bc080c43e6e0c1f76bb/osu.Server.Queues.ScorePump/Queue/ImportHighScoresCommand.cs

This is the 2022.1214.0 tag of osu used in ^^: https://github.com/ppy/osu/blob/50dc76d579a11ecfde83ff91fa561b636fb64996/osu.Game/Rulesets/Scoring/ScoreProcessor.cs

If you notice, `ComputeScore` refers to this `scoreMultiplier` member, which is calculated from the `Mods` property of `ScoreProcessor`. The import command did not set this property:

https://github.com/ppy/osu-queue-score-statistics/blob/572e762cd19c3d6c5c140bc080c43e6e0c1f76bb/osu.Server.Queues.ScorePump/Queue/ImportHighScoresCommand.cs#L536-L544

Since scoring has changed, the importer should no longer be susceptible to this as the relevant method calculates mod multipliers from the `ScoreInfo` directly:

https://github.com/ppy/osu/blob/b581d67416d569a14b29f6a969c4ea922729c803/osu.Game/Database/StandardisedScoreMigrationTools.cs#L244-L254

Which is set here:

https://github.com/ppy/osu-queue-score-statistics/blob/35070d1bd2aea719d21b25c9a91636c14f9162d2/osu.Server.Queues.ScoreStatisticsProcessor/Commands/Queue/ImportHighScoresCommand.cs#L445-L460
