### ISSUE TITLE
More descriptive osu! store slider tooltip for osu! supporter amounts

### ISSUE THREAD

**Issue by Blooshing** [ppy/osu-web#10513]
There is a current help thread: https://osu.ppy.sh/community/forums/topics/1815804?n=1 where a user is confused about the amount of supporter they would receive when buying $4 vs $7. The tooltip currently only says 1 month for both, implying that even if you spend the greater amount you would still be getting only 1 month. 

IMO, even if it is intuitive that the more money you spend on supporter the more supporter you are going to get, it should display the exact amount of supporter you will receive with each $ amount. 

![](https://i.ppy.sh/d78d0dbb4c04d9c6ad930eab112fd1e082cac8cd/68747470733a2f2f63646e2e646973636f72646170702e636f6d2f6174746163686d656e74732f313134303031393830363635333932373436342f313134373130373235383235343234353838392f696d6167652e706e67)![](https://i.ppy.sh/a3e0a9e1258f22619d22519790a2ba82d351b43b/68747470733a2f2f63646e2e646973636f72646170702e636f6d2f6174746163686d656e74732f313134303031393830363635333932373436342f313134373130373336353132353130373736322f696d6167652e706e67)

**Comment by Joehuu** [comment]
I did make an issue about this a long time ago https://github.com/ppy/osu-web/issues/3687 (point 2), and it was deemed intentional at the time.

I did the test and $7 is still 1 month. I still think the behavior confusing to this day. If it's still intentional, I would propose to display it differently like `USD 4(+3)` or similar.

**Comment by cl8n** [comment]
closing this one because that actually *is* how it works -- see #3687 and #6206 instead
