### ISSUE TITLE
Failed solo score handling needs reconsidering with respect to stored score rank

### ISSUE THREAD

**Issue by bdach** [ppy/osu-web#10524]
[Back in the olden days](https://github.com/ppy/osu/pull/13926), when client would submit a failed play, it would set D rank, because we didn't have F rank client-side yet.

Since https://github.com/ppy/osu/pull/18785, we now have an F rank client-side. But this logic still lives:

https://github.com/ppy/osu-web/blob/f7ef5553dc31e2a2dd7ea43644fd092bfe93091a/app/Models/Solo/Score.php#L57-L62

and overwrites the F rank sent by client to D again.

You would say that, well, no biggie, just do this:

```diff
diff --git a/app/Models/Solo/Score.php b/app/Models/Solo/Score.php
index 875ade1318..284aff7c04 100644
--- a/app/Models/Solo/Score.php
+++ b/app/Models/Solo/Score.php
@@ -60,7 +60,7 @@ class Score extends Model implements Traits\ReportableInterface, Traits\SoloScor
         // older lazer builds potentially submit incorrect details here (and we still want to
         // accept their scores.
         if (!$score->data->passed) {
-            $score->data->rank = 'D';
+            $score->data->rank = 'F';
         }
 
         $score->saveOrExplode();

```

which, sure, fixes that immediate part of it, but then you attempt to go to `/scores/{score_id}` web-side and see this:

![1693994564](https://github.com/ppy/osu-web/assets/20418176/28fcbe63-c3a4-4a00-92ce-5e6e57c9204b)

Note missing rank letter, note rank badges on the left all lit up. So that is at least _one_ place that is not ready web-side to handle an F rank. Maybe there are more.

I guess the things to discuss here are:

- Should failed scores be even displayable via `/scores/{score_id}`?
- Maybe something to do with the `preserve` flag makes this issue go away?
- If not, does this need design? Which other places may need to handle an F rank?

**Comment by cl8n** [comment]
setting these to F rank seems correct in context of legacy scores doing the same thing. F ranks are already returned over the API, but yeah none have been displayed via web frontend so far due to `high` tables not including fails, non-`high` fails being filtered out before display on user profile, and `game_scores` not having a rank display on the legacy matches page.

these are the only frontend issues with displaying F ranks, as far as I can tell (and this is assuming failed scores could make it into these responses to begin with). both seem straightforward to fix:

- score page tower and dial have undefined behavior, screenshotted above
- there is no score-rank icon for F, which various components on user profile and beatmap info pages rely on

> Should failed scores be even displayable via `/scores/{score_id}`?

if I haven't missed something that would make it more difficult to support, I don't see why not.

**Comment by peppy** [comment]
> if I haven't missed something that would make it more difficult to support, I don't see why not.

One very valid (IMO) reason not to would be that these scores are not permanently stored. So the link could (and will) become a 404 at any point.

**Comment by nanaya** [comment]
Well, nor would any other scores if the user created higher score with same mod etc set?

**Comment by peppy** [comment]
Sure, but this is a much more common case.

Maybe it's fine with a message mentioning that it will not be a permanent URL?

**Comment by bdach** [comment]
So I guess options are:

- update snippet from the OP to set F rank, but explicitly disallow showing failed scores anywhere on the website
- update snippet from the OP to set F rank, update designs to include F rank, possibly with a disclaimer that the score page for a failed play can go away at any time

Note that we _could_ do with a proper design for F rank, since we already show that in client, but there it's currently just the D rank badge but just with the letter swapped. So if we had something more proper we could show that in both places.

Thoughts on which one would be better/worse, more/less work?

**Comment by peppy** [comment]
I'd say we want to update the condition here to use "F", not "D". And we should implement the "F" display on the scores page similar to the client, as proposed above.

Should probably be done sooner than later so that multiplayer results screen makes more sense (shows failed players as "F" not "D").
