### ISSUE TITLE
get_match gives 100 events without the ability to paginate

### ISSUE THREAD

**Issue by Givikap120** [ppy/osu-web#10611]
There are `before` and `after` params, but they didn't seem to work, or at least it needs more clear explanation how they needs to be used.
From osu-web code it seems that `->limit($limit);` is applied before eg ` ->where('event_id', '>', $after)`.

**Comment by cl8n** [comment]
to be clear, `get_match` is the [endpoint from the legacy api](https://github.com/ppy/osu-api/wiki#apiget_match) -- I assume you're talking about the [v2 endpoint](https://osu.ppy.sh/docs/index.html#get-apiv2matchesmatch) based on the rest of this issue though?

`after` and `before` take event IDs, i.e. the values at `events.[number].id` in the response. seems working for me

as for the code part, it's using a query builder that will compile the clauses in the correct order regardless of the order you apply them, so that part is okay too.

**Comment by tybug** [comment]
I thought this wasn't working because I was testing against [a match with exactly 100 events...](https://osu.ppy.sh/community/matches/110505618)but accounting for that, everything works for me as well
