### ISSUE TITLE
I have problems!

### ISSUE THREAD

**Issue by Nightflyyer** [ppy/osu-web#108]
I tried running this but i keep getting http://puu.sh/kCmcM/6a26689188.png and everything is working also i found out the VM is 64-bit and my PC doesn't support 64 bit os'es on Virtualbox it only uses 32-bit how could i use a 32-bit os on this!?

**Comment by nanaya** [comment]
see if you're running vmware or hyper-v as well since they can't be run at same time.

**Comment by Pepperrika** [comment]
I don't use VMware i use virtualbox and my PC doesn't have hardware virtualization

**Comment by TheHowl** [comment]
Try replacing the `config.vm.box_url` value to `"https://cloud-images.ubuntu.com/vagrant/vivid/current/vivid-server-cloudimg-i386-vagrant-disk1.box"`. Or you can also set it up manually by executing manually all the commands of the provision script so that it runs on your machine without setting up a virtual one, although that might require some work.

**Comment by nanaya** [comment]
> my PC doesn't have hardware virtualization

running it will be slow then. Look into using plain apache setup but as mentioned, it's not quite easy.

**Comment by codevirtuel** [comment]
Hey! i have the same problem ( default: Warning: connection timeout. Retrying... )
I already replace the "config.vm.box_url" but this doesn't work...
