### ISSUE TITLE
Replay being linked to wrong score and causing error

### ISSUE THREAD

**Issue by Flamiii** [ppy/osu-web#10919]
I set two scores on a map.
https://osu.ppy.sh/scores/2261244435 (Global Rank ~6.8k, shouldn't have replay because not top 1k)
https://osu.ppy.sh/scores/2261260831 (Global Rank 2, should have replay)

When I set the first score, there was no replay for it because it was not top 1k on the leaderboard, which makes sense. However, when I set the second play, I think the replay for that play got linked to the Global Rank ~6.8k score. Trying to download this replay from the website or view it in-game both cause an error, and it leads to the Global Rank 2 score not having an associated replay which is not good.

Update: The Global Rank 2 score got a replay somehow but it still causes an error when I try to download it from the website or in-game.

![osu_2024-01-30_07-33-00](https://github.com/ppy/osu-web/assets/74088315/e5a237c4-56e5-44ce-a5ab-b016f8d6c2c7)

**Comment by nanaya** [comment]
Looks like something with component handling replay file storage. @peppy

**Comment by peppy** [comment]
Thanks for finding a reason to do a potential lazer score wipe. We'll investigate but it looks like a colossal failure that got past all of the team (and players?) until now.

**Comment by S1n1st3rn3ss** [comment]
Kind of a silly question - would a wipe really be necessary? Isn't wiping the replays for all scores from the period of time when the issue (to eliminate the possible issues with other replays) a better solution? Or is there something that prevents doing that that I'm not noticing?

**Comment by peppy** [comment]
>  Isn't wiping the replays for all scores from the period of time when the issue occurred

Any score deletion we do will be scoped as small as possible, of course.

**Comment by peppy** [comment]
I've confirmed that the outcome of this issue is that we lost replays for a subset of plays, and nothing more. There is no way to recover these replays.

That said, there are no "incorrectly" linked replays as was reported. The only remaining issue is that some scores has the replay flag set to `true` while not having a replay on disk. I'm actively fixing this via https://github.com/ppy/osu-queue-score-statistics/pull/225.

I've decided we'll just eat the loss of replays and not reset scores for now. We can delete individual scores if they are seen as problematic (ie. looks like foul play and we don't have a replay to assess).
