### ISSUE TITLE
Website should make users aware of lazer mode on own profile when the user has played lazer recently (or only)

### ISSUE THREAD

**Issue by peppy** [ppy/osu-web#10925]

**Comment by nanaya** [comment]
...what should be shown there?

**Comment by nphuracm** [comment]
Maybe add a banner at somewhere like between the pfp, name and location row and the ranking graph row saying something like
_"Your scores set on osu!(lazer) are being displayed because of lazer mode being active. The status of these scores are subject to change, and might even be wiped altogether in the future."_
It doesn't have to be a really bright and scary, just a nice notice with a dark background (i.e. blends well with the overall color scheme) but the text in yellow or something to ensure that there's still some emphasis there.

**Comment by nanaya** [comment]
with recent scoring updates, is this still needed?

**Comment by peppy** [comment]
I think the minimum requirement is to set a user to their lazer profile if they've only ever played on lazer.

Right now, a new user can create an account, never play on stable, and have their profile stuck in non-lazer-mode until they find the toggle (or ask why they can't see any scores on their profile).

**Comment by nanaya** [comment]
With the new default, is it still needed?

(lazer mode for guests and users with no plays, last score type otherwise)

**Comment by bdach** [comment]
Yeah as far as I'm aware latest consensus was that https://github.com/ppy/osu-web/pull/11168 was enough. Let's close for now until it is deemed not enough.
