### ISSUE TITLE
Some mania scores that are SS on classic are not SS on lazer mode

### ISSUE THREAD

**Issue by tailsdk** [ppy/osu-web#10990]
I dont know if this is only a problem for newer scores but not all SS scores on classic mod show as SS on lazer mode as an example https://osu.ppy.sh/scores/2322006466 and  https://osu.ppy.sh/scores/2298997490 are both SS but only show up as S ranks on lazer mode

**Comment by cl8n** [comment]
I think that's actually intended right now; in "lazer mode" scores and ranks use the lazer rules, even if the score came from stable

**Comment by tailsdk** [comment]
But those scores should also be SS on lazer see the 2 scores below on https://osu.ppy.sh/beatmapsets/1335568#mania/2766889 which just have a worse ratio but are SS

**Comment by nanaya** [comment]
fwiw, the lazer version of rank comes directly from score processor (and stored in database), not computed by osu-web

**Comment by bdach** [comment]
For better or for worse the inconsistency looks fixed now, likely by one of the rank recomputation round(s) that we ran.

I'm not going to speak on whether it got fixed in the 'correct' direction, since lazer SS is all PERFECTs currently, but that conversation can continue if needed under https://github.com/ppy/osu/issues/24238.
