### ISSUE TITLE
Only increment "Replays watched" when downloading through lazer

### ISSUE THREAD

**Issue by respektive** [ppy/osu-web#11019]
I'm running a discord bot that downloads replays through the API to show stats like the UR and also render parts of the replay for analyzing and I've been getting a few reports of people being confused about their "Replays watched by Others" stat being increased by using the bot and thinking it might be a bug.

I'm thinking it might be better to only increment it when someone downloads the replay from lazer (e.g. actually watching it in-game). This would also help with potential abuse, as I've already seen people talking about "farming" this stat now.

**Comment by cl8n** [comment]
should downloading through web interface affect this stat? I would think that part is okay but now I'm not sure...

**Comment by respektive** [comment]
Personally I think it's fine, but I wouldn't be surprised if people are already abusing that to artificially increase those stats. So that should probably not increment it either.

**Comment by tsunyoku** [comment]
unless i'm missing something i don't think there's much reason to remove it from incrementing if it's downloaded through the web interface because it's no different than someone watching replays in stable or lazer

it already doesn't increment the count if the person downloading is the score author, so i think the only thing which should change here is not incrementing from an API request that isn't web or lazer... i should have seen this one coming

**Comment by peppy** [comment]
At least short term, API should definitely not count, if it is (this is the case for legacy API).

**Comment by cl8n** [comment]
resolved by #11126 (and web downloads do not count either, idk if I agree with that but seems intentional so ok)
