### ISSUE TITLE
Filtering by "Rank Achieved: SS" does not work in mania

### ISSUE THREAD

**Issue by AkiraMorilas** [ppy/osu-web#11057]
![Screenshot 2024-03-02 at 14-54-07 beatmap listing osu!](https://github.com/ppy/osu-web/assets/134231050/d6770f39-6b16-4f10-8c45-aa5e67b26fcb)
As shown in screenshot, none of my 36 mania SS ranks appear, despite mania being set as my main gamemode.
I am assuming that this is because none of them are lazer SSes(rainbow 300 only)?
Would be nice to get a clarification on whether this is a bug or intentional.

**Comment by bdach** [comment]
Similarly to https://github.com/ppy/osu-infrastructure/issues/27 I'm not sure what should happen. I see basically two outcomes:

- We say that this is intended because that's how lazer grades work and it's a wontfix
- We add support for filtering on old/new rank based on lazer mode being active (involves changes to `osu-queue-score-statistics` to store the old rank somewhere, reindexing at least all stable scores, etc.)

**Comment by bdach** [comment]
@peppy fyi

**Comment by nanaya** [comment]
adding the legacy rank to index (and updating search field based on lazer mode) is _probably_ enough
