### ISSUE TITLE
Improve privacy controls

### ISSUE THREAD

**Issue by Martmists-GH** [ppy/osu-web#11229]
Everything blacked out in this image should ideally have privacy controls.

![image](https://github.com/ppy/osu-web/assets/16361449/432c2e39-60cd-4010-b464-65eddc6d195c)

**Comment by cl8n** [comment]
I suspect this would be very unpopular because looking into & comparing players' stats is a core part of the online portion of this game. if you want the ability to do this, it's probably better to just play offline or play on a locally-hosted server

hiding your country *might* eventually be considered (#8033) given it's actually personal info, but I wouldn't count on that either

**Comment by Martmists-GH** [comment]
Is there a way to play offline while still being able to download beatmaps from in-game?

Also, is there a way to reset these statistics to a default state without deleting and re-creating the account?

**Comment by cl8n** [comment]
no to both, but here are some feature requests for those: https://github.com/ppy/osu/discussions/27253, #10717

I'm going to close this because I'm reasonably confident it would have negative reception, and I think someone higher up than me would oppose this anyway. sorry but you're probably more likely to see something like the first link above implemented, than a major change to online profiles as suggested in this issue.
