### ISSUE TITLE
Allow anyone to downvote a post

### ISSUE THREAD

**Issue by Lyti4n** [ppy/osu-web#11258]
Currently only BNs and NATs and the mapper are able to downvote a post, while it makes sense when it comes to denying kudosu it makes it very hard for anyone else to show that they disagree with a post their only option would be to comment on it while anyone who agrees with it can simply upvote.
Changing this would reduce how many pointless comments simply saying "I disagree" on vetos which is quite an issue currently.
My proposal is to allow anyone to downvote but only downvotes from BNs NAT or the mapper can deny kudosu.
As far as I can tell this change was suppose to be temporary to begin with #1955

**Comment by cl8n** [comment]
whether it makes sense on vetoes I'm not sure, but for other posts I don't think modding should encourage voiceless feedback like that. I don't see it as helpful to the map or the conversation for people to lazily contribute one click (usually just dogpiling on something for popular posts) rather than raising or backing up an actual point of argument, especially for what is supposed to be a more focused discussion area. but that goes for the existing thumbs-up system too so idk, just wanted to add the opposite perspective here

**Comment by Lyti4n** [comment]
I think that's fair but its useful to understand what the consensus on whether people generally agree with a post or not. BNs are already allowed to voice their opinions "lazily" why not everyone else. Besides I don't think it makes sense to only allow people who write something down that might have already been said plenty of times to show their opinion, it only encourages the kinda absurd lengths that these discussions have already.
At the very least I don't like that it lets people voice their opinion in one way and not the other.

**Comment by peppy** [comment]
@ppy/team-web how easy would it be to make this change?

- downvote no longer denies kudosu (dedicated button does that)
- downvote is available for all users, not just BN/NAT.

**Comment by nanaya** [comment]
so only upvotes are considered for kudosu?

**Comment by peppy** [comment]
upvotes and manual denials by BN/NAT, yeah.

**Comment by nanaya** [comment]
should the (down) voters be visible to everyone? 

![](https://s.kohaku.love/2024/07/firefox_2024-07-29_22-39-01.png)

**Comment by cl8n** [comment]
> should the (down) voters be visible to everyone?

ya i dont think anything else needs to change

(also sorry i didnt unassign this but seems like u got the memo lol)
