### ISSUE TITLE
Allow mappers to alter the colors and timing of the in game title scroll

### ISSUE THREAD

**Issue by Antliaosu** [ppy/osu-web#11279]
So on the old osu website there used to be a feature that would allow for the alteration of the colors and timing of the title scroll. This allowed for some pretty neat effects, such as changing the color from white to multiple colors that complement the background and/or placing it during a break so it is visible when the screen lightens (for example: [https://osu.ppy.sh/beatmapsets/54672#osu/166126](url), [https://osu.ppy.sh/beatmapsets/107565#osu/281843](url), and [https://osu.ppy.sh/beatmapsets/23636#osu/84036](url)). Afaik this feature is no longer accessible on the new website, and because this is where it was previously present I was wondering if this could be added back in some way. Furthermore, I was also wondering if this could be made accessible to set owners as well, rather than bns/bats or whatever like how it was in the past.

Edit: 
As far as ranking goes, certainly some guidelines could be added to rc to ensure that people are not doing dumb things with the title scroll and ig the feature would have to made inaccessible after ranking.

**Comment by cl8n** [comment]
this has been denied for various reasons (#10643, #7326, #6023, #2395), basically it's considered a deprecated feature. even if it were reconsidered I would strongly suggest giving it a new format because the existing one is overcomplicated for what it does, see https://osu.ppy.sh/wiki/en/Beatmap/Title_text#formatting-options

as peppy said in some of the linked issues, you're probably better off suggesting this in the lazer repo (both to support showing legacy title text and suggest a replacement feature going forward)
