### ISSUE TITLE
tooltip is centred if link text is overflowing

### ISSUE THREAD

**Issue by MegaApplePi** [ppy/osu-web#1248]
![2017-06-13_23-07-41](https://user-images.githubusercontent.com/14264992/27115023-7821a2ca-508d-11e7-921e-27d497308f6a.png)
If the link's text is overflowing into a new line, the hover text is centred.

**Comment by notbakaneko** [comment]
This seems to be an issue with how qtip calculates the offset and widths for the positioning of the tooltip itself.

qtip is using jquery's `.offset()`, however, when text gets wrapped, the client bounding box around the text expands to cover all the lines; the left edge is now where `tutorial` begins, and the width is now the entire line instead of just the link.

I'm not sure what we can do to fix it other than forking it and making it calculate off the `clientRects()` instead.
