### ISSUE TITLE
Navigation in modding system doesn't reflect in URL

### ISSUE THREAD

**Issue by peppy** [ppy/osu-web#1596]
- Clicking an issue in history then going back doesn't take you back to history.
- Selecting a tab doesn't update the URL (probably should).
- Selecting a filter mode doesn't update the URL (probably should).

**Comment by senoppai** [comment]
If navigating the site would track the buttons and dropdowns, it would be a great quality of life improvement. Currently, refreshing the page or pressing back does not take you back to where you were.

If you used the 'a'(URL link) DOM element in the HTML instead of buttons when clicked. With an href attribute; such as "#page-a; #page-b": it would update the URL to have that fragment(the #...) at the end. Which is visible in the URL when parsed by JS. If you refresh the page after doing so, the fragment would remain. This would enable you essentially "save" the location of clickthroughs present prior to refreshing the page.

**Comment by peppy** [comment]
Yep, this is a pretty important one to get solved. It can be mildly frustrating to link another user to a page and have them arrive at a completely different view to what you expect.
