### ISSUE TITLE
Favourites missing on new beatmap listing

### ISSUE THREAD

**Issue by ProfessionalBox** [ppy/osu-web#1692]
Now that the new beatmap listing is being forced on maps even though it feels unfinished I wanted to ask for hotfix on something that not only I found annoying but other mappers aswell.

All favourites on a map are now treated as a tiny number and the mapper can't tell at all who have favourited the map and that is really frustrating. I think looking at who I have impressed enough to make them favourite my maps is the thing I look at the most when I check out how the listings of my maps are doing and making that just a tiny number besides playcount is just mind boggling to me. Please bring the old way of showing favourites back incorporated to the new website design or even better, make it so that there is a dropdown list for ALL of the favourites the map has gotten. I also think that seeing names you can recognize having favourited a map gives you immediate feedback on how good the map is and if it is worth downloading to some degree.

Thank you for your time!

**Comment by peppy** [comment]
We'll look at adding this back. lease report in separate issues any other reasons you feel the new page feels "unfinished" so we can also address those!

**Comment by tastystew** [comment]
+1 for this, alternatively we could also 'repurpose' hype as favourites, since they're both pretty much showing support for the map. could show both Hype count and Favourite count on listing, or merge them together. like if someone were to favourite the map, they could choose to leave a comment as well. and similarly, if timestamps were allowed, it could also be integrated into beatmap replay comments (the nico style scrolling text when watching a replay).
