### ISSUE TITLE
Resolved checkbox is easy to overlook when replying to discussions

### ISSUE THREAD

**Issue by peppy** [ppy/osu-web#1746]
As mentioned in https://twitter.com/ascendanceosu/status/930770066706231296, it looks like users are regularly posting a comment and forgetting to hit the resolved checkbox.

I think we should remove the checkbox and instead of two buttons, something like "Reply" and "Reply & Resolve".

**Comment by dorothy3242** [comment]
Mappers may want to intentionally not resolve mod posts they want further input on, so making reply/resolve one button may not be the best idea.
Instead, the resolve checkbox could be checked by default, so that they can still uncheck it if they want to, without having to worry about forgetting to check it for the majority of replies.

**Comment by peppy** [comment]
It would be two buttons. One would resolve and one wouldn't.
