### ISSUE TITLE
Modding V2 Issues / Suggestions

### ISSUE THREAD

**Issue by Sotarks** [ppy/osu-web#1792]
- fix the fact that i need to post a message and delete to mark resolved for gds.

- add a box or smth so GDers can post their update directly on their forum thread like you could add smth like only the mapper can add "who's the owner of this GD" and only him can post update on the update box (it will help)

- remove the fact that my email box gets spammed literally everytime someone post a word, make it only for the same dude idk if it's possible.

- make the description editable on the new website

- make a place where poeple can shitpost instead shitposting on the diff spread that's annoying

just copying stuff from my tweet : https://twitter.com/sotarksosu/status/933091233601241088

**Comment by MillhioreF** [comment]
Point 2 is intentional, last I checked guest diff mappers are considered as gifting their diff to the mapset owner - everything else is common courtesy.

**Comment by MillhioreF** [comment]
Point 2 is intentional, last I checked guest diff mappers are considered as gifting their diff to the mapset owner - everything else is common courtesy.
Point 4 is intentional, descriptions are going to be like tags in that they can only be edited by BSS.
Point 5 isn't gonna go anywhere, if people are 'shitposting' outside of valid praise in the praise section their comments should be removed.

Points 1 and 3 are valid, but please make separate issues for both of them.

**Comment by peppy** [comment]
you should not be deleting messages after you post them. what is your beef with posting "thanks" or "done" when resolving? it gives more context to your response.

**Comment by peppy** [comment]
@nanaya I think we should remove resolved changes when the resolving post is deleted.

**Comment by Xinnoh** [comment]
The GDer is saying the exact same thing as the mapper

Modder: fix thing
GDer: Thanks! I fixed this
Mapper: What he said (Marked as Resolved)

There is no point to having the mapper post, and takes up more of what little space mv2 has. 
If GDers were allowed to resolve posts, then the idea you put forward would be fine.

**Comment by peppy** [comment]
That will eventually be the case, but for now this is how we are doing things.
