### ISSUE TITLE
Create a feed that tracks map nomination status

### ISSUE THREAD

**Issue by Xinnoh** [ppy/osu-web#2029]
There should be a section similar to "New Approved Beatmaps" on the [new site](https://osu.ppy.sh/home). It should track when maps are bubbled, popped, or disqualified
The "New Approved Beatmaps" section covers qualified/loved maps already. Alternately, the new feed could be merged with it.

[Basically an onsite version of this](https://www.reddit.com/r/osugame/comments/6jcdvk/i_made_a_discordbot_for_qualified_map_changes_and/)

**Comment by Mirruuu** [comment]
Bumping this a bit to say https://osu.ppy.sh/beatmapsets/events?type=nominate exists and can be adjusted to be visible to nominators at the very least. 

Ephemeral also mentioned .json output which would be useful for the bots that track nominations as well (in Discord).

**Comment by Xinnoh** [comment]
Artist, Title, Mapper and modes would be plenty

**Comment by dorothy3242** [comment]
Clickable boxes for event types, like the ones on the users/#####/modding/discussions pages
![image](https://user-images.githubusercontent.com/33286824/42836249-7e6a77cc-89c8-11e8-9835-f6b431e7772a.png)
replace the suggestion hype etc with nominate / disqualify / resolved issues / reopened issues events
Otherwise you need to memorize/find things like ?type=nominate being added after /beatmapsets/events in the url to narrow down the results on the page to specific things

**Comment by osuMao** [comment]
There should also be options to filter by "user" and time with filters like "since" and "before" in order to search for events from a group of users within some range of time, which is useful in both applications as well as reviews, and in general makes the pages more flexible.
