### ISSUE TITLE
Limit maximum kudosu achievable in a single beatmap set

### ISSUE THREAD

**Issue by Naxesss** [ppy/osu-web#2040]
From the looks of things there is actually not a limit, unless it's set ridiculously high. See [this user's kudosu history](https://osu.ppy.sh/users/8688812), for example.
![image](https://i.imgur.com/aNBlPmr.png)
![image](https://i.imgur.com/3VNrqMJ.png)
![image](https://i.imgur.com/tgMqEWY.png)

**Comment by Xinnoh** [comment]
If implemented, cap needs to be based off map length. Having the same limit on a 30 second and 30 minute map gives no good outcome.

**Comment by peppy** [comment]
Based on map length sounds unnecessarily complicated.

**Comment by Mirruuu** [comment]
Just wanna show this from this user: https://osu.ppy.sh/users/4452992
![image](https://user-images.githubusercontent.com/25852637/34217505-f84f9c82-e5ab-11e7-9795-a86c23da6678.png)
This is all kudosu from one map (https://osu.ppy.sh/beatmapsets/706545/discussion) because of upvotes (some even on suggestions deemed unnecessary). There should definitely be some sort of regulation on kudosu at least for now, this is extremely high kudosu gain for one difficulty of a set of several lol.

**Comment by nanaya** [comment]
Added in #4620.
