### ISSUE TITLE
S/SS counts on the global leaderboard don't include silver S/SS

### ISSUE THREAD

**Issue by MillhioreF** [ppy/osu-web#2081]
![ ](http://puu.sh/yM7Wt/d001167bf2.png)  

The migration script seems to have taken this into account (Cookiezi's rank totals are correctly combined) but users that set scores after the migration regressed into not including silver ranks.

**Comment by peppy** [comment]
The reprocess is actually still running currently, so it's quite possible some users haven't been reached. What you are seeing above is correct numbers post-maintenance. The issue is that the ranking page is not adding the hidden numbers correctly (see https://github.com/ppy/osu-web/blob/1b689fde1f6d931d10f312c26510674102607c9e/resources/views/rankings/performance.blade.php#L73)

Should be an easy fix
