### ISSUE TITLE
Normal users should be able to reopen discussions

### ISSUE THREAD

**Issue by Xinnoh** [ppy/osu-web#2127]
Currently, only BN, QAT and Map/Discussion Creators are able to reopen discussions. If a discussion remains resolved, it will almost never be looked at again by the mapper. If someone agrees with another user's discussion and leaves a comment, the mapper will never see it because they can't reopen the issue.

example of this working well https://osu.ppy.sh/beatmapsets/709932/discussion#/39926

**Comment by Okorin** [comment]
could get confusing depending on whether or not the map has one nomination at the time of reopening, non-BNs shouldnt  be able to reset nominations this way at least

**Comment by dorothy3242** [comment]
Bumping this because after https://github.com/ppy/osu-web/issues/3360 and https://github.com/ppy/osu-web/pull/3419 **nominators** are no longer able to reopen issues either, despite both the issue and pr stating only the action of _resolving_ issues should be effected. (I still agree the ability to reopen should be expanded to all users)

**Comment by peppy** [comment]
Let's also make normal users able to open discussions, while we're here.
