### ISSUE TITLE
Reply box breaks IME

### ISSUE THREAD

**Issue by kj415j45** [ppy/osu-web#2138]
Here's Screencast
[Screencast_2017-12-30-02-08-15.mp4.zip](https://github.com/ppy/osu-web/files/1593660/Screencast_2017-12-30-02-08-15.mp4.zip)
If you scroll down to the buttom, then click on the reply box, IME will open but suddenly close

**Comment by peppy** [comment]
Which reply box are you talking about here? Context is king.

**Comment by kj415j45** [comment]
the reply box is at forum post's buttom

**Comment by LumpBloom7** [comment]
On portrait view, it seems this happens when the reply box position is locked by the page after reaching the bottom where the footer starts to show but the footer is not fully on screen.

But this doesn't always happen according to my testing. And after IME closes and without scrolling again try to use the reply box again, it'll work properly.

On landscape mode it happens as long as the reply box is locked by the page, and only scrolling upwards a bit until the reply box starts to follow will make IME work without closing itself.

I tested this on Chrome on Android with 291dpi.

**Comment by notbakaneko** [comment]
Replying while on a mobile device seems pretty broken in general with different combinations of:
- not being able to unpin the reply box because the button doesn't fit on the screen.
- on-screen keyboard can cause the page to only use the top half of the screen.
- pinned reply box can block entire view.
- unpinning causes the reply box to be deselected which makes the on-screen keyboard go away (and then tapping in the reply box causes it to get pinned and the on-screen keyboard comes up and pushes everything up and we go into a loop of fail)

**Comment by notbakaneko** [comment]
New summary issue as it's not practical to fix these issues individually: #4273
