### ISSUE TITLE
Character limit in mod posts - examples of when that would be need a raise (or alternative).

### ISSUE THREAD

**Issue by Nicarim** [ppy/osu-web#2164]
There are quite a few times people need to express things in more than 500 characters limit. For example if they're trying to make a justification to their change that they suggest.

We should discuss reasoning for this - and possibly find a middle ground between people who think it should be higher - and the ones who keep on insisting it should be as concise as it should. Some examples to justify first: 

http://prntscr.com/hvogx7

https://media.discordapp.net/attachments/136581774036828160/398207678880677898/unknown.png?width=561&height=676

http://prntscr.com/hvoh8x -> https://pastebin.com/vk6Gru7e
  
Maybe a place for mod to put extended reasoning that would be hidden in a spoiler by default? Which would have no character limit?

Proposed solution by ppy: If general user base agrees that this needs a raise - he is more than welcome to discuss it.

**Comment by error-exe777** [comment]
i think the idea of a spoiler box is a cool idea. but then again, it would basically be the same as a mod point but within a closed environment so doesnt make much of a difference. i would personally prefer a whole new page dedicated to beatmap discussion, where people can give ideas and contribute to the discussion, rather than it being nestled in a drop down. it would kind of act like the old forum in a way, but with no modding. you could also add IRC modding somewhere there so it doesnt get completely phased out.

**Comment by Nicarim** [comment]
I do think a section where you concisely explain change (i.e. visible part) and section where you're able to justify that in your words - could actually solve most of the issues people have it it - including IRC Mods, and the discussion section.

**Comment by error-exe777** [comment]
yeah that wouldn't be a bad idea. i think the main problem with the character limit is that people want to explain things in much detail when talking about maps on the grand scheme, like this screenshot here https://media.discordapp.net/attachments/136581774036828160/398207678880677898/unknown.png?width=561&height=676

people dont have a problem with the way mod points work now, since most people have no reason to go above 500 characters but i feel like there should be something implemented for the people that do go above 500 frequently.

**Comment by Xinnoh** [comment]
Make two comments if you need to write more, not exactly at the top of priorities to implement something like this for now

**Comment by peppy** [comment]
Making two comments is a valid work-around. We've also discussing reducing the characters taken up by timestamps (one of the reasons such a short post hit the limit).

Please post links to actual discussion pages rather than links to screenshots (ambiguous, can't see raw content) and pastebin ([can't even load](https://www.theregister.co.uk/2018/01/02/intel_cpu_design_flaw/)) when making issues.

Adding "extended" or any more complexity is not going to happen. If *anything* the chartacter limit would just be increased to 600 or something.

**Comment by Celektus** [comment]
Another example of a very long broad mod post that had to be split up into multiple parts

- Permalink: https://osu.ppy.sh/beatmapsets/708763/discussion#/81269
- Map Discussion: https://osu.ppy.sh/beatmapsets/708763/discussion
- Screenshot of the post: https://i.imgur.com/OIWucfz.png

I think even 750 in the general section might be not enough yet for this sort of more subjective overall criticism style of modding. In case this one comes of as too unnecessary and in-concise, I'd argue you could make similarly long post on Discussions of new mappers that need this sort of broad criticism to actually learn something about vague concepts etc. 

I asked some people who would generally suggest about 25000 Characters as enough to be helpful, the post I referenced used about 1600. Either something among those lines or another more complicated method of allowing for more Characters without encouraging people to post V1 style mods

**Comment by peppy** [comment]
That would be better written as a wiki entry and then linked to, in my opinion.

**Comment by Lewskl** [comment]
Making a wiki entry is quite a lot of work just for a 2500 character mod post and doesn't even really make sense (to me, at least) if the topic is very subjective.

**Comment by error-exe777** [comment]
there are so many different types of these mod posts though and making a wiki entry for every major problem somebody comes across is just an inconvenience if anything. 

disqualification reasons are a massive drag as well, since somebody did say to me being limited to 750 characters when explaining major problems just gets in the way. even worse when trying to discuss. You basically have to wall-post to explain properly and its just more annoying to have to split your ideas into up to 3 or 4 separate messages. 

i mean, like Celektus said, maybe raising the character count in the general and general (all difficulties) section to something much higher like 2000-3000 would kinda fix the problem, and still ensure people are concise with points on the timeline (?)

i dunno, but thats an idea?

**Comment by peppy** [comment]
I believe this is no longer applicable.
