### ISSUE TITLE
Allow for clicking on your username to instantly take you to your profile

### ISSUE THREAD

**Issue by dorothy3242** [ppy/osu-web#2392]
Like on the old website
![image](https://user-images.githubusercontent.com/33286824/36223001-0552efea-1191-11e8-8b9f-b509092a49a7.png)
this part here
one's own userpage can be one of the most visited by any given user on the website, as it allows them to check their top scores, stats, and more. Unlike the old website, you have to click your profile name/avatar, THEN click on the link on the profile to get there. It gets annoying after a while when on the old website you can get there in a single click from the homepage.

So the suggestion is:
make clicking the name take you to your own profile instantly, and clicking on the avatar to bring up the same panel it currently does.

Either that or add a link to it here on the homepage:
![image](https://user-images.githubusercontent.com/33286824/36223097-52e65aa8-1191-11e8-8b88-4cbd0bb8a776.png)

Just **some** way to get there more easily

**Comment by peppy** [comment]
I disagree with name and avatar having different behaviour. @arflyte any ideas?

**Comment by arflyte** [comment]
While I agree we need a faster way to get to your own profile, giving different behaviour to name and avatar will be confusing. It was designed that way to ensure that you can get to links to all of your personal stuff (profile, team profile, settings, team settings etc). I have no quick solution for it, for now; I'll look into it again soon. It definitely will be there in the new design.

Can't add profile to homepage navigation because User Profile is not part of homepage; it will break the design and flow.

**Comment by Joehuu** [comment]
Can you put it here?
![](https://puu.sh/zoNk6/4b3b5911bd.png)
![](https://puu.sh/zoNju/3b2d50994f.png)

**Comment by peppy** [comment]
Could be a good compromise.

**Comment by arflyte** [comment]
Yeah. That's a fine idea.

**Comment by dorothy3242** [comment]
Closing in favour of https://github.com/ppy/osu-web/issues/2915 due to header design changes and such o:
