### ISSUE TITLE
Add ability to prevent nomination

### ISSUE THREAD

**Issue by osuShiro** [ppy/osu-web#2488]
Similarly to how Nuke icons worked in the old forums, where a beatmap that received the icon was deemed invalid and officially disallowed for ranking, there should be a similar option for Beatmap Discussions where a QAT (not a BN) can disallow the mapset from being nominated.

The "nuke" (probably needs a different name) button should possibly also lock the discussion (up for debate, it might be a good or a bad idea). (see #2273)

EDIT: this should also be toggleable off, if the map received sufficient improvement not to warrant it anymore.

**Comment by JBHyperion** [comment]
Nuke icons and thread locking were often done in tandem, but weren't totally linked with one another. For something approaching the "old method", you'd need something to block nominations AND a (temporary) means of preventing discussion.

I say temporary because Nuke icons were used to determine a map as "unfit for ranking in their current state" and would often be revisited after a cooloff period to make major fixes.

If a map is outright unfit for Ranking due to inappropriate content, etc., it's usually just removed regardless of whether it was aiming for Rank or not.

**Comment by cl8n** [comment]
this was later brought up again as a forum thread, and dismissed here https://osu.ppy.sh/community/forums/posts/7927111
