### ISSUE TITLE
No trend line in charts on user profile

### ISSUE THREAD

**Issue by Joehuu** [ppy/osu-web#2615]
It is the faded gray line. The line of best fit or trend line is decreasing for this person.
![](https://puu.sh/zzfE2/877bf74b1b.png)
![](https://puu.sh/zzfEY/74e99c3c83.png)

**Comment by Xinnoh** [comment]
I don't think this is needed since it doesn't really provide any information that can't be seen.
If it is implemented, the line should change from linear to log or power series, eg the line below is rising, but that's not correct.
![screen shot 2018-03-03 at 9 21 07 am](https://user-images.githubusercontent.com/30382015/36928822-5506d9a8-1ec4-11e8-943a-bb95d7a83d49.png)

**Comment by peppy** [comment]
As discussed internally, the trend was just to add extra texture to the graph (make it look more technical). Implementing it with the new design would be counter-productive as the design is changing with @arflyte's user profile redesign anyways.

Needless to say, I do agree that the new graph looks worse than the old one, but we are working on this.

**Comment by nanaya** [comment]
Closing this issue as the trend line itself isn't coming back. And as mentioned, it's easier to just look at the full chart itself, especially considering values for individual data points can now be checked.
