### ISSUE TITLE
Add delay to search box

### ISSUE THREAD

**Issue by kj415j45** [ppy/osu-web#2667]
When typing in search box, it would send request when each letter was pressed. This cause stuck on lower performance device, and increase request bandwidth. Better set a 500~2000 ms delay before request.

**Comment by peppy** [comment]
Surely debounce was added from the start o_O

**Comment by nallown** [comment]
Yup and I can confirm, the search does already have a debounce set on it.

You just need to take a look at line 21 of this code below.

https://github.com/ppy/osu-web/blob/5420da692f42a7371c9c92c049f0e8cceb4b9165/resources/assets/coffee/_classes/nav-search.coffee#L19-L30

**Comment by kj415j45** [comment]
`Timeout.set(0)` o_o;;

**Comment by nallown** [comment]
I think that's to fix the asynchronous nature of DOM updates that happen in react components because if you look at the padResult function then you can see that it uses a lot of query selectors.

https://github.com/ppy/osu-web/blob/5420da692f42a7371c9c92c049f0e8cceb4b9165/resources/assets/coffee/_classes/nav-search.coffee#L47-L59

Basically, imagine you have a data attribute for `username` and you render that attribute using react a template strings like:
```html
<div>{{ username }}</div>
```

Well basically... If you set username to `kj415j45`, the DOM doesn't update right away, it takes ONE tick for the changes to get seen in the DOM.

So if you query selector the content of that div _right after_ you've set the `username` data, the content isn't going to be `kj415j45` right away. You have to wait ONE tick (aka a millisecond) to see the changes in the DOM.

So that timeout is there to make up for that single tick wait.
