### ISSUE TITLE
Modding discussion permalinks should work in disqualification reason

### ISSUE THREAD

**Issue by dorothy3242** [ppy/osu-web#2715]
![image](https://user-images.githubusercontent.com/33286824/37545821-b5bdae30-2940-11e8-928c-170ed4bbd849.png)
a disqualification reason such as this can be a bit frustrating to figure out exactly what it's trying to refer to, as there is no way to get to the linked reason directly, you'd have to copy+paste it. These links should be made clickable like they are when linked in modding posts.

**Comment by peppy** [comment]
Let's get this in sooner rather than later.

**Comment by nanaya** [comment]
Isn't that what disqualifying-by-posting-issue (nomination reset) is for?

**Comment by peppy** [comment]
Is that already a thing? I'm a bit out of touch.

**Comment by nanaya** [comment]
I think so.

**Comment by peppy** [comment]
#2714 maybe?

**Comment by nanaya** [comment]
So removing disqualification and require reset instead? And perhaps with message preview or something in addition to the link.

**Comment by nanaya** [comment]
Or just post problem to general all when someone do disqualify with reason as its post content.

**Comment by Okorin** [comment]
current process is QAT only:
- Press DQ Button, give a reason, Map ends up DQ'd with that reasoning being displayed on the top like in the screen on #2714 
Beatmap Nominators / QAT:
- If a map has one nomination and a nominator posts an issue, the nomination resets to nothing and the listing will show "Nomination reset by new problem `#{problemId}`

-> if you want to make this more simple, a QAT posting an issue on a qualified map could automatically put the map back into pending with a nomination reset

-> Or require posting / referencing an issue when clicking the disqualification button as a QAT when you click the DQ button

---
Maybe a bit more context on what people do about qualified maps right now can't hurt:

Automatically DQing actually undermines community feedback because qats then can't post issues that someone else has to sanity check before a disqualification happens (current process for everyone is, find an issue, point it out, [get someone to sanity check and dq for your issue via this thread](https://osu.ppy.sh/forum/t/447428)) - sanity check would be lost if qats couldnt post issues in qualified that would require someone else to look over it.
