### ISSUE TITLE
Medal sections on profile are inconsistent

### ISSUE THREAD

**Issue by NoffyNoffeh** [ppy/osu-web#2825]
For instance on this profile https://osu.ppy.sh/users/1576498#medals it goes
Skill | H**ush-Hush**
Beatmap Packs | Dedication
Mod Introduction

but then on this one https://osu.ppy.sh/users/6933054#medals it goes
Skill | Dedication
**Hush-Hush** | Mod Introduction

and that's just on their standard tabs, it differs often between modes and nearly any profile I've visited trying to figure out why this is.

These sections of medals should be placed more consistently in comparison to one another, or else you end up just wasting time when browsing other's profiles (or your own!) trying to find a particular medal section. Currently the orders seem almost nonsensical.

**Comment by peppy** [comment]
We really need to reorganise the medals section to take up less room. maybe a tab control for each section with achievement counts for each one in the tab? That might be nesting too much.

@arflyte hi :D

**Comment by nanaya** [comment]
The grouping order has been fixed since a long time ago.

There isn't much way - short of redesign - of getting around grouping moving around between left and right due to them just being rendered in order and groupings with no achieved medals are hidden.

There are a few other open issues related to redesign (#8628, #9210) so this one which mainly about grouping order can be closed.
