### ISSUE TITLE
Use square border for avatar on the header

### ISSUE THREAD

**Issue by venix12** [ppy/osu-web#2918]
As avatars are squares it would work better if the border would be a square too I think.
Roundy one might look kinda awkward on some avatars like for example on mine
![](https://venix.s-ul.eu/iBSL1BmJ)

**Comment by Lyawi** [comment]
Isn't it a common thing on websites over the years now? Fix your avatar instead lol

**Comment by VenixOSU** [comment]
I don't think so my avatar is a problem, osu! used to have the square format and also profile page is still using it.

**Comment by peppy** [comment]
Going to leave this open since I'm not sure I agree with circular either.

**Comment by yayuhhzz** [comment]
replying to this instead of making a new post. I also feel that the new website should use a square border as it reflects the avatars seen in-game on the f9 social tab/leaderboards. After using the new site more often now it has become a tad annoying seeing parts of my avatars get cut off. I think it would be a quick fix that wouldn't take away from anything, but will make most users happy that do use the full space for their avatar.
some examples:
![old site avatar](https://user-images.githubusercontent.com/38289568/71974632-9540c100-31d7-11ea-8f4e-e4f1ca6a256d.PNG)
![new site avatar](https://user-images.githubusercontent.com/38289568/71974633-983bb180-31d7-11ea-8a01-11c85f37fabb.PNG)
![idke 1](https://user-images.githubusercontent.com/38289568/71974561-64608c00-31d7-11ea-8e74-9f2970878557.PNG)
![idke 2](https://user-images.githubusercontent.com/38289568/71974570-675b7c80-31d7-11ea-9bd9-78635bdbf943.PNG)

**Comment by peppy** [comment]
I don't think we'll be going back to completely square avatars ever. But we also won't be doing circular.

**Comment by nanaya** [comment]
I don't think anything will be changed here.
