### ISSUE TITLE
There is no Flag for Kosovo

### ISSUE THREAD

**Issue by Yoruichi-SamaK** [ppy/osu-web#2919]
If you Start Playing osu in Kosovo your Profile Shows the Serbian flag instead of  Kosovos flag (Kosovo is an own Country with bis own flag so) please fix that
Thank you

**Comment by peppy** [comment]
Let's double-check how many players are in this country before spending the time adding a flag (unless we already have one available).

**Comment by booms5551** [comment]
There are quite some players from Kosovo but most of them are albanian so they chose the flag of Albania and I'm one of them.
However in game it can depend on your internet provider as well because I'm from Kosovo and I used two different internet providers one of the first (kujtesa|) showed that I was from Albania in game while the second one which I highly dislike shows that I'm from serbia in game.
I tried fixing the second one by contacting Osu Support but they told me they can't do anything about it.

Idk if Yoruichi knows but in the website you can select your country to Albania instead of serbia,I'm sure you wouldn't mind it since you're albanian.
Anyhow,the in game problem depends on your internet provider.

**Comment by Yoruichi-SamaK** [comment]
Okey thanks for your help

**Comment by Yoruichi-SamaK** [comment]
Flm ;)

**Comment by arflyte** [comment]
![kosovo](https://user-images.githubusercontent.com/3632750/38986598-d89c4efc-4407-11e8-9b8a-dae8f18f4c46.png)
![kosovo 2x](https://user-images.githubusercontent.com/3632750/38986599-d8c04ab4-4407-11e8-800f-801b2f805f50.png)

**Comment by nanaya** [comment]
Apparently the flag has been there forever. It's just not in database or used at all.

https://osu.ppy.sh/images/flags/XK.png
