### ISSUE TITLE
Beatmap sorting options (may be) slightly difficult to distinguish

### ISSUE THREAD

**Issue by arkaderd** [ppy/osu-web#2921]
https://osu.ppy.sh/beatmapsets
With the mix of the color white everywhere (Also the color of selected sorting options), it may be a little hard to distinguish selected sorting options at a glance. Could change the font color to yellow for selected options. 

Also could change the white panel behind the beatmaps to be gray (also makes play/favorite numbers and thumbnails on beatmaps more distinguishable)

There is also an issue of inconsistent font size for "expanded" sorting options after expanding the list of options to choose from. Strangely enough, this does not affect the sorting genres (Genre, Language, Extra, etc.)

**Comment by Numailia** [comment]
area behind the filter options isn't themed.... it uses bg from the top search result 
making that text yellow would just make it blend in more with a yellow map bg
area behind play/favorite numbers is not strictly themed, depends on bg as well
![screenshot_20180406-002641](https://user-images.githubusercontent.com/18292514/38403585-7deaf308-3932-11e8-84dc-a8356f80b107.png)

font size difference of the extra sorting options is intentional because those ones are almost never used

**Comment by arkaderd** [comment]
@Numailia My bad, when I refreshed, the image at the top stayed the same, didn't know it was dynamic
