### ISSUE TITLE
Tooltip to Show Date of the Post?

### ISSUE THREAD

**Issue by AncuL001** [ppy/osu-web#2948]
![applicationframehost_2018-04-09_12-24-59](https://user-images.githubusercontent.com/16044057/38480692-248af7c4-3bf1-11e8-85ba-3437034b202a.png)
currently not present on the current forum and i think this is important

**Comment by Lyawi** [comment]
![chrome_2018-04-09_07-31-15](https://user-images.githubusercontent.com/32525896/38480821-0ccb1822-3bc8-11e8-8dc0-baf00158d452.png)

?

**Comment by dorothy3242** [comment]
![image](https://user-images.githubusercontent.com/33286824/38480795-9099e7d8-3b95-11e8-9c6c-7d3f394751fc.png)
It shows if you hover over the "27 days part" but not if you're hovering over the "posted" part. 
It does exist, but maybe it should be the entire thing that causes the date tooltip to display since it all shows the underline indicating it's a link when hovered.

**Comment by Joehuu** [comment]
You are using edge, there is a problem with the offset from the issue you made in #2926.

**Comment by AncuL001** [comment]
oh yea
