### ISSUE TITLE
Live post preview when replying

### ISSUE THREAD

**Issue by peppy** [ppy/osu-web#30]
Currently the live post preview is only visible when creating a new topic. Would be nice to have it when replying also.

**[Bounty](https://goo.gl/nFdoyI) offered**: 250

**Comment by nanaya** [comment]
design wise this looks impossible. Unless by "live" you mean tabbed just like github.

**Comment by peppy** [comment]
tabbed is an option, for sure.

**Comment by TheHowl** [comment]
I don't see this as 'impossible'. [Ghost](https://ghost.org/) and [Dillinger](http://dillinger.io/) allow you to write markdown and parse it real-time as you type it. If you want to see a real-life example of a forum bullettin system which does the same, check out [NodeBB](https://nodebb.org/). Last time I checked it they did it in a bit different way to what we're doing (instead of putting the response form inside the forum body, they made a 100% wide container pop up from the bottom from which the user could type their response to the thread and thus see the preview).

We could also just settle for the way we are doing it in the topic creation (create a new fake reply at the bottom of the thread containing the preview of what we are writing inside the response-creation form).

**Comment by Soinou** [comment]
Why not add a preview button that will pop up rendered markdown in something like bootstrap modals ?

Doesn't add anything to the page, you can still check your answer, and it's doable with only a bit of javascript.

**Comment by Heinzen** [comment]
What are browser supports required for this one?

**Comment by peppy** [comment]
latest chrome and firefox are a must, IE is always nice where possible. mobile browsers should be checked too, although functionality like this could be restricted to desktop if space becomes an issue.

**Comment by peppy** [comment]
Increased bounty to 250. Highly recommend implementing a tabbed approach to start with.

**Comment by steffandonal** [comment]
I'd like to claim this one!

**Comment by Aquazus** [comment]
Claiming for 25 days.

**Comment by sn0w** [comment]
Re-Claiming for 25 days

**Comment by sn0w** [comment]
This is the result of my first iteration.
Any feedback on the design?

BB-Code:
![](https://fs.lukas.moe/jepr76dzpc00.png)

Preview:
![](https://fs.lukas.moe/nzhds2k2kg0w.png)

The current implementation fades between the two views with 300ms long jQuery animations.

**Comment by peppy** [comment]
This is a good start. Not sure a fade it needed though.

**Comment by LiquidPL** [comment]
Should the reply box check whether the reply has been changed since generating the previous preview before requesting a new one?
