### ISSUE TITLE
Let [youtube] BBCode work

### ISSUE THREAD

**Issue by Lyawi** [ppy/osu-web#3133]

**Comment by MegaApplePi** [comment]
The `[youtube]` tag works, do you mind pasting the BBCode you tried?

**Comment by Lyawi** [comment]
```[youtube]-kv10eAxJiM&list=RD-kv10eAxJiM[/youtube]```

**Comment by MegaApplePi** [comment]
Hmm, the `[youtube]` tag works if you only pasted just the video ID, `[youtube]-kv10eAxJiM[/youtube]`.

There is a way around this to add a playlist using BBCode, but I assume it would get fixed at some point. The `&list=RD-kv10eAxJiM` is missing a few things:
- That ampersand (`&`) needs to be a question mark
- You will then need to add an ampersand (`&`) at the end of the `list` argument. This will bypass the `?rel=0` thing that osu-web does.

So it should look this:
`[youtube]-kv10eAxJiM?list=RD-kv10eAxJiM&[/youtube]`

---

Though, that means you can also do some miscellaneous stuff that the YouTube iframe API allows, like change the seekbar colour to white, disable keyboard controls, and ~~autoplaying (if not using the latest Chrome version)~~ (probably should do that since it is against the rules), etc.

`[youtube]-kv10eAxJiM?list=RD-kv10eAxJiM&version=3&disablekb=1&autoplay=1&color=white&[/youtube]`
