### ISSUE TITLE
Display Downloads/Plays on all Beatmaps

### ISSUE THREAD

**Issue by downpour-osu** [ppy/osu-web#3359]
Often, as a new mapper, it's really disheartening because it really feels like you're releasing maps into the void- most players don't know how to use the favorites system or even what it is. A lot of mappers quit because the quality of the ranked section is very high now, and takes a long amount of time to rise to that level. A simple download/play counter on unranked maps would go a long way, and a 32 bit number should handle it just fine and shouldn't be terribly hard to implement (I think). 

Thank you so much! This is my first time using github, so please let me know if I did anything wrong. This idea received positive feedback in the mapping channel of the osu!dev discord so I figured it might be worth it to post here.

**Comment by downpour-osu** [comment]
This will have been up for **two years** in like 2 weeks. Given that I am always told that "anyone can contribute and have their ideas discussed, you just need to spearhead it properly" I would love to see ANY sort of response/action related to this. So many people have expressed support for this proposal especially, it is disheartening to see that it has gone nowhere.

**Comment by cl8n** [comment]
complements #5520 , both of these would be great to help search through the huge volume of unranked maps

**Comment by cl8n** [comment]
is this easily possible? on top of the reasons above it would be a huge help for project loved-- we're looking for more ways to discover audiences for unranked maps, because the only metric we have now is favorites, and those doesn't say a whole lot about how much people want a leaderboard on it.

I think unranked maps should count for these stats:
- beatmap playcount
- user playcount
- `osu_user_beatmap_playcount`
- `osu_user_month_playcount`
- user play time

might be nice if they appeared in recent play history too but that's not necessary for this issue

**Comment by peppy** [comment]
This has been added score-submission side and will be in the next cutting edge release. Closing this issue, please open further issues if UI/UX changes are required for the listing etc.
