### ISSUE TITLE
Russian specific language category for beatmaps search

### ISSUE THREAD

**Issue by Lyawi** [ppy/osu-web#3376]
Since this involves the new website too I'll leave this here. 
https://osu.ppy.sh/community/forums/topics/762484

**Comment by 3mplify** [comment]
Is this real to see this feature in this nearest future?

There are at least 78 Russian songs in osu! Ranked (Sweden songs are only 15) and 2 Loved (Sweden - 0) Is there any probability that we could see Russian language in search options instead of other? 
List of Russian songs in osu!: https://t.co/XYmexo8i0d

**Comment by Shmiklak** [comment]
I already mentioned this long time ago, and the suggestion wasn't applied yet. Is it really that hard to add a category for the search system?

**Comment by dorothy3242** [comment]
This has been added with PR https://github.com/ppy/osu-web/pull/6176/

will be working on changing the genre for existing ranked maps, issue can be closed.
