### ISSUE TITLE
Wrong usergroup displayed in moddingv2 panel

### ISSUE THREAD

**Issue by Lassikko** [ppy/osu-web#3521]
![](https://lassikko.s-ul.eu/vhfW5GO0.png)

https://osu.ppy.sh/users/2757689
Toy shows up as a QAT in moddingv2 despite it not being their default usergroup.
example: https://osu.ppy.sh/beatmapsets/749623/discussion#/159030

**Comment by Kuron-kun** [comment]
It also happens with some other users (MillhioreF and flyte, for example), but only in moddingv2 panel. Since they do not have any forum colors and known permissions, and yet they show up as yellow Admins, I guess it's probably worth to point it out too.

Examples:

Millhiore: https://ninkeron.s-ul.eu/cr7gzWSC
https://osu.ppy.sh/beatmapsets/346218/discussion/764310/timeline#/168054

flyte: https://ninkeron.s-ul.eu/u3xaHG6D
https://osu.ppy.sh/beatmapsets/351408/discussion/787707/timeline#/60

**Comment by cl8n** [comment]
the yellow color is a fallback for anyone with extra privileges (qat, bn, admin) on this page, if they don't have a user color. I don't think this is an issue; it would be even more strange if they were colored normally but had extra permissions
