### ISSUE TITLE
Page loading slowed and page width broken on some beatmap pages

### ISSUE THREAD

**Issue by TPGPL** [ppy/osu-web#3657]
happened on https://osu.ppy.sh/beatmapsets/320118#osu/714001

![](https://puu.sh/Btfqv/bbba0503b4.jpg)

screenshot taken after scrolling from the comment section to the top of the site

**Comment by Aergwyn** [comment]
The image is not available.

**Comment by TPGPL** [comment]
@Aergwyn weird i can access it normally, will upload to puush then

**Comment by peppy** [comment]
What browser is that (and what version)?

**Comment by TPGPL** [comment]
Mobile, Google Chrome (68.0.3440.91)

**Comment by cl8n** [comment]
there's a super long word in a comment by KaochiDesu919 that did not get wrapped, causing this (seems like all wrapping on long words is broken)

**Comment by omkelderman** [comment]
page loads normally for me (android 8.0.0, chrome 69.0.3497.86).

however, I can zoom out to the zoom level showed in that screenshot due to some comments far down the page being super long one word phrases (![](https://cdn.discordapp.com/attachments/188630616286167041/489083631894003732/Screenshot_20180911-164119.jpg)).

Also note that when I zoomed out and scrolled back to the top it looked exactly the same to me as in the screenshot from TPGPL, after a while, the background image of the map loaded. (altho I'm sure it was already loaded when the page originally on correct zoom level showed to me, but I might be mistaken...)

**Comment by notbakaneko** [comment]
closed by #3662
