### ISSUE TITLE
Add ability to rearrange profile sections from header menu

### ISSUE THREAD

**Issue by peppy** [ppy/osu-web#379]
Rearrange own profile sections by dragging the links at the top of the page:

![](https://puu.sh/nciOn/bc3e2e39a0.png)

**[Bounty](https://goo.gl/nFdoyI) offered**: 30

Bounty may increase depending on whether we need design iterations. Initial implementation doesn't need any specific design, just functionality.

**Comment by LiquidPL** [comment]
This is actually somewhat tricky. 

In my current implementation, only the tabs' order is dependent on the state, as they need to be reordered with the sections.

However, when I make both tabs and sections state-dependent, something breaks, as when you reorder any of those, it snaps back to original, with the other behaving as expected.

I assume it's because React doesn't expect anything besides itself to change the DOM, which is what the sortable does.

I guess I will have to find a more React-compatible library, or write a drag and drop implementation from scratch.

**Comment by peppy** [comment]
Has been completed by @nanaya.
