### ISSUE TITLE
[Proposal] Use MariaDB in place of MySQL for compose

### ISSUE THREAD

**Issue by sr229** [ppy/osu-web#3858]
According to a performance benchmark done by the [MariaDB foundation](https://mariadb.org/performance-evaluation-of-mariadb-10-1-and-mysql-5-7-4-labs-tplc/) themselves comparing MySQL (10.1 on the blog) and MariaDB (5.7.4-labs-tplc), MariaDB can present more performance on non-compressed and compressed tables, even more performant with a larger server for it.

![image](https://user-images.githubusercontent.com/14976516/47952507-716a6580-dfab-11e8-8f7f-403b1a783cdb.png)

I think we can use MariaDB since its binary-compatible with MySQL for Compose, since some operations may be faster than MySQL, which is required if you're doing rapid prototyping.

**Comment by peppy** [comment]
It is not compatible with some features we use. Database structure would have to change.

**Comment by peppy** [comment]
On top of that, we are using a custom mysql configuration for development purposes that will likely outperform mariadb (while been non-acid compatible).

**Comment by peppy** [comment]
Also mysql 5.7 is old (we are using 8) and you got the versions around the wrong way. Huge improvements have been made especially in multi-core performance. Even not considering that, the benchmark shows almost no benefit at low client counts (generally during development the client count will be 1).

If you consider this a serious issue please do an actual test with the pp deployment (since that's the only case where the database may be challenged) on both mysql8 (using our configuration) and maria10.x.
