### ISSUE TITLE
Allow for selectable difficulty icons

### ISSUE THREAD

**Issue by NoffyNoffeh** [ppy/osu-web#3917]
Potentially, this could take the form of a box on the beatmap listing where you can choose one of the icons which would appear when hovering a difficulty icon. The ones that aren't selected would be darker/grayed out and colored on hover/selection.
![image](https://user-images.githubusercontent.com/33286824/48960485-fad1df80-ef3a-11e8-816a-9ec343243648.png)

This would be good because icons are often inaccurate to the intended difficulty level, especially on edge cases like 3.6* insanes or 2.3* normals. Users can already set the name of the difficulty, so being able to set the icon to what difficulty it is meant to be would make sense. 

With this it'd be easier to see at a glance on the beatmap listing what the spread of a map is actually like, such as ENHI instead of seeing NNHH - which makes it look like there's two normals and two hards when that's not the case at all.

This would be changeable by:
- the mapper, when a mapset is in pending/wip/graveyard
- QAT and higher when a mapset is in any state.

By default, icons would be set automatically by star rating the same way they currently are.

**Comment by VINXIS** [comment]
this would be a major step up from the current state but it may just be a good idea to have icons based on each star instead of diff icons since this would cause inconsistency with past sets, assuming that the QATs arent going to go through every single set in the past

Kite suggested that there could just be a colour for each star, and a gradient between each, 
Quoted from him:
```
so if you put green for 2sr and everything under, blue for 3sr and yellow for 4sr and red for 5sr purp for 6sr and black for 7sr and higher you get a good coloring system
i guess this is what i mean 
if it wasnt clear
```
![1](http://puu.sh/CIXsr/84ccb3727c.png)
![2](http://puu.sh/CIXwe/15b79e59e2.jpg)
![3](http://puu.sh/CIXxo/eb0238ff37.jpg)
![4](http://puu.sh/CIXyt/cc75076d9c.jpg)

except with nicer looking colours and stuff, could probably even use the current colours use as well

**Comment by cl8n** [comment]
I started on the original proposal, not sure how to color/pad this tooltip to make it look okay though
should it even be a tooltip?
![](https://up.clayton.cc/fae4f2.png)

**Comment by squirrelpascals** [comment]
> this would be a major step up from the current state but it may just be a good idea to have icons based on each star instead of diff icons since this would cause inconsistency with past sets, assuming that the QATs arent going to go through every single set in the past
> 
> Kite suggested that there could just be a colour for each star, and a gradient between each,
> Quoted from him:

I'm not too much of a fan of this, because I feel like all the various colors would be pretty hard to keep track of and doesn't give much visual continuity between diffs. For example, if there was a 1.3* gap between two diffs in a set, having 3 colors to represent 2 difficulties feels like bad design.

I absolutely love the original idea, to add to it we could implement icons for advanced, hyper and light insane diffs as well!

**Comment by NoffyNoffeh** [comment]
Closing as it's no longer relevant with gradient colored icons replacing the hard boundaries
