### ISSUE TITLE
Display timezone for "Estimated to be ranked..." date

### ISSUE THREAD

**Issue by NoffyNoffeh** [ppy/osu-web#3926]
on the modding page there's a display of the estimated day a map will be ranked, however it is not clear from the page itself whether this is in some osu! determined timezone or a user's own. There is no indication of what timezone it is for.

Sometimes maps will seem to rank a day earlier than the estimate given, it is currently unclear whether this is due to the estimates being inaccurate or due to the timezone of the estimate being different than that of the user looking at it.

tooltip stating the timezone should help with this.

**Comment by peppy** [comment]
The reasoning behind this is that it is an estimated date, therefore time zone is not so valid.

Internally this is done based on a “day” count, and does not contain a specific time value.

**Comment by cl8n** [comment]
the display can also feel odd because maps 2nd and onwards in the queue will always show as ranking tomorrow or later, so maps getting ranked in an hour could show a full day remaining and that's a pretty large error. I don't think this is worth "fixing" though because ranking time of day is supposed to be random

**Comment by nanaya** [comment]
I don't think we'll show more precise time here (if there's such thing).
