### ISSUE TITLE
Animate forum header background

### ISSUE THREAD

**Issue by DarkStoorM** [ppy/osu-web#3947]
Not really needed, but some elements like forum headers (or maybe other elements of the osu! web) could use background-position animation (requires seamless backgrounds)

![animation](https://user-images.githubusercontent.com/7021295/49609126-e827c380-f99a-11e8-9563-a31e1c9ec64b.gif)

Reference: https://jsfiddle.net/DarkStoorM/gqzsw7m2/

**Comment by DarkStoorM** [comment]
OK, so currently we have 4 forum headers, and from what I have seen, CPU usage just for animating one element is at 2.3% / 3%, and 5%~ for four elements on idle (doubled for 144Hz) - according to Chrome performance meter.

I'm not able to test GPU usage, so I think we can close this issue if 5% CPU usage it too much. No idea how to test it on mobiles either.

**Comment by peppy** [comment]
CPU% is not a good measure because your multiplier/clock speed is going to be changing as it leaves 0%. try chcecking watt usage of cpu and gpu combined. We found it took CPUS from an idle state (~2W) to pretty active (~10W) on intel integrated. This is enough to drain a battery very quickly, just for a little animation.

**Comment by notbakaneko** [comment]
Any kind of continuous idle animation on the site should be considered a non-starter imo

**Comment by peppy** [comment]
nah
