### ISSUE TITLE
3 year beatmap nomination badge tooltip is wrong

### ISSUE THREAD

**Issue by Endaris** [ppy/osu-web#4049]
![grafik](https://user-images.githubusercontent.com/22120694/50549610-129a3300-0c60-11e9-9739-b5dfe4fb10fa.png)
as found on https://osu.ppy.sh/users/1561995 etc.

This might not be an actual osu!web issue as it persists on the old site as well but I have no idea wherelse I should open this issue.

**Comment by dorothy3242** [comment]
seems to be a per-profile issue with these BN/QAT badges, because Mao's 4 year QAT badge says 3 years
https://osu.ppy.sh/users/2204515
![image](https://user-images.githubusercontent.com/33286824/50549927-f7b1c980-0c33-11e9-93f4-0d6ccd9e0add.png)

but p3n's 4 year badge says 4 years
https://osu.ppy.sh/users/123703
![image](https://user-images.githubusercontent.com/33286824/50549933-39427480-0c34-11e9-9270-34b3f6214171.png)

**Comment by peppy** [comment]
I've fixed four errors in tooltips on these badges.
