### ISSUE TITLE
Languages should not be represented as flags

### ISSUE THREAD

**Issue by Joehuu** [ppy/osu-web#4228]
This site gives a detailed explanation:
http://www.flagsarenotlanguages.com/blog/

**Comment by peppy** [comment]
They provide a good visual aid for both the current setting and the place to click to change the language. I'd see removing this as a *decrease* in usability.

**Comment by cl8n** [comment]
seems like sort of a nit-pick because for the most part the flags are a nice icon to quickly identify language, and as far as I can tell osu! is doing a good job of using flags to identify the right regional variant of language (English is British English, Spanish is *not* Latin American Spanish, China/Taiwan flags are used for simplified/traditional, ...). the region also isn't particularly important for osu!, it's just a visual aid like peppy says

the only alternative I can think to show the current locale without clicking is to just write the language but... ![](https://up.clayton.cc/0d2268.png)
idk this looks kinda silly to me to show at the top of every page. maybe I'm just not used to it

**Comment by Joehuu** [comment]
We can show the language code instead (`pt-BR`) as languages have different string lengths.

**Comment by cl8n** [comment]
having to understand a set of language codes seems far less intuitive than just looking at a flag where the language is commonly spoken... are any of the osu! locales being misrepresented in some way by the flag?

**Comment by Joehuu** [comment]
The button displays the language code while the dropdown menu has code + full language name (or even just full language name). There is nothing here to remember/understand, same with flags. I think it's just the familiarity of a person's country and it's flag.

I get that people probably know the commonly known language in their country, thus having the same flag represented as the country and *language*, but that doesn't apply to knowing multiple languages, living in a country that doesn't have an official language, moving countries, etc.

Or just google the definition of a flag.

**Comment by Joehuu** [comment]
Crowdin also represents languages as flags. I'm either way if this was one of the reasons of keeping it as is.

**Comment by Poyo-SSB** [comment]
> are any of the osu! locales being misrepresented in some way by the flag?

Let's take a look at some of the largest /problems that osu!'s current flag system has with regards to the distinction between sovereign states and languages.

**English (UK flag):**
- The [Anglosphere](https://en.wikipedia.org/wiki/Anglosphere) comprises, generally, the "inner circle" of anglophone nations. While English developed primarily on the British Isles, of course, the flag neglects the fact that the the United Kingdom represents about 16.6% of the English-speaking world. In fact, even ignoring that the United States actually makes up 64% of the English-speaking world, around 20% come from places outside both the USA and UK. This includes countries such as Canada, Australia, South Africa, Ireland, and New Zealand. [Wikipedia](https://en.wikipedia.org/wiki/English-speaking_world#Majority_English-speaking_countries) lists 27 other nations and territories whose primary natively-spoken language is English.
- The UK per se has several natively-spoken non-English languages, including Scots, Welsh, Ulster Scots, Scottish Gaelic, and Irish.

**Spanish (Spanish flag):**
- Spain as a country contains only the third largest Spanish-speaking population, after Mexico and Colombia. That's not to mention around two dozen other countries with significant Spanish-speaking populations.
- Spanish as we know it (i.e. Castilian Spanish) is actually one of at least four languages spoken in Spain, the most significant of which is [Catalan](https://en.wikipedia.org/wiki/Catalan_language). This one is particularly fun because it's not one that can easily be ignored as being a minority language in rural areas of the country, as is sometimes the case with minority languages elsewhere—Barcelona is the second most populous city of Spain and serves as the capital of the semi-autonomous region of Catalonia.

**French, Dutch, Portugese, etc.:**
- There's very obviously a pattern here—there are a *lot* of languages whose native countries (a) have multiple other significant languages and (b) have large populations of native speakers elsewhere.

**Literally everywhere:**
- Political borders are clear-cut. Linguistic borders are extremely fuzzy. It's tempting to mentally partition countries by their languages but there is a lot of bleeding over borders and pockets and other intricacies absolutely everywhere. The borders of countries in regions like Fennoscandia, Central and Eastern Europe, and Northeastern Asia become very difficult to recognise when maps are drawn by linguistic makeup rather than political division.

This really doesn't need to be a problem, there are a plethora of different solutions that don't at all require compromising the cleanliness of the current design without adding locale text:

- The language code - I'm not so fond of this, but it's certainly a better option than using flags.
- An icon - Icons like the globe and speech bubble can, unfortunately, be rather vague. Here's a fun alternative: [the language icon](http://www.languageicon.org/).
- A single flag - Display one single flag as the dropdown button for the language selector but show no flags for the languages themselves. The flag indicates the availability of different options without inexorably tying languages to countries. A frequent choice for this is the UK flag or a UN-like flag. I think that it might be fun to include the flag of the user's current country via IP.
- A selection in the footer of a page - Maybe impractical for osu!, with long and/or infinite-scrolling pages, but it is consistently effective.
- The language name - It certainly can look strange at first, especially given clayton's example above, but this is far and away more effective than any other option in practice save the footer selection. There are instances where this can be confusing—say, if the [entire page is in a completely foreign script](https://addons.mozilla.org/zh-CN/firefox/)—but this can be remedied by compounding it with an icon.

From a [Flags are not languages](http://www.flagsarenotlanguages.com/blog/case-study-onefinestay-com-and-dropdown-language-selection/) case study:

>So in conclusion, if you’re planning on implementing a dropdown language switcher, consider the following:
>
> - always supplement your dropdown with links in the footer
> - use a globe or similar icon to communicate translations to the user along with language labels
> - flags don’t appear to aid nor hinder users compared to using icons/common UI patterns, but by using them [you’ll probably find yourself stumbling into several problems outlined elsewhere on this blog](http://www.flagsarenotlanguages.com/blog/why-flags-do-not-represent-language/).

osu! seems to have a more multicultural and diverse playerbase than any other game I've ever seen, and it stands to reason that their languages should be respected. It's easy for speakers of majority European languages to take for granted our status as the "default" in so many circumstances, but it's *very* easy to alienate others.

**Comment by peppy** [comment]
everyone i've asked so far prefers flags, for the record. including all the team members that have had an opinion on this. we get that there are political issues and some discrepancies, but as a visual aid it helps in 99% of cases.

**Comment by Poyo-SSB** [comment]
Of course—it is a matter of opinion in the end, but just keep in mind that a vast majority of the team members are from countries that have the "default" privilege in most cases. 😉

**Comment by nanaya** [comment]
Seems fine so far.
