### ISSUE TITLE
Ability to expand images when clicking in the osu! wiki

### ISSUE THREAD

**Issue by Joehuu** [ppy/osu-web#4257]
Images right now are limited by the width of the wiki. This means images are downscaled visually and the ASC says "to save space, actual downsize them". There are still images that are over that (tournament brackets). It makes them less in quality.

It is also a ux thing, since there are also image slideshows in beatmap pages, forums, contests, etc.

**Comment by TicClick** [comment]
this would be awesome. now¹ that infoboxes are supported after #7546, this is about the only thing that stops us from using them on a larger scale:

- example of a page with infobox, similar to that of Wikipedia; the image cannot be expanded for a closer look without making it an unnecessary link to itself: https://osu.ppy.sh/wiki/en/Modding/Nuke

--

¹ since a few months ago, but that's still "now"

**Comment by peppy** [comment]
I'm not sure what this is asking for. By slideshow do you mean the ability to view images at a larger resolution when clicking?

**Comment by Joehuu** [comment]
Yes (indirectly). I said slideshow as upon clicking an image in some content (e.g. beatmap description, forum post, contest entries), it shows a slideshow. Will rename.

**Comment by peppy** [comment]
I think this is probably quite an easy one to implement (using the existing display we have for the contest system) so I'm going to bump it up in priority. Seems like a good usability improvement.

**Comment by nanaya** [comment]
Well, except the gallery thing involves fetching image sizes and for page which uses icons (or flags etc), they'll either need some kind of tagging or otherwise they'll be part of the slideshow

**Comment by gagahpangeran** [comment]
Only use the images with class name `osu-md__figure-image` for the slideshow? Is it okay?
