### ISSUE TITLE
Have Beatmap Disqualifications require two Nominators

### ISSUE THREAD

**Issue by Loctav** [ppy/osu-web#4404]
As we learned recently, the Beatmap Nominators that want to disqualify somthing are currently required to post a Problem in beatmap discussions and have them re-evaluated by a second Beatmap Nominator to reconfirm this desired disqualification to be valid. In order to achieve that, they currently just post the problem and then link this problem to a collection thread where they "report" the beatmap to have possible critical problems and ask for a third party Beatmap Nominator to come by and recheck the allegations.

I propose to implement a proper implementation of this:

* In order to disqualify a map, two individual Beatmap Nominators have to press the "Disqualify" button seperately. This can work in comparable fashion to "Nominating" a beatmap, just with the reverse effect. This assures that nobody can go rogue and disqualify things in rapid succession and that every Disqualification is backed up by at least a second Beatmap Nominator.

Refer to https://github.com/ppy/osu-web/issues/4405

I made a separate issue to make it possible to post a Problem without necessarily disqualifying a beatmap, so it is possible to document the potential problem and have some other Beatmap Nominator to agree with it first formally within the vicinity of the beatmap discussion page itself before they move on to disqualify it.

**Comment by Ephemeralis** [comment]
If this is added, it should also include an implementation that allows the owner of a beatmapset to disqualify their own map when it is in qualification phase, or automatically upon submission of an update.

This is commonly done at the moment via a request to a BN, as qualified maps cannot be updated any further. Mappers use this when they identify further issues based on their own review or community feedback to apply important changes.

**Comment by Naxesss** [comment]
fwiw the rules as they are currently (may be subject to change) does not necessarily require that the user reporting the beatmapset is a nominator.

An alternative solution to this problem is implementing https://github.com/ppy/osu-web/issues/4042 which we can then use to automatically bring problems posted on qualified maps to the attention of nominators so that necessary action can be taken; this way bringing the community closer to the process of checking qualified maps, without first needing to know about the report thread and post in multiple places for it to be found by anyone able to disqualify.

**Comment by RushFTK** [comment]
![a simulation about this function](https://user-images.githubusercontent.com/20500319/58367563-64936c00-7f13-11e9-83b7-5f977d561531.png)  
_one example about this features, by edit html using exist sources_

nowadays lots of mappers confused about "why this BN leave message told me my map have unrankable issues but just leave it as it was? is he carefully about his job?" ok, you can blame these mapper not read news carefully , but uncleared display may surely cause someone **misunderstanding**.  

currently dq information shows like _Disqualified X days ago by XXX with new problem #XXXXXX_ let people confused "it's dqed by one BN not two". so add this information can clearly let people know what  this map exactly statues and , surely dqed by two BNs. (or a BN + mapper request)  

 btw i dont think its a good idea to let mapper upload updates on qualified map and auto dq its. that cause only a mapper can dq their own map and not suit for current rules. it also may cause some potential problem such as :"i dqed my own map because of misoperation". which is just waste of everyone's time.

**Comment by VenixOSU** [comment]
@RushFTK I don't think mapper who can rank a map would be confused with this, it's just how the system works and I think everyone who knows how the ranking system works (what is most likely required to rank a beatmap) is aware of that, to me, only confusing thing is that BNs have to post problems as suggestions (https://github.com/ppy/osu-web/issues/4405), everything would be clear if that gets fixed I believe

**Comment by RushFTK** [comment]
@VenixOSU yes, the mapset host self may not confused about that, this changes more good for other player who can catch process clearly.

**Comment by VenixOSU** [comment]
@RushFTK It's pretty easy to understand without any complicated systems I believe.

**Comment by RushFTK** [comment]
@VenixOSU its same easy to understand on Nomination process but the bar is still on here.

**Comment by celerih** [comment]
Main issue i have with this is that while yes two people are required to DQ a map (1 reports, other confirms and DQs) that first person reporting **does not need to be a BN**. The first post doesn't really mention this even though it's kind of important, and as I see it having this thing go through kinda pushes this idea even more and alienates non BNs checking for issues in qualified maps. Additionally there's a lot of situations that only require one nominator, such as requested DQs, vetoes and ignored valid concerns. Now you'd get the issues of 2 people being required in a lot of cases where rules are explicit about only one nominator being needed.

A possible solution would be the implementation of https://github.com/ppy/osu-web/issues/4536 which already sheds a lot of light on the process of disqualifications making it clear that it works on a report/confirm basis and giving more chances for regular users to report and help in qualified, as right now that thread is kinda hard to find.
