### ISSUE TITLE
Blocking a user should hide their content from search results

### ISSUE THREAD

**Issue by peppy** [ppy/osu-web#4563]
Forum posts, beatmaps etc. should probably be hidden for blocked users. I believe this is already the case for forum posts, but not beatmaps.

As discussed IRL, search queries already have blacklist support so this may not be a huge feat in implement.

(this was a user request)

**Comment by LiquidPL** [comment]
I checked on the live website and I can't seem to be able to make this work for forum posts, and I can't find any reference to the blacklist support in the code.

Also should this just straight out exclude the content from results on elastic level, or should it show something like 'x results are hidden because the user that created them is blocked'?

**Comment by notbakaneko** [comment]
Blacklisting will be handled at the query level

**Comment by notbakaneko** [comment]
Turns out that since the beatmap listing is cached, we can't just remove users from the result
