### ISSUE TITLE
Add report button to forum posts

### ISSUE THREAD

**Issue by TobiasLeander** [ppy/osu-web#4597]
Would be useful to have a report button option for forum posts to either report really old bumps or just a keyboard spam message or something offensive.
Example:
![report button 2_000000](https://user-images.githubusercontent.com/26700331/60096138-7eadad80-9750-11e9-8765-f6b02eaf520d.png)
![report extra spicy_000001](https://user-images.githubusercontent.com/26700331/60096153-85d4bb80-9750-11e9-92c3-f3d8cbef6292.png)

**Comment by Ephemeralis** [comment]
This should be lifted to critical priority. External servers are being set up to manage forum reports because of how arcane the process to do so is otherwise, which is all levels of crazy.

Highlighted especially in https://github.com/ppy/osu-wiki/pull/4482 - see the Reporting Abuse section where a user has to navigate three different pages then contact a GMT directly via chat in order to do so.

**Comment by peppy** [comment]
Should follow the same report channels available for comments etc.
