### ISSUE TITLE
Send notifications to all QAT when an issue is reported on a qualified beatmap

### ISSUE THREAD

**Issue by peppy** [ppy/osu-web#4784]
Right now a forum thread is being used, which is all sorts of backwards.

This should address the issues raised in #4536.

**Comment by ascendancelol** [comment]
Can this be sorted by mode? As in, could I only receive notifications for reports of my mode (catch) and not all modes? Seems much better than the report thread either way if it goes right to my notifs.

**Comment by dorothy3242** [comment]
Reposting thoughts from the other issue plus some other stuff

there needs to be something that
- makes reported maps visible in one place
- ^ ideally alongside a summary of the problem that the reporter would submit
- keeps it intuitive to report maps for issues (easy to know the option exists)
- Should be able to alert **BNs and NATs alike** (QAT doesn't exist)
- Would automatically clear the reports for disqualified maps.

There should also be some way for BN/NAT to clearly mark if they feel a report is invalid. It doesn't need to remove the report, but it would make it clear a report has already been looked at so others can focus on other unchecked issues.

I think something like github reviews could work quite well. You "start a report", post multiple issues as part of it, and it shows up as one thing with a summary for others to easily look at.

**Comment by TheMoMan** [comment]
Some functional requirements
- Notifications must be sent when a new issue has been reported.
- Notifications should be seperated by gamemode, so that relevant members can react to beatmaps of the appropriate mode.
- NAT must receive notifications from at least one gamemode.
- BN must have the ability to opt into receiving notifications for any gamemode.
- There should be an API for updates to this system (let discord bots repost updates etc)

**Comment by Naxesss** [comment]
If reports are only made when people post a problem stamp, https://github.com/ppy/osu-web/issues/4405 is a prerequisite so that nominators can report beatmaps like anyone else when they're unsure of something and not have it be disqualified.

For the last point Mo mentioned, see https://github.com/ppy/osu-web/issues/4042.

Context:
We currently use a webhook to highlight any NAT or BN that opts-in when a beatmapset of their mode is posted in the report thread. When a beatmapset is disqualified or ranked, we remove the entry so that anyone looking at the channel can see what's relevant. Allowing this to track problems (and possibly suggestions) means we could adapt this accordingly. This information (who did the report, what map it was on, etc) is also added to a database and is something we use to judge Beatmap Nominator activity.

![](https://i.imgur.com/qllpBrH.png)

**Comment by notbakaneko** [comment]
Is this page useful to BNs/NATs in any manner: https://osu.ppy.sh/beatmapsets/beatmap-discussions ?

**Comment by Naxesss** [comment]
With this I should be able to fulfill all the requirements -Mo- mentioned above, along with other applications we've been unable to do before this. So yes, it'll be very useful once we start adapting it.
(need to finish some exams first, though)

This also partly resolves https://github.com/ppy/osu-web/issues/4042, just missing a similar page for replies and votes now to fully incorporate everything.

**Comment by dorothy3242** [comment]
errrr
even if that's the first step, sending notifications for every problem post on every qualified beatmap to the **~100** members of the entire BN and NAT is pretty hefty.

Also NAT and full BNs can't even post problems on maps without disqualifying them. Meaning we'd be locked out of "reporting" maps in such a system.

What's the overall plan here?

**Comment by peppy** [comment]
Reporting problems as a BN/NAT is intended to disqualify. This is *part of the process*.

**Comment by peppy** [comment]
This should also trigger on disqualify, I believe.

**Comment by dorothy3242** [comment]
General beatmap related actions that are sent as notifications to NAT/BN members should also be clearly distinguished from regular modding notifications they get.

It feels visually mixed together with their own beatmap watches as of right now, which can make the notifications for qualified beatmaps feel less important.

**Comment by notbakaneko** [comment]
#5174 #5101
