### ISSUE TITLE
New content font is too decorative and hard to read

### ISSUE THREAD

**Issue by celerih** [ppy/osu-web#4868]
Took a quick screen but this new font is so out of place compared to the rest of the page with the generally more rounded fonts used.

![image](https://user-images.githubusercontent.com/37513517/63957493-7dea0e00-ca56-11e9-87be-2de337fbf9a3.png)

Not exactly sure why the older font was changed considering how it was consistent with the rest of the page and what was used there, but now it clashes heavily with the generally rounded stuff used in headers and prety much everywhere else

**Comment by Mirruuu** [comment]
Agree with this, it looks kinda blurry too so its actually harder to read for me than the previous font which also fit a lot more with the headers and such.

**Comment by yaspo** [comment]
Problems I personally find in the new font are
- color is pure white, this makes the contrast with the otherwise dark theme rather extreme
- letters (and especially spaces) are spaced further apart than before, making it hard to adjust (blurryness Mir referred to) or to simply read through (text takes up a lot more space)

So making small changes like making the colour a light grey and reducing the letter spacing helps a great dea imol, example :
![adjusted font](https://i.imgur.com/pO6Gnqp.png)
eyeballed #eee color and -0.5px letter-spacing

**Comment by peppy** [comment]
Could you please provide comparisons vs the old font to try and help us figure what you mean by "blurry"?

**Comment by arflyte** [comment]
The new content font Inter was meant for the newer parts of the web where Torus is used. Inter was designed with legibility in mind at any size and it's far from anything 'decorative'.

For the rest of the web that's still on Exo, best to revert it back to Open Sans for now.

**Comment by notbakaneko** [comment]
what browser/OS/userstyle/zoom level/cleartype/anti-aliasing settings are you using?

**Comment by Mirruuu** [comment]
I don't really have a direct comparison shot since the old font is gone but I believe these two are different fonts?
![image](https://user-images.githubusercontent.com/25852637/64001731-c06c2300-cb08-11e9-9b9b-c32d0603c79a.png) 
![image](https://user-images.githubusercontent.com/25852637/64001745-c8c45e00-cb08-11e9-8fea-d2c06efd988e.png)

Just comparing things like the t's and the e's there's slight blurs on the top of the t and the hole of the e and so on, where there's close lines together on the new font. On the old font there isn't as much blur.

I don't have great eyesight so I preferred the previous font for that reason mostly.

**Comment by peppy** [comment]
Until the other half of the new font is ready, we have rolled back this change.
