### ISSUE TITLE
Chat doesn't scroll to last unread (or bottom) on load

### ISSUE THREAD

**Issue by peppy** [ppy/osu-web#4897]
On load or switching chat channel, the scroll position is always the top. Should be bottom (or last unread).

**Comment by LiquidPL** [comment]
will do this one if possible

**Comment by LiquidPL** [comment]
I looked into the code for this, and it seems a bit confusing for me:

* first of all, there's [this](https://github.com/ppy/osu-web/blob/master/resources/assets/lib/chat/chat-orchestrator.ts#L69) bit of code, which just seems to disable autoscroll for pretty much any channel change. I'm guessing that this is the reason for why it's not working as intended, and I'm asking as I don't want to just remove it without knowing what it does exactly.
* second, the autoscroll flag is stored globally for the whole UI state, while it makes more sense for me to store it per each channel, so that each channel would remember if it was scrolled to the end or not.

**Comment by peppy** [comment]
I believe @nekodex can probably shed some light on the reasoning for having it disabled (or you could try switching it on and see what hell breaks loose).

**Comment by nekodex** [comment]
That referenced line disables autoscroll when changing channels unless the target channel is a 'new conversation'. That was intended behaviour.... this issue is not a bug fix, but a behavioural change.

The final behaviour was intended to be: scroll to the first _unread message_ in a channel when changing to it. The problem is that in public channels with high activity, this is kind of useless (to make it worse, the unread message may have been culled from the client backlog already in some cases...). So in that scenario, we want to instead default to scrolling to the last message.

I'd also be careful with storing autoscroll per-channel... consider the case where you're switching back to a PM with a bunch of unread messages - you want to be scrolled to the first _unread message_ position, not for autoscroll to kick in and throw you at the end of the entire conversation.
