### ISSUE TITLE
Modding Discussions feel impersonal to use

### ISSUE THREAD

**Issue by TheMoMan** [ppy/osu-web#4902]
This is an issue brought up by discussions in https://github.com/ppy/osu-wiki/pull/2337 and [this Twitter post](https://twitter.com/u896613/status/1152348318665781250). 

Basically, comapred to forum posts, the stricter format of modding discussions currently makes the process feel impersonal and more like a chore. Given that most mappers and modders, especially BNs, entirely on a voluntary basis, this impersonal environment isn't really suitable and is demotivating to some members of the community.

With forum posts, modders were able to format their mod posts in countless ways, as well as write short intros and outros to their posts. While something similar can be achieved with praises in modding discussions, modders aren't really using them currently because of how every post creates a seperate thread. Writing "good luck" or some other sign off at the end of a forum post was general etiquette, but this hasn't carried over to praises as they tend to get buried and people feel like they're posting bloat (unless it's a hype).

As discussed in https://github.com/ppy/osu-wiki/pull/2337, some members have resorted to writing jokes in the disqualification post, which some people deem to be inappropriate.

Modding discussions should ideally encourage a more friendly and personal atmosphere without compromising on how we use these tools efficiently. While modding discussions format problems in a much more efficient manner, it is a lot less enjoyable to interact with the community through it.

**Comment by peppy** [comment]
We are already working on these mentioned issues, but progress is very slow. Suggestions are welcome in the mean time.

**Comment by Kibbleru** [comment]
Can we bring paging back first?
It's a crucial part of making the posts system viable as it was an effective way to prevent clutter. The current system does not work for this, not to mention the amount of resources it takes, it makes scrolling through the content way harder.

**Comment by Naxesss** [comment]
Currently it's kinda difficult to navigate to where activity happens on a mapset when you're not the mapper since there's usually ~9 different places you need to look (4-ish diffs with 2 tabs each + general (all diffs)).  Although you can see all activity in chronological order through the events tab, it requires actually going into each link since it often brings you into a completely different place every time.

If posts followed a structure something along the lines of this (made some rough changes to the current design), and there was just one tab that could be sorted by post date, things would be much easier to follow (posts wouldn't swap order while you're not looking and new posts could be found easily) while still allowing for beatmap filtering and so on (issues would be associated with a difficulty and receive their own replies and stuff as it is now). On top of this, it'd allow for intros and outros and generally keep things more personal and in one place for each modder, as it was in modding v1.

![](https://i.imgur.com/Z39S2WF.png)

Making a post in this could be done by preparing all of the suggestions, problems, etc for each difficulty (including a General one which is equivalent to the current "General (All Difficulties)") and then submitting all at once. Each issue in one of these posts would be able to be resolved, replied to, deleted, edited and so on as any other post right now.

This is pretty much an overhaul of the way the current structure works, but it'd be one way to solve many of the issues that were introduced by modding discussions, including stuff being impersonal. Despite being a lot of changes, it could probably be applied retroactively, as all that changes is just the structure and how it's interacted with; not the data itself.

**Comment by cl8n** [comment]
seems like that'd undo a lot of what makes v2 so helpful though, since now (just an example) the modder would have to check through previous mods to make sure they aren't suggesting things twice etc 

some combination of this and the current moddingv2 layout could be nice imo. reminds me of how GitHub handles reviews, you can comment on specific lines of code (equivalent to timeline modding) but also write comments pertaining to your entire review before you submit it. when the owner of the PR goes to make the changes, they can choose whether they want to view suggestions chronologically or via the files changed tab

**Comment by ascendancelol** [comment]
would be nice to at least make mv2 and naxess' suggestion a toggle-able feature, if it doesn't require too much effort. i think mv2 has some positive factors (it most notably helps newer mappers from my own experience) but mo's post brings up a lot of critical points in what makes modding for more experienced people a bit more of a chore or a job.

**Comment by Kibbleru** [comment]
> some combination of this and the current moddingv2 layout could be nice imo. reminds me of how GitHub handles reviews, you can comment on specific lines of code (equivalent to timeline modding) but also write comments pertaining to your entire review before you submit it. when the owner of the PR goes to make the changes, they can choose whether they want to view suggestions chronologically or via the files changed tab

Github style would really be nice imo. Github is used to "mod" code, while osu is used to "mod" maps, they're in similar parallels.

**Comment by TheMoMan** [comment]
Here's one suggestion I made very quickly. The idea is similar to Naxess's in that modders post all of their suggestion in one post, and each suggestion can be replied to individually.

![soffice bin_2019-07-20_13-02-55](https://user-images.githubusercontent.com/6444058/64488889-f31ec580-d244-11e9-8f9a-38cd09cf5b26.jpg)
![soffice bin_2019-07-20_13-03-10](https://user-images.githubusercontent.com/6444058/64488891-f87c1000-d244-11e9-816d-9cde189850d6.jpg)

What I've also tried to include is some functionality from current modding discussions, where mappers can switch to the timeline page to see all issues for each difficulty. (and filter by unresolved). This would also make it easier for modders to see what issues have already been addressed. 

The goal overall here is to format a mod post like a forum post (modv1), and then have the website convert it into timeline posts like modding discussions (modv2). The original modv1-style post should always be accessable.

**Comment by peppy** [comment]
I just want to add that the above kind of "posting time" ui change is not a focus.  Out of curoiosity, have you tried filtering to a specific user? This alreadygives a view very similar to what you are proposing, minus the ability to add "comments" in a single view (which *is* something we are considering):

![image](https://user-images.githubusercontent.com/191335/64669411-6b32f880-d49c-11e9-91b8-e9b65aba30cd.png)

**Comment by TheMoMan** [comment]
That's similar, but I don't think it really meets all of the requirements.

- Posts are still fragmented across different difficulties, and even split between general and timeline issues.
- It doesn't show points that are being reopened where the original poster is not the one you are filtering for.
- Order/structure is still determined by the site rather than the poster, sometimes it makes sense to order points that's not by timeline or last update, and posting things as a single block encourages a more natural way of interaction. An example would be grouping all points about spacing into a single discussion (could be done as a single post in general tab but still has the fragmenting issue).

The issue I think is that modding involves posting individual threads rather than a single post, and this doesn't really encourage natural interaction on its own. Being able to view posts individually is good for efficiency, but it compromises on users getting the communal and personal feel from it. That's why I've tried to suggest a system where there's more options in how to view mod posts.

**Comment by celerih** [comment]
Something i want to add about uses for more singular posts is simply coherence within a mod.

Often when modding some general ideas carry from different difficulties, or after modding another difficulty you can spot recurrent issues and go back or call back to the past difficulty.

With singular posts is becomes really easy to have a certain flow and natural progression to your mod and how you approach issues, which you just can't on mv2. Calling back to other difficulties required you to constantly switch tabs, and when you spread that between 4 tabs just to reference 2 diffs (general diff + timeline) it quickly becomes a mess and it's difficult to have a good mod that has a coherent progression to it. With a singular post this becomes a ton easier to do and helps with the more personal feel of the post as opposed to a wall of disconnected issues

**Comment by peppy** [comment]
I just want to make sure you understand that "Natural flow" in your words is basically chaos in terms of organising a system where we are trying to make things easy to parse for the average user.

Going forwards, where we plan on having modding done in the editor, what you ask for here is a step backwards and makes improving the system unfeasible. Thanks for the feedback though.

**Comment by celerih** [comment]
Approaching modding as a set of individual problems to point just doesn't work well with the purpose of modding tho. Maps aren't code where you find problems like on GitHub, it's about representing music and creating a specific gameplay experience. 

Trying to approach that kind of stuff with a very disconnected modding, aka point by point, you inherently lose a ton of required nuance that is extremely important given how subjective and personal mapping has become.

Mapping plays around with a mix of game design and artistic endeavors. Being able to properly critique and help improve it is infinitely harder when you're stuck having to right every thing one at a time. Treating it like code won't be a step forward

**Comment by peppy** [comment]
This is a really weird (and in my opinion outright *wrong*) argument when all old mod posts are a series of individual problems in a list. Could you please provide examples of cases where problems can not be split up into individual points which can be resolved when fixed?
