### ISSUE TITLE
Can't rename oauth client

### ISSUE THREAD

**Issue by cl8n** [ppy/osu-web#5104]
used to be possible, but now `ClientsController` doesn't support it. the client edit menu in account settings should allow this too

**Comment by peppy** [comment]
Sounds like it may have been a conscious decision to avoid screwing with end-users.

**Comment by hallowatcher** [comment]
Hello all, I would appreciate if this became a thing again. I'm currently stuck with my OAuth application list because I've reached the limit (I'm actively creating osu related projects for tournaments/applications etc).

I knew there would be an OAuth limit implemented, so I created a bunch of OAuth clients in advance and named them "example"
![image](https://user-images.githubusercontent.com/6265839/91857176-dbb3c600-ec67-11ea-8578-20d6a1914d6e.png)

And now I'm using those OAuth clients I created back then, but they're stuck with the name "example".

Would it be possible to make name changing available to users again? Or at least increase the client limit for certain/all users? Deleting these clients to create new ones with proper names would mean I would be stuck with whatever the limit is (probably around 5), and would also break some of my production applications.

@peppy

**Comment by peppy** [comment]
you're correct in thinking the limit is 5. we'll look into increasing it for all or for specific users.

**Comment by cl8n** [comment]
> Sounds like it may have been a conscious decision to avoid screwing with end-users.

maybe I'm not creative enough but I don't see how you would do that via renaming. other websites let me rename oauth clients so I figured this is ok

**Comment by peppy** [comment]
I think we can allow editing.

**Comment by hallowatcher** [comment]
Hello all, I assume this was seemingly forgotten and buried within the many other issues.

I have released yet another project, https://choice.hwc.hr, and some users are complaining because of the OAuth app name:
![image](https://user-images.githubusercontent.com/6265839/147254669-8d598aac-e1a3-4b69-94ab-b6336d70216f.png)

@peppy should I just look into PRing this myself (app renaming) or is this still in the pipeline (after 1.5 years)?

**Comment by peppy** [comment]
You're welcome to attempt it

**Comment by notbakaneko** [comment]
Renaming a client should revoke all the existing tokens for the client.

**Comment by nanaya** [comment]
Can we just increase the client limit? Something like 20 maybe. I can't remember the reason for enforcing low limit for this.

**Comment by peppy** [comment]
Yeah, that does seem like the easier solution. @hallowatcher how many clients are you thinking you'd need in total?

**Comment by hallowatcher** [comment]
20 sounds like a good number that would be enough for everyone.

I'm not using more than 10 atm, but I can see myself going above that (for example, when freelancing for other projects like COE or tournaments)

**Comment by peppy** [comment]
I'll increase the limit to 15 for now.

As an aside, if anyone finds this issue in the future looking to rename their oauth client, feel free to email me with ample identification and I'll do it for you (pe@ppy.sh).

**Comment by peppy** [comment]
I've made this change.
