### ISSUE TITLE
Fix textwrapping for tables on mobile

### ISSUE THREAD

**Issue by Pennek** [ppy/osu-web#5671]
Currently textwrapping on mobile makes text look weird, and whitespace messes everything up. This makes reading tables very frustrating

[Image 1](https://cdn.discordapp.com/attachments/410314356455243789/681136095878184985/unknown.png) 
[Image 2](https://cdn.discordapp.com/attachments/218677502141399041/681135207742570554/Screenshot_2020-02-23-14-47-11.png)

**Comment by notbakaneko** [comment]
It turns out that it isn't practical to do apply any kind of wrapping to tables without known of the form of content beforehand; e.g. preventing `t h i s t h i n g` from wrapping just causes the table layout to mess up for other columns. Other kinds of wrapping lead to other new problems, like unaligned columns, other text not wrapping when they should, etc.

The best solution for this outside of piles of javascript to re-render the table or somehow adding styling hints to the markdown, appears to be css subgrids, except they're currently only supported by Firefox

**Comment by peppy** [comment]
Closing for now, then.
