### ISSUE TITLE
Hide legacy PM counter when zero

### ISSUE THREAD

**Issue by peppy** [ppy/osu-web#5754]
We don't want people ending up on the old site for just idly clicking this button. It shouldn't need to display if the count is zero.

![image](https://user-images.githubusercontent.com/191335/76445842-6a5a2f80-6409-11ea-85c3-01de532c1708.png)

**Comment by Xinnoh** [comment]
idk how to bring this up, but in general from most conversations i've read the general consensus has been "wtf why"

There's no easy way to read messages that have been opened in the past which is a common thing to do. Legacy PM is still important for:
Sendng messages to multiple people (tournaments, contests)
Not being deleted after a month (why is that still a thing)
Knowing whether the receiver read the message

Until the first two issues are fixed, legacy needs to be accessible.
(If this is still a hard no I would have suggest reverting + just changing the link to be the new community chat since going to community -> chat isn't as clear)

**Comment by peppy** [comment]
Please make a bookmark.
