### ISSUE TITLE
Incorrect site width on full hd+ screens (mobile)

### ISSUE THREAD

**Issue by Moltanicaa** [ppy/osu-web#5819]
On my Honor 8x smartphone, the screen resolution is 2340x1080, which is why the site is displayed wider than the actual screen resolution
![Screenshot_20200325_145123_com android chrome](https://user-images.githubusercontent.com/59089206/77503361-21928400-6ea9-11ea-9e94-50d0eadc13a2.jpg)
![Screenshot_20200325_145119_com android chrome](https://user-images.githubusercontent.com/59089206/77503364-23f4de00-6ea9-11ea-8c9c-41760f4e2f7e.jpg)

**Comment by gagahpangeran** [comment]
It happened because of overflow link in footer. I can reproduce it when change the language to russian and german.

![image](https://user-images.githubusercontent.com/4964985/87277564-ba0e4c00-c50c-11ea-853c-2db6180aaa6b.png)

![image](https://user-images.githubusercontent.com/4964985/87277615-d7431a80-c50c-11ea-9aec-2e54a389e8bf.png)
