### ISSUE TITLE
implement PKCE for api v2 auth

### ISSUE THREAD

**Issue by tybug** [ppy/osu-web#5879]
I have a desktop application which I'd like to migrate from v1 to v2 at some point, but I can't embed the client secret in the application for security reasons. [PKCE](https://oauth.net/2/pkce/) would be helpful (necessary, even?) for me.

**Comment by peppy** [comment]
Our API does not (and can not) support this flow. That is not an intended purpose of it. Please create a server-side component for your application which provides caching and user authentication for your application.

**Comment by tybug** [comment]
I may have jumped the gun a bit here - I assumed v1 would be removed entirely in favor of v2 in the future. If this is not the case, this issue was unnecessary. 

But if you do plan to remove v1 in the future, what does that mean for desktop applications (among others)? Will they not be supported unless they have a website component? Many useful applications function without any website and the associated costs thereof.

**Comment by tybug** [comment]
I may have jumped the gun a bit here - I assumed v1 would be removed entirely in favor of v2 in the future. If this is not the case, this issue was unnecessary.

But if you do plan to remove v1 in the future, what does that mean for desktop applications (among others)? Will they not be supported unless they have a website component? Many useful applications function without any website and the associated costs thereof.

**Comment by longnguyen2004** [comment]
@peppy Is there a reason why it can't be supported?

**Comment by peppy** [comment]
Our API is not meant to serve large amounts of clients. This basically makes me responsible for running the infrastructure for your application, in terms of scaling and cost.

For the time being we just don't have the team to do this. I am already at my limits managing our own services without needing extra load from third party applications.

Please spin up your own cheap server and perform and cache your API operations there, rather than having the end-user's client perform them.
