### ISSUE TITLE
Time display doesn't need to have "ago" in absolutely all cases.

### ISSUE THREAD

**Issue by ghost** [ppy/osu-web#5890]
"119 minutes ago" and "23 months ago" is not something a human normally says.
----
I see there was an update with the timeago thing but its quite weird. I suggest the following format:

Lets say its Wednesday, April 8
1~3 minutes > **Just now**
45 minutes ago
1 hour ago
12 hours ago
23 hours ago
**Yesterday**
**Tuesday**
**Monday**
**April 5**
April 4
...
**February 4**
...
January 4
...
**December 4, 2019**

Thats it, theres no need to dwell on how to display "1 month and 7 months ago" or "1 year and 3 months ago".

**Comment by nl-tatatat** [comment]
I agree with,

 1~3 minutes > Just now
45 minutes ago
1 hour ago
12 hours ago
23 hours ago
Yesterday
Tuesday
Monday

but I dont understand what you mean below that point

**Comment by Flanster** [comment]
Uh display just a month and day? No "days ago" beyond that point.

**Comment by nl-tatatat** [comment]
yes

**Comment by peppy** [comment]
Does it matter if a "human would say it"? It's there to be accurate and informative.

**Comment by Flanster** [comment]
It matters when its easier to comprehend and looks cleaner. You don't need to be accurate up to 102 minutes or 17 months. Saying 1 or 2 hours ago is informative enough. Even if my example is disregarded, the previous way of handling it would still be fine. If anything, hovering on the timestamp could also be a solution for more "accurate" results because surely everyone needs to know their map was graveyarded 1 year and 7 months ago and not 2 years.

**Comment by InvisibleSymbol** [comment]
> Saying 1 or 2 hours ago is informative enough.

As a note this change was made in part to address #5859, where this kind of resolution _is_ required - Tho I'm not saying that `90 minutes ago` makes more sense than `1.5 hours ago` or `1 hour and 30 minutes ago`. 

Personally I would prefer seeing a combination of 2 units over just forcing the higher resolution one. (so `90 minutes` would be `1 hour and 30 minutes` or `23 months` would be `1 year and 11 months`)

I have no opinion on switching to dates after a certain amount of time because I don't really care, either way works for me.

**Comment by nanaya** [comment]
Probably fine as is.
