### ISSUE TITLE
Arrow on top right of comments should also collapse top level comment

### ISSUE THREAD

**Issue by Joehuu** [ppy/osu-web#5948]
Or you have long comments that can't be hidden. I'm proposing reddit behavior.

![JNAPTBfeN1](https://user-images.githubusercontent.com/35318437/80241421-6d575b00-8618-11ea-86c5-6a8af955630d.gif)

![hbowpdG4Ic](https://user-images.githubusercontent.com/35318437/80241503-8bbd5680-8618-11ea-830c-44a7a09b7e04.gif)

**Comment by arflyte** [comment]
oh, didn't expect one would write a thesis in the comments. hmm, I think we can do a similar bar like reddit under the chevron, but only for the top.

**Comment by peppy** [comment]
I really think comments should have a "view more" when they are more than x lines. This kind of comment spam should definitely not be encouraged.

**Comment by arflyte** [comment]
aite. i'll look into the expandy button.

**Comment by arflyte** [comment]
![Figma_200507-151949](https://user-images.githubusercontent.com/3632750/81261054-46684280-9076-11ea-945b-f9a0a1da0d23.png)

Only show the first 7 lines, and fade the last 2 lines to 50% and 25%, followed with 'Read More' text link. Text link because putting another button there made it look busy.

Can make the lines shorter, if 7 is a lil bit too much.
