### ISSUE TITLE
Can't find my beatmaps through the search

### ISSUE THREAD

**Issue by N0Glory** [ppy/osu-web#5956]
I just type title of the song, for example ("Monster in Me Mors Principium Est") and find a lot of maps but not one with the same title... should this work like that? this map  (https://osu.ppy.sh/beatmapsets/1154588#osu/2409650) and this my GET request (https://osu.ppy.sh/beatmapsets?s=any&q=Monster%20in%20Me%20Mors%20Principium%20Est)

**Comment by peppy** [comment]
This would be improved with exact match weighting (something we used to have on the old site).

See:
https://osu.ppy.sh/beatmapsets?s=any&q=Mors%20Principium%20Est
vs
https://osu.ppy.sh/beatmapsets?s=any&q=%22Mors%20Principium%20Est%22

@notbakaneko can you have a look at why searching [just "mors"](https://osu.ppy.sh/beatmapsets?s=any&q=mors) gives very poor visibility of word matches? i think prefix matching needs to be outweighted by exact

**Comment by notbakaneko** [comment]
original issue was fixed in #5962.
Exact matches already outweigh partial and prefix matches just by the nature of how fields scores are but there are other factors that affect how full-word and prefix matching gets scored across all terms.

Prefix matching is largely there for suggestions, so it's probably better to have auto-complete suggestions separate and remove it from the final results.
