### ISSUE TITLE
Add score date to the beatmap leaderboard

### ISSUE THREAD

**Issue by stanriders** [ppy/osu-web#6207]
![image](https://user-images.githubusercontent.com/8269193/85063301-9cbabc00-b1b2-11ea-95de-92eb03cc668b.png)
Just like osuplus does it

**Comment by AqilCont** [comment]
In my opinion, I think it should be provided in a different way, like maybe on hover. The current implementation takes up the most space on the map rankings and makes everything considerably more squished.

**Comment by peppy** [comment]
@arflyte has this been considered in the newer design? definitely something we want to show somehow.

**Comment by arflyte** [comment]
Oh. I don't think I have this. I'll add it.

**Comment by arflyte** [comment]
![Figma_200624-031109](https://user-images.githubusercontent.com/3632750/85439840-6624dd00-b5c8-11ea-8824-211c98b4bf1c.png)

Condensed 300/100/50/Miss to make space for the Time column. Relative dates are shown in short form, actual dates shown on hover. Anything lower than 1 hour shown as "<1h".

**Comment by AqilCont** [comment]
I think we would benefit from just removing the smaller time signatures completely, and make the remaining ones more definite, like, just have `2yrs` instead of `2y 4m`.
Also, I don't think we need to shorten anything below an hour if we just follow the rules above, like maybe `38min` or `28sec`. I think this is definitely more readable by the average user, and hover shows the full date anyways.

**Comment by arflyte** [comment]
Yeah, that works too.

**Comment by mcendu** [comment]
The mania ruleset uses 6 columns for judgements (MAX, 300, 200, 100, 50, MISS). I am not sure how would the design scale to that.
