### ISSUE TITLE
Get thread notifs in the forum

### ISSUE THREAD

**Issue by Lyawi** [ppy/osu-web#6214]
what's the point of having a notification system if we don't get notifs when someone commented your thread? Same thing when you comment a thread from someone, you usually wanna continue to follow it.

If someone doesn't want to follow anymore, they could turn off by a button?

If this gets applied we shouldn't get e-mails about it, except if it's the help or skinning forum imo.

**Comment by Helen0903** [comment]
Not quite sure what this is about because afaik this exists already on forum threads
![SmartSelect_20200620-201106_Chrome](https://user-images.githubusercontent.com/12070265/85209746-496f7780-b332-11ea-9642-6ede0f00b3de.jpg)
(See bottom left, I'm subscribed with emails)

![SmartSelect_20200620-200904_Gmail](https://user-images.githubusercontent.com/12070265/85209751-54c2a300-b332-11ea-8d71-a88afff0c705.jpg)

**Comment by Lyawi** [comment]
there should be coming a forum notification though. 
https://i.imgur.com/pNAa2a0.png this

**Comment by dorothy3242** [comment]
That's already a feature by bookmarking a thread with notification. What type of notification you get (email, website, or both) can be customized in your user settings.

![image](https://user-images.githubusercontent.com/33286824/85211626-ed4c2980-b318-11ea-8aca-edaeb8dc3e5a.png)

**Comment by peppy** [comment]
Closing as already available.
