### ISSUE TITLE
After favouriting beatmapset with 0 favourites, favourites starts showing nothing

### ISSUE THREAD

**Issue by lmnyx** [ppy/osu-web#6250]
![a](https://user-images.githubusercontent.com/13962537/86121339-496c3600-baef-11ea-88eb-52dff33ae15f.png)
Should not make it hover-able or update the favorites after favouriting.

**Comment by gagahpangeran** [comment]
So this happened because after click the favourite button, `@state.favcount` and `@state.hasFavourited` are updated but `@state.beatmapset` that has `recent_favourites` is not updated.

https://github.com/ppy/osu-web/blob/448b9d64151f042c08199e098101166656a5050e/resources/assets/coffee/react/beatmapset-page/main.coffee#L158-L160

Possible solution are refetch the beatmapset data then update the `@state.beatmapset` or include the `recent_favourite` in `/beatmapsets/{beatmapset}/favourites` response then update the `@state.beatmapset.recen_favourite`. Which one is better?

**Comment by peppy** [comment]
i think it should probably be included in the response. @nanaya / @notbakaneko ?
