### ISSUE TITLE
No default redirect multiplayer url

### ISSUE THREAD

**Issue by gagahpangeran** [ppy/osu-web#6291]
Currently if I open rankings > multiplayer from top navigation, it opens page with url https://osu.ppy.sh/multiplayer/rooms/latest.

I try to open https://osu.ppy.sh/multiplayer/rooms and https://osu.ppy.sh/multiplayer that don't exist but it's not redirect to https://osu.ppy.sh/multiplayer/rooms/latest and my account is auto logout.

![Screenshot from 2020-07-10 22-54-25](https://user-images.githubusercontent.com/4964985/87174105-ece3f480-c300-11ea-8c2d-4f5b7116940a.png)

Expected behavior is like when I open https://osu.ppy.sh/rankings then redirect to https://osu.ppy.sh/rankings/osu/performance.

**Comment by peppy** [comment]
What is this even saying? I think you may be confused. The only valid URLs are the ones exposed by the site.

**Comment by Helen0903** [comment]
If I understand correctly, they're asking about implementing redirects from the shorter multiplayer room URLs to the actual one (like for rankings): https://osu.ppy.sh/multiplayer & https://osu.ppy.sh/multiplayer/rooms would redirect to https://osu.ppy.sh/multiplayer/rooms/latest.

Also I don't know if it's intentional or worth opening another issue for, but the missing page always displays the user as not logged in. However, that's only a display thing as other pages stay logged in (and cookies are not replaced).
