### ISSUE TITLE
API link redirecting to forum

### ISSUE THREAD

**Issue by rileywaffle** [ppy/osu-web#6347]
Upon clicking https://osu.ppy.sh/p/api and logging in for the first time it redirects you to the https://osu.ppy.sh/community/forums/ site. It works if you are already logged into old.ppy.sh though.

repro steps:
* open incognito window (or log out)
* log in upon prompt
* reload https://osu.ppy.sh/p/api 
* will redirect to forums (until you wait ~1 min seems to be a cache issue of some sort)

**Comment by tybug** [comment]
this is on its surface a pretty minor issue but causes many users to be confused about how to get their api key, because they've never seen the real page before and think the redirection is intentional. I've lost count of the number of times I've had to tell someone to "just keep trying until it works"

**Comment by peppy** [comment]
For me it redirects to a login screen. Is that not what you're seeing?

**Comment by rileywaffle** [comment]
> For me it redirects to a login screen. Is that not what you're seeing?

It redirects to the login screen on the first click, but after logging in it goes to the forum.

**Comment by peppy** [comment]
Not sure this will be fixed since it's non-straightforward and old web is pretty dead.

Plus this is a developer facing features which is not used by many and I'm sure those who are capable of using an API key are also capable of finding the correct page
