### ISSUE TITLE
Create an "announcement" style message in new chat system

### ISSUE THREAD

**Issue by cl8n** [ppy/osu-web#6404]
the old forum pms have been in an end-of-life stage for a while (as said in multiple issues here, and on discord), but I don't see anything tracking ideas for what could properly replace it. #5774 requests for "group chat" to be exposed, but that isn't really in the same spirit as the mail-like forum pms. #6359 asks for api access to chat to get some workaround going due to forum pms having awkward bugs sometimes (#6334), but it would be a nonissue if there were a new alternative to forum pms. I and probably anyone else trying to do important communication with osu! projects would benefit a lot from having something similar to the old forum pms, but without all of the bloat that phpbb brought along with it.

I feel like a good enough "replacement" could be closely related to chat, so these are what I see as necessary features that *aren't* available via chat already:

- multi-paragraph & formatted messages
- "to" and "bcc" fields with same function as email, specifically *not* just opening a group chat
- subject line that can be used in notifications and emails

and these are more features I use in forum pms that are nice but probably not necessary:

- read receipts
- message icons
- drafts
- basic message sorting or "folders"

**Comment by peppy** [comment]
Going to milestone this so we can finally turn off the old system.

Route forward is adjusting chat to have a special message type which gets more prominence and can be seen as "important" compared to normal chat.

**Comment by huuishuu** [comment]
Apologies for bumping, but it's been since August 2020 when the last mention on this happened, so I'd like to chime in on why this would be beneficial for stuff like Project Loved. As part of Project Loved, with the way things are - old forum PMs are just about the only way we have of mass-messaging multiple people when it comes to:
- letting them know their map is being put up for vote
- letting them know that changes are necessary (as moddingv2 doesn't automatically subscribe the mapper to make them receive notifications).

Old forum PMs are basically a necessity for us, yet it's in such a state of disrepair that it's not just buggy but it also no longer sends an on-website notification that someone has received a message, making the entire process of communicating with mappers a real drag.

Is there any update on this or anything to expect anytime soon?

**Comment by peppy** [comment]
No updates on this just yet.

If you don't mind using the API, "mass messaging" via the new chat system is already feasible.

**Comment by cl8n** [comment]
if nobody else starts on this by June or so (a guess when I'll have my other PRs + WIP stuff in good states) I'd like to try it-- for Project Loved we rly need this functionality soon, I'm sure other projects would prefer it over raw chat messages, and it also looks like a blocker for turning off the old site.

based on the renamed title of this issue I'm assuming that a priority is to integrate this with Chat as much as possible. unless there are designs already in the works I can propose the minimum features/design that would make it useful to me, already done some thinking abt this

**Comment by peppy** [comment]
We were discussing getting this done in the near future, but how it should work from a UI/UX perspective isn't set in stone. Since you're someone who has knowledge of how this system is going to be used, it may actually be beneficial for you to give it a go (starting with the front-end implementation) and see how things work. Let me know if you need any direction.

@notbakaneko since you're still making changes to the chat system, can you confirm whether the remaining refactors you're doing are near completion / overlapping with implementing something like this (new message type, new UI classes etc.)? If so, do you have an ETA on when you'll be finished with the changes? Might be better to wait for that to be done before adding a new system on top if it's not too far away.

**Comment by notbakaneko** [comment]
At this moment, I wouldn't go beyond mocking up the UX flow of how users would be interacting with this; should consult with @arflyte for how it would fit into the current or any upcoming designs. Chat currently needs a decent bit of work that isn't just bolting more things onto it, at the moment.

**Comment by notbakaneko** [comment]
Are there any updates on ideas for the flow of how this would be used / displayed?

**Comment by LeoFLT** [comment]
We could really use this for the world cups. That said, for it to be useable for our needs, some feature parity with the current legacy PM system is needed. Things that are absolutely needed:

- Markdown support (mainly for bulleted lists and font weight of course, we usually send big player lists and it needs some sort of formatting to look presentable)
- Sensible character limits, the ones currently employed for normal DMs are already insufficient in my experience when sending a user a notice as a GMT, player lists with an arbitrary number of entries would go over this limit really quick
- Ability to send mass DMs (think BCC field in an email)

These are the bare minimum if this is to sunset the legacy system, currently it's the only platform that offers this sort of functionality and it's precarious to say the least to actually access the messages if you're not used to the workarounds. 

Markdown support is arguably optional but currently even typing a new line is a challenge with the chat system, it's not suited for longer messages.

**Comment by Gamingzone123** [comment]
is this closeable?, everything seems merged...

**Comment by peppy** [comment]
The system isn't usable yet because there's no way to trigger it. We'll keep it open until that happens.

**Comment by tybug** [comment]
can be closed now that https://github.com/ppy/osu-web/pull/8747 is merged?

**Comment by peppy** [comment]
I think so yes. Can open new issues for any follow-up work.
