### ISSUE TITLE
after mp game is disbanded, match page still thinks it in progress

### ISSUE THREAD

**Issue by lmnyx** [ppy/osu-web#6513]
![example](https://user-images.githubusercontent.com/13962537/90545814-a2c51d00-e1a2-11ea-88d8-0659d7f1a3eb.png)
https://osu.ppy.sh/community/matches/65559787

**Comment by gagahpangeran** [comment]
Looks like it's because the latest event type is not `match-disbanded`, so it's still assume the match is in progress.

https://github.com/ppy/osu-web/blob/a0be5592bd39149aa0194252327a600c32f6e3bd/resources/assets/coffee/react/mp-history/main.coffee#L76-L77

https://github.com/ppy/osu-web/blob/a0be5592bd39149aa0194252327a600c32f6e3bd/resources/assets/coffee/react/mp-history/content.coffee#L88-L95
