### ISSUE TITLE
Missing some flags image

### ISSUE THREAD

**Issue by marcostudios** [ppy/osu-web#66]
Missing the Netherlands Antilles flag (https://jizz.ppy.sh/images/flags/AN.png)

**Comment by claudiodekker** [comment]
This is probably because the Netherlands Antilles does no longer officially exist as of 2010, and they each now have their own separate flag. To prevent issues, however, I've quickly mocked up a flag anyway, since most people still refer to it as the Netherlands Antilles anyway.

![na](https://cloud.githubusercontent.com/assets/1752195/9749066/ea8b0342-5689-11e5-813d-84d5fa6a8b91.png)

**Comment by nanaya** [comment]
I did make a list at one point. I think only HK has been added afterwards. https://0paste.com/7382

**Comment by nekodex** [comment]
I believe this has been fixed, closing.
