### ISSUE TITLE
Beatmap leaderboard is cut off well before 50 scores

### ISSUE THREAD

**Issue by Magnus-Cosmos** [ppy/osu-web#6764]
On this beatmap: https://osu.ppy.sh/beatmapsets/639281#osu/1417193
The leaderboard stops at 13 scores, when there are supposed to be way more.
![adrenaline leaderboard bug](https://user-images.githubusercontent.com/39173355/96085411-c6e56780-0e8e-11eb-9b0e-6f9633878fbb.PNG)
Checking in-game, there are around 3k scores.
![screenshot3543](https://user-images.githubusercontent.com/39173355/96085725-38bdb100-0e8f-11eb-81b1-8fb8155d56bf.png)
This issue also happens on the country and friend leaderboards.

**Comment by peppy** [comment]
No too sure what's going on here, I tried reindexing but it didn't help.

**Comment by abraker95** [comment]
`https://osu.ppy.sh/beatmaps/1417193/scores` gets top 14 while `https://osu.ppy.sh/api/get_scores?b=1417193&k=` gets top 50

**Comment by cl8n** [comment]
the scores listing query gets the top 150 scores on the map, then filters out any that aren't the user's top score, then limits to 50 again https://github.com/ppy/osu-web/blob/master/app/Models/Score/Best/Model.php#L65-L91

so I think what's going on here is a lot of the top players on that map have scores with lots of mod combinations (would make sense because it's so short), and this implementation doesn't work because it assumes less than 3 scores per user in top 150. can someone check mod leaderboards to see if that makes sense, i dont have supporter

**Comment by abraker95** [comment]
There is one with 6 mods, and a couple with 4 mod combos beyond top 50. There rest have 3 or less mod combos.

![](https://i.imgur.com/0Otz0eX.png)

**Comment by cl8n** [comment]
i mean multiple scores with different mods. you'd have to check different mod pages to find them. I'm suspecting that some of the top 13 players are going to appear near the top of a lot of the mod leaderboards

**Comment by Magnus-Cosmos** [comment]
Indeed, [beef wellington](https://osu.ppy.sh/users/6841423) has done over 100 scores with different mods. He actually mentions this might be the case in the comments - https://osu.ppy.sh/comments/1217176

**Comment by nanaya** [comment]
That is indeed the cause. It's not a problem in old web because it fetches the data multiple times until there's enough rows. Similar logic should probably be copied over.
