### ISSUE TITLE
Error on website, only one of the languages is not uppercase on first, while all the rest yes. Please correct this. :)

### ISSUE THREAD

**Issue by ErrorFinder-osu** [ppy/osu-web#6840]
Only happens on Spanish/Español.
![Screenshot_2020-10-31 dashboard osu ](https://user-images.githubusercontent.com/73762816/97791863-d4e8f700-1bb5-11eb-86cc-201b3bccb099.png)

**Comment by qauland** [comment]
According to #6241,

> Language names in Spanish are common nouns (_nombres comunes_) and the first letter shouldn't be capitalised.

**Comment by bdach** [comment]
While this issue is a huge nitpick, if each language's capitalisation standards are to be used, they should probably be enforced in all cases. As far as I can tell there are some other language names on that list that do not abide by their language's capitalisation rules - from the ones I know without having to google, I'm pretty sure both "polski" and "français" should be lower-cased to match.

**Comment by ErrorFinder-osu** [comment]
> 
> 
> While this issue is a huge nitpick, if each language's capitalisation standards are to be used, they should probably be enforced in all cases. As far as I can tell there are some other language names on that list that do not abide by their language's capitalisation rules - from the ones I know without having to google, I'm pretty sure both "polski" and "français" should be lower-cased to match.

That's it. All uppercase/not uppercase or all in their respective language rules.

**Comment by peppy** [comment]
When adding these I would copy from the wikipedia entry as that seemed to be correct. I'll fix the above ones accordingly (to match the language's rules) but please list any others which look incorrect.

**Comment by cl8n** [comment]
"common noun" doesn't mean "lowercase" though... if it's sentence or title cased for style, you'd have the appropriate caps to go along with it in all of these languages. I don't think I've seen a language selector *not* capitalize all of them, including the one on Wikipedia...

**Comment by peppy** [comment]
Feel free to provide an alternative PR, probably faster.

**Comment by notbakaneko** [comment]
Wikipedia itself isn't consistent; the list of languages [here](https://meta.wikimedia.org/wiki/List_of_Wikipedias) follows the rules of each language but at the same time, the [Spanish version](https://es.wikipedia.org/wiki/Anexo:Wikipedias) of the list in the table doesn't, even for Spanish itself, but the [French version](https://fr.wikipedia.org/wiki/Liste_des_%C3%A9ditions_de_Wikip%C3%A9dia) does.

**Comment by Helen0903** [comment]
All 3 pages seem to follow 2 fairly standard capitalisation rules:
- Capitalise if it's the first word in the row/cell
- Then use the respective language's formatting rules

Only exception is at the top of the [List of Wikipedias](https://meta.wikimedia.org/wiki/List_of_Wikipedias) page, where the languages all follow their respective rules. I support capitalising, but it's really a debate about style.

The English version of osu!'s [Article Styling Criteria](https://osu.ppy.sh/help/wiki/Article_Styling_Criteria) is pretty clear that language names should be capitalised, so that should probably be corrected (or not, whichever ends up being chosen) as well.
![Screenshot of article saying languages should be capitalised](https://puu.sh/GJkhe/6c292cd2cd.png)

**Comment by bdach** [comment]
> The English version of osu!'s [Article Styling Criteria](https://osu.ppy.sh/help/wiki/Article_Styling_Criteria) is pretty clear that language names should be capitalised, so that should probably be corrected (or not, whichever ends up being chosen) as well.

That's just a rule of the English language, though. English language names used in English text are generally capitalised regardless of the language, so it's not the same thing.
