### ISSUE TITLE
Can't play song preview on a certain map

### ISSUE THREAD

**Issue by TamamoNoMae13** [ppy/osu-web#6907]
Many old ranked maps (before ranking criteria is even written properly) using ogg audio files (vorbis), and some recent ranked maps (6 mapsets since the change allowing the use of ogg files) also using it.
Most of them can play the preview normally on the web.
However this map can't:
https://osu.ppy.sh/beatmapsets/8768#osu/35652
Although it works fine in song select ingame.
It seems that web decide how to play (decode) it with the extension of the file. Because when I checked the audio files (track10.ogg), it was mp3 codec.

**Comment by peppy** [comment]
I belive these older maps need manual regeneration. I'll grab it.

**Comment by peppy** [comment]
Seems like this is going to require a special submission to get right (missing osz2 file server-side, so regeneration alone is not enough). @Ephemeralis can you have a shot at this?

**Comment by Ephemeralis** [comment]
I've resubmitted the map (breaking the normal diff in the process due to... shenanigans), which has apparently recreated the osz2 file, but further investigation is needed to see why the preview isn't regenerating.

**Comment by huupoke12** [comment]
@Ephemeralis I don't think the beatmap has been modified when you resubmited it, because I have just downloaded the beatmap, but the audio file is still named `track10.ogg` (it should be `track10.mp3` instead), and the map files still reference to `track10.ogg` instead of `track10.mp3`.
(The audio file codec is `mp3`, but the author wrongly set the file extension as `ogg`, as has been already mentioned by @TamamoNoMae13).

**Comment by peppy** [comment]
Tracking in https://github.com/ppy/osu-web/issues/5955.
