### ISSUE TITLE
When unfocused, Audio Preview on Autoplay may repeat itself.

### ISSUE THREAD

**Issue by ReiFan49** [ppy/osu-web#6957]
As the title says, if you leave the window unfocused (to other tabs). The `playerNext` of the audio player will refer to the same audio for unspecified times.

This is how the assets are loaded into
![image](https://user-images.githubusercontent.com/9847780/101590603-56d20880-3a1d-11eb-8e8d-a4e2b7ace57d.png)

and, when I tried to debug it somewhere around 3s/5s/10s interval, the change can happen somewhere during the song play
![image](https://user-images.githubusercontent.com/9847780/101590678-7832f480-3a1d-11eb-84ac-d9cd268ecb12.png)
_duplicates are discarded automatically by browser_

Note: output format is "Current preview url" and "Next preview url".

To replicate:
1. Have autoplay toggle on (anonymous/non-logged in access are preferred)
2. Play set of beatmap previews from certain mapper who had at least 5 maps on respective category you want to listen to.
3. Let the window blurred (not just change into other window, but you have to change the tab to make sure the _blur_ is in)
4. There you go, the playlist sometimes repeats the same song (the longer the playlist, the longer the self-repeat goes on)

Browser in use: Firefox 78 ESR

**Comment by gagahpangeran** [comment]
Can confirm and also happen in chrome.

After some check it happenned in this code.

https://github.com/ppy/osu-web/blob/baf4356bf167c411ea8a4a676521bcccf46670e7/resources/assets/lib/osu-audio/main.ts#L393-L418

`requestAnimationFrame` is paused when tab is not active or running in the background (this is expected behaviour based on [the documentation](https://developer.mozilla.org/en-US/docs/Web/API/window/requestAnimationFrame)), so the callback function didn't run and `this.playerNext` was never change.
