### ISSUE TITLE
Show nominators on qualified/ranked beatmapset listing page

### ISSUE THREAD

**Issue by Ephemeralis** [ppy/osu-web#7008]
The nominators for a given set should appear on the listing page when it hits qualified or ranked. For example, https://osu.ppy.sh/beatmapsets/1223737#osu/2545340 should show that Karen and Milan- are responsible for nominating it somewhere on the main page instead of needing to click through into discussions.

Why?

Currently, nominating a map is fairly transactional - there is little prestige or acclaim involved for the people putting the sets forward themselves, knowing full well that their names are essentially hidden behind a clickthrough that 90%+ of players will not ever use.

Associating nominators closely with a set allows them to use the types of work they push as a kind of social "badge of honor". Nominators that push consistently good sets will gain reputation along with the mappers they help elevate, while nominators that consistently push poor sets will gain the appropriate notoriety for their decisions as well. This kind of push-pull effect is very important to have in communities as a form of social self-regulation. 

This is otherwise a very minor design change that will likely have measurable (if slight) impact on map quality and the health of the modding scene going forward. Please consider it.

**Comment by DaxMasterix** [comment]
It's already shown on  [Discussion] so this would be a pretty neat and (I think) easy addition to the page. 
At the same time we could stretch it a little.

IMO, Only the username showing isn't enough, I think is important to exploit the positive side of this Idea, by garantee not to take back the "Badge of Honor" if it's about a Rank-Streak or something among the lines, etc.
I'm not a BN so I can't talk much for them, but I know (Or at least I feel) it can be such an stressful duty for something so trivial like being part of the community.

I also think this could sadly encourage some BNs on avoid taking risks when talking about New Mappers so... Something like **Additional Points** when taking those risks should be pretty good. High Risks, High Rewards.

And just like you said, This is otherwise a very minor design change, a good one for sure.

**Comment by BlastTheKidd** [comment]
> while nominators that consistently push poor sets will gain the appropriate notoriety for their decisions as well

The wording on this is kind of strange but I think the general idea is definitely something that was needed.

**Comment by camellirite** [comment]
agree with this 100%, it might make some people use bn's nomination logs as a way of discovering new maps if some bns make a really good reputation for themselves

**Comment by peppy** [comment]
@arflyte can you advise where this should be displayed?

**Comment by arflyte** [comment]
![Figma_210317-155354](https://user-images.githubusercontent.com/3632750/111427155-031c3d00-8739-11eb-89a9-a73892f263f6.png)
I assume this is the stuff that you all are referring to?

**Comment by peppy** [comment]
That's fine, but this is looking to add the same information to the beatmap information page (one page up from this). So that people can see these users without going in to the modding interface.

**Comment by arflyte** [comment]
Oh, the beatmap info page itself. I'll look into it.

**Comment by arflyte** [comment]
![Figma_210317-155945](https://user-images.githubusercontent.com/3632750/111427727-dd436800-8739-11eb-81b6-6f26dd27478b.png)
Something like this?

**Comment by peppy** [comment]
I think that's fine, although one may argue that the creator has a lot less presence than they do on the old design.

**Comment by arflyte** [comment]
Hmm. I'll think of something.

**Comment by Kimitakari** [comment]
Maybe change the highlighted colour with creator and nominator (thought it would be a bit illogical in terms of matching the overall design)?

**Comment by arflyte** [comment]
![Figma_210317-183654](https://user-images.githubusercontent.com/3632750/111446460-c7d93880-874f-11eb-9dbf-c1563f0e2e6c.png)
Prelim design update.

**Comment by Ephemeralis** [comment]
should be 'Nominators' and may also need to accommodate up to 8 people (2 nominators for each mode for full hybrid sets)
