### ISSUE TITLE
BBCode Profile tag ignores text within/ignores color tag

### ISSUE THREAD

**Issue by shrublet** [ppy/osu-web#7075]
Unsure if intended, but text within the [profile] [/prorfile] tags is not representative of what is inside and instead pulls the name of the profile. This makes sense, but also kinda sucks if you're trying to format or write somebody's name a certain way. While tags inside do not work, using tags _outside_ works for most, but color notably doesn't which I think is a valuable addition along with customizing the profile text. The alternative that I used previously was a URL tag, but I appreciate the functionality of the profile tag showing profile on hover.

Edit- revised

**Comment by notbakaneko** [comment]
This is intentional, `[profile]` will only show the user's current username as a usercard link to remove any ambiguity. #6707

**Comment by Magnus-Cosmos** [comment]
Could this be revisited? Perhaps making an exclusion for tags (e.g. if there is an `[img]` tag, ignore it and only replace outside of the tag, and for text tags, like `[color]`, ignore the tags and replace what is within).

I have auto-generated `user-card-brick` images which I currently link to the user's profile with the `[url]` tag. It would be a lot better if I could put these images within `[profile]` tags so that it shows the user card on hover.
![image](https://user-images.githubusercontent.com/39173355/119216665-f56d9580-baa2-11eb-8395-83fe203033cc.png)
