### ISSUE TITLE
Recent active user search doesn't quite work

### ISSUE THREAD

**Issue by nanaya** [ppy/osu-web#7185]
(`recent_only=1` parameter for user search)

It searches based on `user_lastvisit` in the elasticsearch but the entry is only updated on renames and registrations.

It currently "works" on live site because we recently reindexed the whole thing but it'll get stale as time passes.

Maybe should just let user to be reindexed every time it's updated?

Edit: users hiding their presence shouldn't have the actual value indexed

**Comment by peppy** [comment]
Where is the `recent_only` flag used? Is this intended to be for the client or something else?

**Comment by nanaya** [comment]
It's not currently exposed anywhere

**Comment by notbakaneko** [comment]
I think the question is whether there is any need to keep it - it was originally added on the basis if you were searching for a username, you'd likely want the one that is active. Although, with hiding online status being a thing, you could be never active?

**Comment by peppy** [comment]
Going forward, we likely want this for the client (to be able to list and search active users similar to what `osu-stable` does). Currently in lazer this is being done via the SignalR server, but that only shows users which are actively in gameplay, rather than users which are sitting around chilling.
