### ISSUE TITLE
BSS Creator Name Bug

### ISSUE THREAD

**Issue by spxder** [ppy/osu-web#7208]
So uh I have found a Beatmap Submittion bug on accident and it can be very gamebreaking, i guess.
I originally wanted to submit a beatmap, that had 3 Diffs but forgot to change the username of these beatmaps. I then changed only one of them to my original Osu IGN to submit this map. It actually submitted and after I checked on it I saw the previous Name of it just standing there. [My osu IGN is SpxderWeeb] (Beatmap: https://osu.ppy.sh/beatmapsets/1373244#osu/2839060) (Screenshot: https://i.imgur.com/t9ivkvR.png)

out of curiousity, i submitted a test map with broken unicode, and uh yeah please fix. (beatmap: https://osu.ppy.sh/beatmapsets/1373255#osu/2839092) (screenshot: https://i.imgur.com/twBr3FJ.png)

And sorry for the weird format, I'm using gitlab for the first time here.

**Comment by Eeveelution** [comment]
we have just checked this for potential XSS vulnerability and it seems like it isnt vulnerable to it

**Comment by Eeveelution** [comment]
To fully recreate:
1. Create a map with 2 difficulties
2. Have 1 difficulty have a different Name
3. Submit Beatmap
4. Visit the Broken Difficulties Page,
5. Refresh,

If all went well the Creator name should differ

**Comment by iptq** [comment]
can confirm, just reproduced the bug with https://osu.ppy.sh/beatmapsets/1256017#osu/2839228

![image](https://user-images.githubusercontent.com/1700346/107816467-6f6edf80-6d3a-11eb-81fb-73dcfaab75d9.png)

it's definitely been a bug for a long time, someone [submitted one of my unuploaded maps from like 2015 as me](https://osu.ppy.sh/beatmapsets/496371#osu/1056534)

i'm guessing this is because creator is stored as a string in the map while the website knows the user id of the uploader.

maybe a fix for this could just have the website display the real username fetched from the id rather than relying on the creator? (this might be controversial since some people prefer seeing previous usernames for certain maps since they associate it with that username)

**Comment by peppy** [comment]
This is intended to handle the rename scenario, so people can still locate maps they know by the original creator name. Probably just needs a check at upload time to force the creator name to be correct.

**Comment by peppy** [comment]
It turns out all the correct checks were in place, but were temporarily disabled to fix some old beatmaps (using an admin override flag).

Could you please try to reproduce this now? It should no longer be possible.

**Comment by iptq** [comment]
Just tried resubmitting the above map with no changes and got a 500 instead

![image](https://user-images.githubusercontent.com/1700346/107850897-827dc000-6dcb-11eb-9a7a-113490a0b482.png)

**Comment by peppy** [comment]
Hmm, that's not the expected error. Try once more?

**Comment by iptq** [comment]
OK this looks like the correct error. 

![image](https://user-images.githubusercontent.com/1700346/107851028-4eef6580-6dcc-11eb-8159-44b3e9d386e6.png)

two things tho:

- Could there be a message saying that _some_ of the diffs don't have the correct creator vs. just "this beatmap isn't yours"?
- It still went through the entire upload process which for a large beatmap could take a long time. Would it be possible to complete this check earlier in the submission process?

**Comment by peppy** [comment]
Thanks for the confirmation.

No normal user will hit this issue, so I don't think it needs more attention. We will probably add better client side verification in lazer.

I'll do a pass on the database and delete any maps which looks to be abusing this, since there was a small gap where this could have been abused.
