### ISSUE TITLE
Incorrect timestamps after time change

### ISSUE THREAD

**Issue by dorothy3242** [ppy/osu-web#7310]
Today Daylight savings ended in many places, and clocks were moved 1 hour forward in most places.

However, the osu! website is showing me differing, causing it to tell me things that were just posted will happen in 60 minutes

![image](https://user-images.githubusercontent.com/33286824/111085214-be9c6180-84ec-11eb-8f2d-c2ba9b0fb38a.png)

I did not see anywhere on the osu! settings to fix my time.

**Comment by Joehuu** [comment]
Did you perhaps leave that tab open since the time change? I would try closing that tab first, then the whole browser, or even restarting. The timestamps displayed depends on your windows settings, and that browser tab has yet to update.

For testing, I set my windows time manually 1 hour before and the osu! site and even GitHub don't update the timestamps until closing the tab and opening it again (reloading won't work).

**Comment by dorothy3242** [comment]
Unexpectedly that did fix it, thanks. Thought it was still going off some time stored on the osu site forever.
