### ISSUE TITLE
History of multiplayer lobbies you joined

### ISSUE THREAD

**Issue by thymue** [ppy/osu-web#7320]
If it's possible, it would be nice to have a page that displays what multiplayer matches I joined so I can access the mp links after I accidentally leave and forget grabbing it from the mp chat.

**Comment by peppy** [comment]
This is already implemented in the new multiplayer system in lazer. We do need to add web support for this. I *believe* there may be an issue tracking adding exactly this to the profile page, but if not, let's keep this open to track it.

**Comment by peppy** [comment]
This has since been implemented for playlist rooms (see https://osu.ppy.sh/users/2/multiplayer), but doesn't work for multiplayer rooms, strangely.

I believe there was discussion elsewhere recently regarding splitting this tab into a "playlists" and "multiplayer" listing, but can't immediately find it.
