### ISSUE TITLE
No way to logout or re-request verification email

### ISSUE THREAD

**Issue by peppy** [ppy/osu-web#733]
![image](https://cloud.githubusercontent.com/assets/191335/18580176/ea22505a-7c34-11e6-8ec7-ab4c43856e55.png)

Should at very least be able to logout and try again.

**Comment by NeoAdonis** [comment]
![osuweb-reissue](https://cloud.githubusercontent.com/assets/1562728/18661706/cddd2dca-7edc-11e6-9230-b42be47f0826.PNG)

I wonder if showing the logout button there is the best thing. Probably it is, as no other action should be allowed if you need to verify, I suppose.

Also: why are the keys saved on session instead of on database? If we're going to allow logout, I think it's needed to save those keys on DB now.

Attaching sample of what I've done. If this is fine, I'll create a new pull request.

**Comment by peppy** [comment]
That's a lot of separate lines.

How about

"If you can't acccess your email or have forgotten what you used, please follow the [[email recovery process]]. You can also [[request another code]] or log out."

On logout the existing code should be *cleared and invalidated*.

**Comment by peppy** [comment]
I've awarded 50 bounty for this fix, thanks!
