### ISSUE TITLE
API endpoint to retrieve all of a player's scores

### ISSUE THREAD

**Issue by LeaPhant** [ppy/osu-web#7348]
Having a way to retrieve all of a player's scores without having to request each score one by one would be really handy for projects that need that data to work properly. This could be solved by either adding a new endpoint `/users/{user}/scores/all` that returns up to 50 scores per page in whatever sorting is the most efficient for the database – or uncapping the `/users/{user}/scores/best`or `/users/{user}/scores/recent` endpoint, which seem to be currently capped at 100 scores max on the database side.

**Comment by peppy** [comment]
i here is a reason it is "capped" - this is quite expensive.

can you state your use case so we can potentially look at other options?

**Comment by Magnus-Cosmos** [comment]
Having all scores (or just more viewable scores in general) would be very useful for profile analysis. Sometimes I want to check the progression of a player on a map in their recent plays, but the plays' offsets are >99 in recent plays. Similarly, there are times where I want to do replay analysis of a player's replays, but no scores with replay data exist in their top 100 best scores (or in recent activity).

But I agree that this would be very expensive in cases where the player has many scores (e.g. score farmers like xasuma have tens of thousands of scores).

**Comment by peppy** [comment]
The expensive part comes from a sudden influx of third party services wanting to consume the new information, specifically. You have to consider that after some services find this data available, they will begin to retrieve the full data set, which is terabytes in overhead, not to mention the added load on the web site.

**Comment by tybug** [comment]
Is there a solution to this that doesn't involve not providing useful endpoints simply because they could be abused? Perhaps a per-day ratelimit could be added for endpoints where full dataset retrieval is a concern, so no application can make more than a thousand requests per 24 hours to this endpoint, or some other reasonable number.

**Comment by peppy** [comment]
Not sure. Monthly full database dumps or something?

**Comment by LeaPhant** [comment]
> there is a reason it is "capped" - this is quite expensive.
> 
> can you state your use case so we can potentially look at other options?

The use case is a site that lets players browse their plays filtering or sorting by different parameters (e.g. scores on 2012 maps sorted by pp, all scores sorted by combo) or lets them view graphs of this data (e.g. amount of SS ranks per month).

There's a niche in the community that wants better tools for this (completionists, score farmers, SS farmers) and I think it would be fun to experiment with visualizing osu data in different ways.

**Comment by sverrier** [comment]
A monthly full database dump would be great I think. Would simplify the gathering of data a lot, although it might take some work to filter it for the more complex use cases.

**Comment by Orisgeinkras** [comment]
"which seem to be currently capped at 100 scores max on the database side."

via `/users/[user]/scores/best?limit=100` I'm only getting 50 results, which seems to be the cap of `limit`, if I'm not mistaken.

If the limit _is_ 50, I think the cap should be increased to 100 in order to match the number of plays visible on the user's profile page, at the very least. I didn't think this warranted adding another issue by itself, so I figured I would add it here.

**Comment by nanaya** [comment]
Did you try the offset parameter?

**Comment by Orisgeinkras** [comment]
That seems to work. I do wish there was a way to actually list all 100 scores in one request, but it's workable for my purposes. Thank you!

**Comment by peppy** [comment]
Going to close this in favour of https://github.com/ppy/osu-web/issues/7348 as that has more recent discussion of the remaining points.
