### ISSUE TITLE
chat.write Scope Should Not Be Exclusive to Chat Bots

### ISSUE THREAD

**Issue by aticie** [ppy/osu-web#7356]
Currently the only endpoint that is using `chat.write` scope is `/chat/new`:

https://osu.ppy.sh/docs/index.html#create-new-pm

However, it is stated that this scope is only exclusive to Chat Bots. In order to apply for a bot account, there is a criteria that requires us to run the bot on personal accounts for **6 months**. 

And in order to run the bot we need to use API or IRC. The problem that comes with IRC is that we can't use user ids to pm others. 

I'm hosting a beatmap request bot (just like Mikuia, since it's down most of the time), which just relays beatmap requests from Twitch chat to in-game messages. However, when someone changes their nickname in the game, the link between twitch to in-game gets broken. To prevent this, I would love to use `/chat/new`. I already had to manually change user's osu! nickname twice in 1 month. I can't keep up with it if I get more users.

I think you should allow regular users to use the `chat.write` scope with the current rate-limit that's in the game.

**Comment by cl8n** [comment]
agreed:
- I don't see the point of restricting `chat.write` to bot accounts, it's not a security issue because resource owners still have to authorize the use of it
  - the `bot` scope already takes care of the different client-credentials behavior for `chat.write`, so this isn't relevant when considering to make `chat.write` public
- if for any reason restricting `chat.write` is necessary, can it at least be allowed when the resource owner is the client owner? that covers the use case of OP and probably many others
- `forum.write`'s accessibility is not consistent with `chat.write` for what seems like no reason, and `forum.write` has the arguably more expected behavior

**Comment by peppy** [comment]
It's fine to remove the limitations of this. I believe they were placed in a historical point where we wanted to avoid any additional security issues, but this shouldn't be the case any more.

It *should* be limited to only the account holder. ie. a request should not be able to be made on behalf of a third party.

**Comment by nanaya** [comment]
this has been added I believe 🤔

@notbakaneko ?

**Comment by notbakaneko** [comment]
changed in #7951
