### ISSUE TITLE
Pack upload page is on the old website

### ISSUE THREAD

**Issue by NoffyNoffeh** [ppy/osu-web#7427]
When I tried to go to the pack upload page https://osu.ppy.sh/web/adm-packs.php it demanded I log in first. I was already logged in on the new website. I had to force-navigate my way to the old website to log in there (extremely annoying and difficult) before the pack upload page could be accessed.

Getting this moved over to the new website is a critical issue with how finnicky verifying log ins on the old website is lately. It doesn't need to pretty. It can stay just as ugly as the current page honestly 

Image for reference of how it looks
![image](https://user-images.githubusercontent.com/33286824/113759085-acc06f80-96e2-11eb-8f63-d86af916724e.png)

If it's made prettier though it should be more visible on the packs page for people with permissions to upload packs.

**Comment by peppy** [comment]
While this may be "critical" to you, for me this is lowest of low priorities.

If we decided to continue doing packs in the current way (manual upload etc.) then it will either stay here or be converted to work via discord.

As a temporary workaround: use `old.ppy.sh` instead of `osu.ppy.sh` and login first. It will work 100% of the time.

**Comment by NoffyNoffeh** [comment]
Will that still be the case when old web is turned off?
