### ISSUE TITLE
[Feature Request] Report a score from their score page

### ISSUE THREAD

**Issue by GrilledCheeese** [ppy/osu-web#7541]
Score pages look like this: https://osu.ppy.sh/scores/osu/3626112929
![image](https://user-images.githubusercontent.com/34809632/116578133-64772480-a911-11eb-8ae0-b7593d3e0dd0.png)

It can be put on the left of "Download Replay" in the red color that is used for "Send Report"
![image](https://user-images.githubusercontent.com/34809632/116577884-2aa61e00-a911-11eb-908e-e63dcde59d98.png)

Examples:
![image](https://user-images.githubusercontent.com/34809632/116578449-b61faf00-a911-11eb-8944-4c83cbecad8f.png)
![image](https://user-images.githubusercontent.com/34809632/116578546-d18aba00-a911-11eb-9aa2-a34ade3df95f.png)
And it can have the same exclamation triangle as the profile report button:
![image](https://user-images.githubusercontent.com/34809632/116578779-0bf45700-a912-11eb-9b1d-d3fc139f4252.png)

**Comment by zeusminus** [comment]
In case reporting a score from its page is thought to be non-existent, the button appears under the hamburger menu which appears when the cursor is hovered over the usercard, as shown below: 

![](https://zeu.s-ul.eu/ze9iFhTc.png)

However, I agree that adding better visibility for this button would be preferred, since one may not guess its presence under some obscure menu.

**Comment by peppy** [comment]
I think we still want a "report score" button as score reports contain more information than user reports.

That said, if this is to be implemented it should not use the user-provided designs in the opening post, but a similar hamburger menu at a top level.
