### ISSUE TITLE
please fix registration 

### ISSUE THREAD

**Issue by chase12345678-jpg** [ppy/osu-web#7596]
sorry I'm new to this so idk how to really do it. But every time I try to make an account it just says "something happened... and we're not sure what" it may just be  because I just have a school computer and others do too. 

2021-05-13 20:06:21 [verbose]: Request to https://osu.ppy.sh/users failed with System.Net.WebException: NotFound.
2021-05-13 20:06:21 [verbose]: Response was: 404 not found

**Comment by bdach** [comment]
As a initial sanity check before proceeding further, can you access https://osu.ppy.sh/ from a web browser?

It is not impossible that given you are using a school-issued device, it has some sort of filtering that prevents students from accessing websites deemed unnecessary. It would certainly explain why the `/users` endpoint is returning 404.

**Comment by chase12345678-jpg** [comment]
@bdach no I can't that's the reason  why I mentioned it up I saw other people dealing with it as well so I didn't know if it was because of that or not.

**Comment by bdach** [comment]
In that case, if your school or academic institution has indeed completely disallowed access to the osu! website, I'm not sure there is much to be done from a development perspective. The online parts simply can't work if they can't even be reached from your device/network.

If you still wish to try the online parts of the game, I'm afraid you might have to look for alternative methods of access to use instead of the school-issued device, or possibly consult the school staff whether access can be granted.
