### ISSUE TITLE
Allow to choose several mappers as difficulty owners

### ISSUE THREAD

**Issue by Shmiklak** [ppy/osu-web#7602]
This is a common practice for a difficulty to be mapped by two or more mappers as a collaboration, however the new system lets users to choose one guest mapper per difficulty only. Perfectly, it would be the best solution if we could mark each part of the map to show who mapped it through web interface, but considering the complexity of this thing I guess it would be a better idea to implement adding of multi users per difficulty.

**Comment by Kirairu** [comment]
i think that its a good suggestion because there a lot of collab difficulties in a lot of sets

as example: https://osu.ppy.sh/beatmapsets/1443360#osu/2968957 
this map has 8 mappers and i have to claim myself as overall difficulty owner (i am but according to the modding thread it feels like i mapped the whole song by myself)

**Comment by peppy** [comment]
Already mentioned elsewhere, but this adds a whole new level of complications and is not something we will be looking at in the short term. Not out of the question, but definitely not until the whole BSS subsystem has been rewritten for lazer.

**Comment by NoffyNoffeh** [comment]
Hi I would like to follow up on this, there's been no visible progress on letting GDers submit updates for their own maps. 

From my understanding the holdback on setting multiple creators was BSS updates, but if that has been stalled anyways for other reasons, may as well implement allowing multiple creators set on a guest difficulty for web? 

It just seems like the hold back isn't relevant at the moment, when allowing multiple creators on modding discussions would be a good QoL to have sooner rather than later - especially as numerous collab maps are being mislabeled for who made them on the modding panel right now because of the limitation.

**Comment by peppy** [comment]
So we can figure out a path forward, can you provide some use cases for this? Thought process is that for large collab maps (ie. 10+ people) this wouldn't be something we'd see fitting the usage of the guest difficulty specification, so I'm interested to see some practical use cases you foresee for having more than one guest difficulty mapper for a single difficulty.

**Comment by Hiviexd** [comment]
Now that GDs appear on userpages, I think it would be a good idea to re-consider this now, because we have a viable use case now. 
Collabs are very common nowadays and it would be ideal to credit all creators with the GD function so the map can appear on their respective mappers' userpages.

**Comment by AJT127** [comment]
Aside from the fact that there are an insanely high amount of 2 person collab maps that could use this, can I ask why large collab maps would not be fitting of this feature? Especially for long maps, it can easily be the case that each contributor added something of value to the map and I don't see why they shouldn't be credited just because there are a lot of collaborators.

**Comment by elicz1** [comment]
Seeing as the recent site changes now make GDers visible next to the difficulty itself - this should really be given more priority. It is odd to see just one name in this field when there is clearly multiple mappers involved, especially if the diff name is not entirely clear as to the mappers who contributed eg. "Collab Expert".

https://osu.ppy.sh/beatmapsets/1425901#osu/2937682 (just one example)
![image](https://user-images.githubusercontent.com/104147743/204105699-b8f86ab0-3314-4bbc-afc8-123e50ab1605.png)

**Comment by aceticke** [comment]
any update on this? there is an increasing amount of multiple person collabs by the day, and in fact, recently a map which had a collaborative difficulty of 12 people was loved, but you can't assign it to anyone, meaning nobody gets credit, unless you can figure out a way to somehow agree on ONE person to get credit.

**Comment by osuZiRoX** [comment]
Another reason to implement this: Beatmap Spotlight newspost creators try to credit the actual mapper of each difficulty, obtaining difficulty ownership through the metadata of the map. Since there's no support for collabs, this means that sometimes people aren't credited properly as the collab difficulty isn't assigned to them (see https://github.com/ppy/osu-wiki/pull/9187 for such a case - and this is only a 2-man collab)

**Comment by Walavouchey** [comment]
> Another reason to implement this: Beatmap Spotlight newspost creators try to credit the actual mapper of each difficulty

will clarify that this is relevant due to those listings being automatically generated (both in news posts and in wiki pages) in most cases

**Comment by Ryuusei-Aika** [comment]
Are there any technical issues still hindering it from being implemented? peppy's reply was nearly 1.5 years ago so if things have improved since then maybe there will be workarounds for this?

**Comment by notbakaneko** [comment]
I presume that the main mapper and guest mapper mapping the same diff would also be a thing?

**Comment by Shmiklak** [comment]
> I presume that the main mapper and guest mapper mapping the same diff would also be a thing?

Yes, it is often the case. I guess Mappers' Guild website has this option defined in a perfect way.
