### ISSUE TITLE
Allow retrieving 100 scores on user scores endpoint

### ISSUE THREAD

**Issue by stanriders** [ppy/osu-web#7673]
Would be good for https://github.com/ppy/osu-tools/pull/87

**Comment by smoogipoo** [comment]
To start off with, sure. But I think instead of just 100, we should be able to retrieve more, paginated of course. Is there a reason why this isn't already a thing? Are these queries too expensive?

I could foresee several hundred scores being retrieved as a buffer, since:
1. The top 100 scores contribute to weighted pp.
2. After a change in SR/PP, scores currently outside the top 100 can be pushed into the top 100.

The tool mentioned in the OP allows recalculating the PP of entire profiles.

**Comment by tybug** [comment]
See https://github.com/ppy/osu-web/issues/7674 for discussion on retrieving more than 100 best scores, including discussion of profile recalcs (tldr it's expensive, though I don't want to speak for the team on that one)
