### ISSUE TITLE
All token requests for API give me Response <400> authorization grant not supported

### ISSUE THREAD

**Issue by eclipsevtuber** [ppy/osu-web#7717]
It doesn't matter what I change on the post requests, all requests to 'https://osu.ppy.sh/oauth/token' give me the same error. Is there a fix for this? Why can't I get a token?

**Comment by bdach** [comment]
404 is "Not Found". If that's what you're getting then that's a network problem, but I doubt it is what you're getting, since you mention "authorisation grant not supported".

Did you check all of these? https://github.com/ppy/osu-web/search?q=authorization+grant+not+supported+is%3Aissue&type=issues

**Comment by eclipsevtuber** [comment]
> 404 is "Not Found". If that's what you're getting then that's a network problem, but I doubt it is what you're getting, since you mention "authorisation grant not supported".
> 
> Did you check all of these? https://github.com/ppy/osu-web/search?q=authorization+grant+not+supported+is%3Aissue&type=issues

I meant to type "400" not 404

**Comment by eclipsevtuber** [comment]
Here's the full traceback I get `<Response [400]>
{"error":"The authorization grant type is not supported by the authorization server."}`

**Comment by gagahpangeran** [comment]
Have you tried the right [auth step as per docs](https://osu.ppy.sh/docs/#authentication)?

There must be something wrong with your auth if you get error 400.

**Comment by eclipsevtuber** [comment]
and here is my authorization params:
`params = {
        'client_id': clientid,
        'client_secret': clientsecret,
        'scope': 'public',
        "grant_type": "client_credentials"
    }`

**Comment by eclipsevtuber** [comment]
> Have you tried the right [auth step as per docs](https://osu.ppy.sh/docs/#authentication)?
> 
> There must be something wrong with your auth if you get error 400.

I followed it exactly

**Comment by eclipsevtuber** [comment]
```
with open('credentials.json', 'r') as f:
        credentials = json.loads(f.readline())
    clientid = credentials['client-id']
    clientsecret = credentials['client-secret']
    params = {
        'client_id': clientid,
        'client_secret': clientsecret,
        'scope': 'public',
        "grant_type": "client_credentials"
    }
    headers = {
        'Accept': 'application/json',
        'Content-Type': 'application/json'
    }
    r = requests.post('https://osu.ppy.sh/oauth/token', params=params, headers=headers)
    print(r)
    print(r.text)
```

**Comment by eclipsevtuber** [comment]
made in python, but it follows the literal word-for-word format on the website

**Comment by bdach** [comment]
There's no need to keep posting comments one after another, this is not a chatroom. A single complete would suffice.

Did you check the closed issues I linked above? I believe you'll find https://github.com/ppy/osu-web/issues/5872 is relevant. Namely it looks like you're passing the auth parameters in the query string and not the request body (I believe the param in `requests` you're looking for named `data` rather than `params`)

**Comment by eclipsevtuber** [comment]
> There's no need to keep posting comments one after another, this is not a chatroom. A single complete one would suffice.
> 
> Did you check the closed issues I linked above? I believe you'll find #5872 is relevant. Namely it looks like you're passing the auth parameters in the query string and not the request body (I believe the param in `requests` you're looking for named `data` rather than `params`)

Just tried it, it still isn't working for some reason.
