### ISSUE TITLE
Tweak the low end of the difficulty color spectrum (<1.5*)

### ISSUE THREAD

**Issue by FD5GD** [ppy/osu-web#7955]
So the difficulty spectrum is supposed to "allow the player to roughly guess the star rating" by just the color, and I really like that idea actually being implemented.
There are some things I would do slightly differently, mostly subjective (like the 8.00* jump), but one issue really should be corrected, that is **the constant blue color below 1.50*.**
Firstly, when looking at just this color, there's no way to determine if it's a 0.50* or a 1.50* (even slightly higher SRs like 1.60* blend in due to how close the colors are) and some mapsets do have Beginner difficulties way below 1.00* along with Easy difficulties at around 1.50*. For example, [the lowest SR'd ranked map](https://osu.ppy.sh/beatmapsets/958476) sits at 0.34* and [this mapset](https://osu.ppy.sh/beatmapsets/1102512) combines a 0.60* and a 1.43*.
Secondly, there exists a category of maps that would never show up in ranked, but isn't that uncommon in the unranked or even loved section. Those are maps with an extremely low star rating (0.0x*, often 0.00*) and range from WIP placeholders through special long difficulties meant to raise the upload size limit for [map packs](https://osu.ppy.sh/beatmapsets/547197#mania/1159070), all the way to [spinner-only maps](https://osu.ppy.sh/beatmapsets/1471364#osu/3020634) (these are between 0.10* and 0.15* and maybe shouldn't be included in this category). I believe these should have their own color for identification as well. Let's set the threshold to 0.10* or 0.20* (depends on whether we want to include the spinner maps) since ranked maps are unlikely to reach below that point anyway, and the color to an average grey (in my opinion it fits for difficulties not meant to be played).

The current code for the colour spectrum is (lines 22-26):
```
const difficultyColourSpectrum = d3.scaleLinear<string>()
  .domain([1.5, 2, 2.5, 3.25, 4.5, 6, 7, 8])
  .clamp(true)
  .range(['#4FC0FF', '#4FFFD5', '#7CFF4F', '#F6F05C', '#FF8068', '#FF3C71', '#6563DE', '#18158E'])
  .interpolate(d3.interpolateRgb.gamma(2.2));
```
and (lines 92-95):
```
export function getDiffColour(rating?: number | null) {
  rating ??= 0;
  return rating >= 8 ? '#000000' : difficultyColourSpectrum(rating);
}
```
I suggest a simple change in lines 23-25 (the blue progresses towards white as SR decreases):
```
  .domain([0.1, 1.5, 2, 2.5, 3.25, 4.5, 6, 7, 8])
  .clamp(true)
  .range(['#F5FAFF', '#4FC0FF', '#4FFFD5', '#7CFF4F', '#F6F05C', '#FF8068', '#FF3C71', '#6563DE', '#18158E'])
```
and in line 94:
```
  return rating >= 8 ? '#000000' : rating < 0.1 ? '#AAAAAA' : difficultyColourSpectrum(rating);
```

**Comment by peppy** [comment]
I think this is unnecessary. Let's see what others think.

**Comment by FD5GD** [comment]
If this is too complex, just the first point (blue to white) could do.

**Comment by Purplegaze** [comment]
I agree with this. The new spectrum does a great job in allowing players to guess the star rating from the colour, and adding more distinctions is definitely a benefit. Blank diffs being gray would also really help with sets where they are included for whatever reason.

**I would also like to point out another issue which I believe to be more important as well:**

Currently, when you look at the gradient at a glance, the range between 4.5-6 stars appears to blend in far more slowly than the ranges below and above it.
The difference in colour between 4.8* and 5.4* appears much smaller than the difference between 6.6* and 7.2*:
![image](https://user-images.githubusercontent.com/25409695/129385102-b966ea5e-bd0f-4284-9360-84eebf7b8cc9.png)

This is problematic for display because **4.5-6.5 stars is the most common range where multiple difficulties of similar levels are present** in larger mapsets involving multiple levels of Expert difficulties. (examples: [large set](https://osu.ppy.sh/beatmapsets/972812#osu/2317620), [very large set](https://osu.ppy.sh/beatmapsets/972025#osu/2077771))

I propose removing the harsh jump at 8* and using the extra space in the spectrum to spread the points back a bit, so the rainbow looks smoother:
```
  .domain([0.1, 1.5, 2, 2.5, 3.3, 4.2, 4.9, 5.8, 6.7, 7.5, 8.5])
  .clamp(true)
  .range(['#F5FAFF', '#4FC0FF', '#4FFFD5', '#7CFF4F', '#F6F05C', '#FF8068', '#FF4E6F', '#C645B8', '#6563DE', '#18158E', '#000000'])
```

```
  return rating >= 8.5 ? '#000000' : rating < 0.1 ? '#AAAAAA' : difficultyColourSpectrum(rating);
```


![difficulty](https://user-images.githubusercontent.com/25409695/129386103-edb3ce15-d577-4e61-b20a-9d8ad4f28f43.png)

I haven't seen one stated anywhere, but if there's a specific reason there has to be a harsh jump at 8*, the end of the last point can be cut off at a slightly lighter colour there too.

**Comment by NoffyNoffeh** [comment]
Purplegaze's proposed adjustment for the 4.5-6.5 range does well to fix what I've seen mirrored in other's thoughts about the change - that being it's really cool, but Hard-Extra currently feel a bit too close together color wise. 

I don't feel like the white differentiation for the low end is really beneficial though because below a certain point all diffs are just "you are able to play this after playing the tutorial"... the osu! tutorial is 1.17* for reference.

**Comment by Purplegaze** [comment]
> I don't feel like the white differentiation for the low end is really beneficial though because below a certain point all diffs are just "you are able to play this after playing the tutorial"... the osu! tutorial is 1.17* for reference.

I'm exclusively a standard player and I don't know how relevant me being hilariously bad at other gamemodes is, but as someone who has very little playtime in their gamemodes, I played the [taiko mapset linked in the original post (0.6*, 1.43*)](https://osu.ppy.sh/beatmapsets/1102512#taiko/2305077) as well as [this catch set (0.7*, 1.09*, 1.53*)](https://osu.ppy.sh/beatmapsets/420858#fruits/910459) and [this 5K mania set (0.68*, 0.74*, 1.07*, 1.56*)](https://osu.ppy.sh/beatmapsets/519251#mania/1103166) and it seems like there's a decent difference in how those star ratings play to a complete noob (though, to the looks of it that mania set seems to be underweighted according to the comments, which explains why I got a C rank on the 1.07* and couldn't pass the 1.56*).

Whether or not differences in difficulty to a completely new player with only 5-10 hours of playtime matter to this is up for debate, but I would just like to add that "anything <1.5* is trivial to play after the tutorial" doesn't seem to apply as much for other gamemodes which seem to require comparatively more inputs for maps calculated to have SRs that low.

**Comment by FD5GD** [comment]
The change in 4.5* to 6.5* is great imo because right now 4.50* and 5.00* are nearly indistinguishable. It also brings the Expert range colors closer to where they were in the old system, the text color threshold at 6.50* closer to a deeper purple (right now the combination right at 6.50* looks a bit awkward), and the removal of the 8.00* jump with the extension to 9.00* will allow reading the SR by color in that range as well.

Also indeed this proposal is made with newbies in mind in the first place, and maybe mania players hunting easy 1M scores. The 5K set you mentioned is indeed underrated, as LN maps tend to be below a certain point, and it contains inverse patterns, which themselves can be hard to learn.

**Comment by peppy** [comment]
@arflyte thoughts on this? are you open to changes like this?

**Comment by Corne2Plum3** [comment]
As a 6 digits, it's also hard for me to see the difference between a 4 and a 5 stars.

I looked at the @PurpleGaze suggestion: he has good ideas that helped me to make this but I wasn't agree with some colors, especially the white under 1 star. I tried to improve it.

That my suggestion:

![gradient_2](https://user-images.githubusercontent.com/57914482/133004568-040743ca-45f3-4193-acb4-5881a28136d1.png)

### 0 stars
I liked the idea for a specific color for placeholders (0 stars map). For that, I chosed the gray too, but another gray (it's darker than the PurpleGaze one). Personally I made ot smooth up to 0.1 stars but you can just set the gray for all maps under 0.1* with the same gray.

### 0.4 - 1.5 stars
The main problem of this issue is about the low stars difficulties, which are the same under 1.5 stars. As you know, there are several difficulties under this value. My suggestion is I basically extended the green provided by the 2 stars, so the 1.5 stars color is now for 1 stars. For the difficulties under 1*, instead of using white, which doesn't look very nice in my opinion, is using another blue, the same than the old 1.5 stars, but a bit darker and with less saturation, which is located at 0.4* (yes, 0.1*-0.4* looks the same but I think it's not really a problem). It's more clean in my opinion.

### 4.5 - 6 stars (and 6 to 7 in the same way)
This spectrum uses the fact colors between 4.5 and 6 stars are too similar, and colors between 6 and 7 stars contains more colors than needed. That why I decided to move the 6 stars color to 5.25 stars. (unlike the PurpleGaze suggestion, this spectrum doesn't require to add a purple color, it's not needed).

### 8+ stars
I also though the cut of at 8 stars doesn't look nice. Like PurpleGaze , I made it smoother, where 9 stars is black.

### Yellow text
Instead to make the star rate text at 6.50 stars, I suggest to start at 7.00 or 7.50 stars. ~~7.27 is also nice.~~

### Cool bonus screenshot
![10](https://user-images.githubusercontent.com/57914482/133004574-eb387cdd-146b-4579-9b47-a436fb8eb2ca.PNG)

**Comment by Purplegaze** [comment]
the darker blue at 0.1-1* definitely looks better than the white imo, i'll agree with that. personally I prefer the way my suggestion does the 1.5-2.2 range though, as in yours they look a lot more similar whereas 1.5 and 2.2 are usually very different in osu!standard as the star range for easy and normal are so small. and i'd still kinda prefer the ending parts of the rainbow to be a little earlier though as my suggestion was closer to what people used to know colours as (extra = purple)

aligning with how there is little difference between 1.0* and 1.6* but a lot of difference between 1.6* and 2.2*, i think my suggested scale works really nicely with a subtler dark blue as the bottom instead of the white I used from FD5GD's proposal:
![difficulty3](https://user-images.githubusercontent.com/25409695/133005598-3d784831-9706-4d9a-b6e4-c154afec7be7.png)
```
  .domain([0.1, 1.5, 2, 2.5, 3.3, 4.2, 4.9, 5.8, 6.7, 7.7, 9])
  .clamp(true)
  .range(['#4290FB', '#4FC0FF', '#4FFFD5', '#7CFF4F', '#F6F05C', '#FF8068', '#FF4E6F', '#C645B8', '#6563DE', '#18158E', '#000000'])
```
```
 return rating >= 9 ? '#000000' : rating < 0.1 ? '#AAAAAA' : difficultyColourSpectrum(rating);
```

(and with this, 6.5 can stay as the gold text threshold, imo it works well there)

**Comment by arflyte** [comment]
On the extreme side of the spectrum, I'm good with any suggestions on improving it as I'm not familiar with how often it's used on that end.

**Comment by Corne2Plum3** [comment]
This is what you suggest:

![11](https://user-images.githubusercontent.com/57914482/133140229-c046cd5b-93fb-4d88-987a-6e5f82b6ded7.PNG)

It's looks really nice (the #AAAAAA color is a better idea than mine), but a suggest some small changes:
- Move the 1.5 stars points to 1.25 stars. I think it's better because you can see more the difference between these low difficulties  (below 2 stars). I think it's important to make the difference more visible because playing below 1.5 is really common when you start to play, especially for mania.
- Round all numbers to .25. I think the number will look like less random. (basically rounded all number to 0.25 except 5.8 which become 6 because with 5.75 it would be hard to read difficulties between 5.75 and 7.75).

With these suggestions, it would be like this:
![12](https://user-images.githubusercontent.com/57914482/133142638-45f81f38-d517-4d40-a0d7-258e264bb5a0.PNG)

![gradient_2](https://user-images.githubusercontent.com/57914482/133142625-683c64d3-ac23-4c35-9d78-cad69c66cfbe.png)

The code:
```
.domain([0.1, 1.25, 2, 2.5, 3.25, 4.25, 5, 6, 6.75, 7.75, 9];)
.clamp(true)
.range(['#4290FB', '#4FC0FF', '#4FFFD5', '#7CFF4F', '#F6F05C', '#FF8068', '#FF4E6F', '#C645B8', '#6563DE', '#18158E', '#000000'])
```
and
```
return rating >= 9 ? '#000000' : rating < 0.1 ? '#AAAAAA' : difficultyColourSpectrum(rating);
```

**Comment by mcendu** [comment]
Since the difference between red, orange and yellow is not as obvious as others, I suggest that the orange point should be removed in addition to @Corne2Plum3's suggestion.

**Comment by peppy** [comment]
@mcendu please open a separate issue for that.

**Comment by Purplegaze** [comment]
> Move the 1.5 stars points to 1.25 stars. I think it's better because you can see more the difference between these low difficulties (below 2 stars). I think it's important to make the difference more visible because playing below 1.5 is really common when you start to play, especially for mania.

Makes sense, I haven't played the other gamemodes and didn't know the differences between 1* and 1.5* well there so I guess a little more difference to account for that is fair.

> Round all numbers to .25. I think the number will look like less random. (basically rounded all number to 0.25 except 5.8 which become 6 because with 5.75 it would be hard to read difficulties between 5.75 and 7.75).

This is unnecessary as the numbers are part of a smooth spectrum, it's not like we have a hard line at 4.2 and 4.9. I placed them as such because I was happy with how visually smooth the spectrum looked after tinkering with the placements a bunch, and you can see that in your suggestion, due to your change from [4.2, 4.9, 5.8, 6.7] to [4.25, 5, 6, 6.75], the yellow-red region of the spectrum was extended too much visually and now looks too large compared to the rest.

I think this would work the best:
``` .domain([0.1, 1.25, 2, 2.5, 3.3, 4.2, 4.9, 5.8, 6.7, 7.7, 9])
  .clamp(true)
  .range(['#4290FB', '#4FC0FF', '#4FFFD5', '#7CFF4F', '#F6F05C', '#FF8068', '#FF4E6F', '#C645B8', '#6563DE', '#18158E', '#000000'])```
``` return rating >= 9 ? '#000000' : rating < 0.1 ? '#AAAAAA' : difficultyColourSpectrum(rating);
```

.
> On the extreme side of the spectrum, I'm good with any suggestions on improving it as I'm not familiar with how often it's used on that end.

@arflyte does this mean you wouldn't be open to any alterations on the lower end of the spectrum? Shall I open a PR for only the suggested changes to the range past 3 stars then? (or should someone else do that?)

**Comment by peppy** [comment]
> What I've proposed is pretty much a gradient difficulty guideline. For accurate tweaks, I'll leave it up to the difficulty experts.

Which is to say, since there's seemingly some level of agreement in this thread, I think it's fine to push out the spectrum changes.
