### ISSUE TITLE
Allow retroactively adding guests to a mapset

### ISSUE THREAD

**Issue by Okorin** [ppy/osu-web#8243]
If https://github.com/ppy/osu-web/issues/8196 happens and Guest Difficulties show up on the mapper's profile, then it'd be useful to have the ability to add guests to ranked sets

Obviously this needs some sort of abuse-prevention, but e.g. I have a bunch of maps on other people's sets starting from 2014 or so, having those on my profile as well would be cool

If that first issue happens, then this would be another step that needs some sort of approval system

**Comment by Hiviexd** [comment]
now that GDs are displayed on userpages, now would be the perfect time to bump this, considering that it can easily be fixed by changing perms to allow hosts to edit difficulty owners on ranked maps.

**Comment by AxerCunnyDestroyer** [comment]
I agree, now that we have this implemented it would come as a necessary change.

**Comment by Niftys** [comment]
Agree + have a good day + I love you

**Comment by Kimitakari** [comment]
Agree that'd be nice to fill our GDs on our profiles

**Comment by AncuL001** [comment]
would also be cool to have GMT/BN/anyone else with roles to add guests to a mapset in case the beatmap host is inactive

**Comment by peppy** [comment]
If possible, please use the thumbs up response rather than "me too" replies to keep things easy to track.

We'll definitely need to set something up here. A good starting point would be to automate assignments based on difficulty names, which should handle a good portion of unmarked beatmaps.

**Comment by Cynplytholowazy** [comment]
Any chance for manual marking in addition to automation because there are likely chances that they could be falsely marked / cannot be marked for certain reasons

**Comment by peppy** [comment]
I'll apply the automatic pass over the next couple of days, this should be relative simple and cover 38k ranked difficulties. We'll also look at exposing the controls to moderators as an initial step, to fix any incorrectly labelled difficulties and allow manual application of edge cases.

**Comment by peppy** [comment]
I'm running an initial pass of the automation to match these up.

A couple of notes:

- Does not consider previous usernames (in the case a user renamed some time in the past). Will be added in a future pass.
- Will definitely cause some weird mappings in cases users use something other than their username (ie. `Hitoshirenu Shourai` always used `Hito's xxx`). I can fix these in batches as they are discovered.
- It's fine for NAT/admins to already fix automatic mappings, but I'd appreciate any common ones (ie. whole mappers which need fixing) are mentioned in posts in this thread rather than manually fixed 10-100 times. I can add special cases to the mapping rules.

If posting edge cases to this thread, please try and keep all your reports to a single post per user. If you mark them as a checklist I'll check them off as they are fixed.

Note that the process is running on all ranked/loved/qualified beatmaps and will be completed in around 30-60 minutes from this post's time.

**Comment by MkGuh** [comment]
I ranked over than 50 guest difficulties with the name of "Mk's" while my username was "MkGuh", could you maybe add it all to my user page?

**Comment by Cynplytholowazy** [comment]
I will try to point out as many as possible here since there’s quite an amount of things that are mapped incorrectly

Whole mapper fixes
- Ayyri’s (eiri-)
- Zeth’s ([Zeth])
- Cynp-zy’s (Cynplytholowazy)
- Fapu’s (Faputa)

Potentially confusing mappings
- Half’s (Half/Halfslashed)
- Sing’s (Sing/sing216)

gonna edit if there’s more

**Comment by peppy** [comment]
> also just gonna say it’s probably not that practical to list everyone’s GD name (since i understand there are so many mappers out there who does GD & some difficulties does not indicate the GD mappers as well)

it's more practical to list them here and process once than have moderators go through and mark them manually, so please list as many as you can. it'll be a gradual process to match these up but can be done one piece at a time.

**Comment by Milkitic** [comment]
- yf's (yf_bmp)
- Yoshino's (Yorita Yoshino)
- XLT's (X Light)
- Strenge's (StrengeMistake)
- HW's (Hollow Wings)

**Comment by STCapricorn** [comment]
these only hit 1-2 maps each but posting them anyway

- [ ] Konoe Kanata's (MBmasher) -> wrongly mapped to user "Kanata"
- [ ] Uehara Ayumu's (Elanie) -> wrongly mapped to user "Ayumu"
- [ ] caps' (caps)

**Comment by peppy** [comment]
Also please explicitly mention when a wrong mapping has occurred (as the above posts have done) as I will reset those mappings before running a second time.

**Comment by Cynplytholowazy** [comment]
Instead of using unorganized methods to submit responses I actually think it would be better to organize them into one clear cut place for everything

I think it would be much better than having disorganized messages above so send them all here

made a form here:
https://docs.google.com/forms/d/e/1FAIpQLSfqXQ2kmwHNbeVvynTAehIo9WVutDXlmygPeyGDCruEjgzb8w/viewform

here are the responses (you can check here to avoid double submitting):
https://docs.google.com/spreadsheets/d/1380qFPnDAbV4YlivKykl6zSiB_Je2YzTckgmV9Rq9Sc/edit?resourcekey#gid=1568085932

**Comment by peppy** [comment]
Okay, but unsure about the last question. Maybe best to leave it a "comment" and let people explain any potential issues.

**Comment by Cynplytholowazy** [comment]
Changed

**Comment by Kimitakari** [comment]
Here's an edgecase scenario which I don't think it belongs in the spreadsheet. 

A multimod player named Crystal, who also maps osu! is corresponding with another mapper from osu!catch CLSW who uses "crystal" name in his difficulty names. However Crystal also has an osu!catch difficulty named "Xingxing" which isn't displayed in his profile. A link for reference: https://osu.ppy.sh/beatmapsets/218623.

**Comment by Cynplytholowazy** [comment]
I could open another form that has these kind of edge cases for manual adjustments

Could also think of cases like:
- Difficulty names doesn’t have the GDer’s name there
- Difficulty names doesn’t follow the proper naming convention (a.k.a. not using username’s)

if there are any other ways for these to be automated feel free to suggest; however I doubt there would be

**Comment by peppy** [comment]
> Here's an edgecase scenario which I don't think it belongs in the spreadsheet.
> 
> A multimod player named Crystal, who also maps osu! is corresponding with another mapper from osu!catch CLSW who uses "crystal" name in his difficulty names. However Crystal also has an osu!catch difficulty named "Xingxing" which isn't displayed in his profile. A link for reference: https://osu.ppy.sh/beatmapsets/218623.
> 
> To make things much simpler to explain here's his tweet https://twitter.com/Crystal7mi/status/1517383629684772865?t=aKllEYivMsxvx4NsZh_jsQ&s=19 which the osu!catch diffs mapped by CLSW don't belong to him.

Such cases can be fixed manually.

**Comment by iptq** [comment]
There's also users with names are common words that appear in difficulty names, such as

- [That](https://osu.ppy.sh/users/15936922)
- [Heaven](https://osu.ppy.sh/users/2287536)

These people have gotten marked as guest mappers on maps that aren't actually guest diffs at all.

**Comment by eAkhaten** [comment]
Also [SnowNiNo_](https://osu.ppy.sh/users/2506267) guest difficulties show on [Nino](https://osu.ppy.sh/users/3210623)'s profile

**Comment by arken1015** [comment]
Some prefix like 'lepidon!' is only owned by [lepidopodus](https://osu.ppy.sh/users/194807) so I hope this could be considered too.

Example - https://osu.ppy.sh/beatmapsets/25690#taiko/87671

**Comment by xGordon123x** [comment]
The same problem happened to me, since I and this user [url=https://osu.ppy.sh/users/7856835]Gordon[/url] use the same names to denote GDs, please note since I first started using the designation "Gordon's diff name", and after some reason all my old guest difficulties were attributed to to his profile.
Gordon123: 
- https://osu.ppy.sh/beatmapsets/999054#osu/2123342 
- https://osu.ppy.sh/beatmapsets/735104#osu/1582324
Gordon:
- https://osu.ppy.sh/beatmapsets/1292543#osu/2863979
- https://osu.ppy.sh/beatmapsets/1189948#osu/2483140
I think this can be fixed manually? Thanks in advance:)

**Comment by NoffyNoffeh** [comment]
Would it be possible to cross reference Beatmap descriptions and tags? That would cover a lot of the not exact match cases

A GD uses a nickname: usually this is part of a full name, which would be in tags. For example: Kibb's diff, oko's diff, those are part of their full names in the tags which would be Kibbleru and okoratu respectively

So if a GD name partially matches multiple usernames: check if there are any of those partial match usernames fully in tags. Use the relevant tag to find GDer

Since mapper names have been required in tags for as long as RC has existed, if that's possible it would cover a lot of cases.

And many maps fully list difficulty creators in descriptions with formats like "diff by mapper", or for Collab maps "diff by mapper a and mapper b"

Cross checking with these resources would help to reduce the number of people and maps who need to be manually added to a list.

If this is already being planned that's awesome, I just haven't seen it brought up anywhere yet.

**Comment by czneto** [comment]
I've cheked all my maps to see what's missing or is wrong with the new implementation. Here's the list that needs a fix:
- [ ] [Natsukoi Hanabi](https://osu.ppy.sh/beatmapsets/652293#osu/1415168) missing [Delis](https://osu.ppy.sh/users/1603923) and [Shizuku-](https://osu.ppy.sh/users/1125647) GD credit.
- [ ] [V.I.P](https://osu.ppy.sh/beatmapsets/801096#osu/1685051) missing [deetz](https://osu.ppy.sh/users/3513559) and [bossandy](https://osu.ppy.sh/users/360437) GD credit.
- [ ] [min](https://osu.ppy.sh/beatmapsets/777322#osu/1633044) missing [bossandy](https://osu.ppy.sh/users/360437) GD credit.
- [ ] [Re-sublimity (TV Size)](https://osu.ppy.sh/beatmapsets/827518#osu/1734011) missing [Mismagius](https://osu.ppy.sh/users/19048), [Cyril Scarlet](https://osu.ppy.sh/users/108066) and [bossandy](https://osu.ppy.sh/users/360437) GD credit.
- [ ] [My Les](https://osu.ppy.sh/beatmapsets/868069#osu/1826580) missing [UnitedWeSin](https://osu.ppy.sh/users/1778050) GD credit.
- [ ] [Utsukushiki Zankoku na Sekai (TV Size)](https://osu.ppy.sh/beatmapsets/989457#osu/2069823) missing [Edward](https://osu.ppy.sh/users/5618109) and [Lafayla](https://osu.ppy.sh/users/5312547) GD credit.
- [ ] [Corona](https://osu.ppy.sh/beatmapsets/1001722#osu/2096921) missing [Osu Tatakae Ouendan](https://osu.ppy.sh/users/594210) GD credit.
- [ ] [still alive](https://osu.ppy.sh/beatmapsets/1109705#osu/2644363) missing [IsomirDiAngelo](https://osu.ppy.sh/users/7715620) GD credit.
- [ ] [Kuukan Formation](https://osu.ppy.sh/beatmapsets/1033379#osu/2160544) missing [Kalindraz](https://osu.ppy.sh/users/2313166) GD credit.
- [ ] [Voracity (TV Size)](https://osu.ppy.sh/beatmapsets/812308#osu/1704259) missing [Net0](https://osu.ppy.sh/users/5099768) GD credit.
If the formating is problematic please say so, I'll fix it.

**Comment by MkGuh** [comment]
> I've cheked all my maps to see what's missing or is wrong with the new implementation. Here's the list that needs a fix:
> 
> * [ ]  [Natsukoi Hanabi](https://osu.ppy.sh/beatmapsets/652293#osu/1415168) missing [Delis](https://osu.ppy.sh/users/1603923) and [Shizuku-](https://osu.ppy.sh/users/1125647) GD credit.
> * [ ]  [V.I.P](https://osu.ppy.sh/beatmapsets/801096#osu/1685051) missing [deetz](https://osu.ppy.sh/users/3513559) and [bossandy](https://osu.ppy.sh/users/360437) GD credit.
> * [ ]  [min](https://osu.ppy.sh/beatmapsets/777322#osu/1633044) missing [bossandy](https://osu.ppy.sh/users/360437) GD credit.
> * [ ]  [Re-sublimity (TV Size)](https://osu.ppy.sh/beatmapsets/827518#osu/1734011) missing [Mismagius](https://osu.ppy.sh/users/19048), [Cyril Scarlet](https://osu.ppy.sh/users/108066) and [bossandy](https://osu.ppy.sh/users/360437) GD credit.
> * [ ]  [My Les](https://osu.ppy.sh/beatmapsets/868069#osu/1826580) missing [UnitedWeSin](https://osu.ppy.sh/users/1778050) GD credit.
> * [ ]  [Utsukushiki Zankoku na Sekai (TV Size)](https://osu.ppy.sh/beatmapsets/989457#osu/2069823) missing [Edward](https://osu.ppy.sh/users/5618109) and [Lafayla](https://osu.ppy.sh/users/5312547) GD credit.
> * [ ]  [Corona](https://osu.ppy.sh/beatmapsets/1001722#osu/2096921) missing [Osu Tatakae Ouendan](https://osu.ppy.sh/users/594210) GD credit.
> * [ ]  [still alive](https://osu.ppy.sh/beatmapsets/1109705#osu/2644363) missing [IsomirDiAngelo](https://osu.ppy.sh/users/7715620) GD credit.
> * [ ]  [Kuukan Formation](https://osu.ppy.sh/beatmapsets/1033379#osu/2160544) missing [Kalindraz](https://osu.ppy.sh/users/2313166) GD credit.
> * [ ]  [Voracity (TV Size)](https://osu.ppy.sh/beatmapsets/812308#osu/1704259) missing [Net0](https://osu.ppy.sh/users/5099768) GD credit.
>   If the formating is problematic please say so, I'll fix it.

Mismagius' , Delis', Sotarks' and others that follow this naming pattern aren't a specific issue to the mapper/map, but to the way peppy implemented the feature. I am pretty sure it is a bug and he is already aware of it.

**Comment by Cynplytholowazy** [comment]
It seems that the automatic parse didn't account for Capital letters or Small letters (e.g. BLOCKO'S DIFFICULTY hasn't been assigned to Blocko). Maybe this can be brought to attention as well.

> Would it be possible to cross reference Beatmap descriptions and tags? That would cover a lot of the not exact match cases
Think this would work to a certain extent but it would require a lot of mix and match. In addition I can think of multiple cases where this couldn't be applied:
- GD handle being vastly different with their username (e.g. [R] uses Ron's; or any other username change and old GD handle)
- difficulty name doesn't indicate the GD handle (e.g. https://osu.ppy.sh/beatmapsets/963193#taiko/2016673)
- cannot be applied to maps ranked before the GDers in tag rules are in place (a.k.a. before RC exists)

For the others, if you have found any maps that needs to be fixed please head over to https://github.com/ppy/osu-web/issues/8243#issuecomment-1106056290 instead of posting in the thread to avoid clutter.

**Comment by peppy** [comment]
> Would it be possible to cross reference Beatmap descriptions and tags? That would cover a lot of the not exact match cases

I wasn't behind the tag requirement, and from what i can tell it was not implemented in a useful way. If it was `guest:username` it would have been usable. As it stands I'm do not think it's worth the effort (the false positives will be way to large).

**Comment by Milkitic** [comment]
Please also add entry for manually adding V1 guest diffs if possible (2007~2016?)

**Comment by peppy** [comment]
> Please also add entry for manually adding V1 guest diffs if possible (2007~2016?)

Thanks for completely not reading this thread, but I'll bite: This has been added. Please contact a team member (NAT / whatever) and ask them to assign for you. Alternatively, please use this thread for its intended purpose.

**Comment by peppy** [comment]
I'm processing the spreadsheet but have removed any stupid lines (people who put multiple names or free text in either field; people who put their previous usernames in the current username field etc.).

**Comment by peppy** [comment]
I've done another pass using the provided mappings in the spreadsheet. This matched / remapped 4,936 new difficulties.

I think resetting the spreadsheet and making sure people submit only one pairing per line and include any missed cases (which are *mapper* to *name* mappings only - I can't deal with anything else) would be a good next step.

**Comment by Cynplytholowazy** [comment]
I have gone ahead and reset the spreadsheet so people can input things that may still not be parsed.

> making sure people submit only one pairing per line

As for this, I had already filtered quite a lot of the multi-pairing cases (did have some leftovers due to either very confusing ones or the ones I haven't processed yet)

For single beatmap cases I will forward them to NATs and GMTs for fixing.

**Comment by RockRoller01** [comment]
> Thanks for completely not reading this thread, but I'll bite: This has been added. Please contact a team member (NAT / whatever) and ask them to assign for you. Alternatively, please use this thread for its intended purpose.

Could you please tell us where? From what I have seen none of us NAT/GMT seem to be able to find it, nor have any instructions on what we should and shouldnt handle for now.

**Comment by Cynplytholowazy** [comment]
Maybe it can be clarified a little bit since it seems like a misunderstanding:

What they are talking about is maps that are ranked under moddingV1 (when modding via forum was still a thing). Maps ranked under moddingV1 will not have a moddingV2 discussion page, thus making the assign GD button not accessible to GMT / NAT (since that button only exists in moddingV2 discussion pages) (at least what I heard from the GMT & NAT, if there's something either I missed or is mentioned inside the moderator group then my bad)

**Comment by nanaya** [comment]
Beatmap discussion has been enabled for all beatmaps.

**Comment by RockRoller01** [comment]
Wrong auto mapping i found:
inaba's -> inaba, should be inaba-tan instead (https://osu.ppy.sh/users/477744)

**Comment by MkGuh** [comment]
> Wrong auto mapping i found: inaba's -> inaba, should be inaba-tan instead (https://osu.ppy.sh/users/477744) has 30 cases of this happening it seems


We are using the Google Forms for this now. https://github.com/ppy/osu-web/issues/8243#issuecomment-1106056290

**Comment by RockRoller01** [comment]
> We are using the Google Forms for this now.
thanks for informing. Do we also submit name changed or only wrongly mapped ones?

**Comment by peppy** [comment]
I've reprocessed up to row 116 of the new responses. 866 new mappings.

I'll do another one on request, let's see how many more come in. Make sure to use the single map form if you don't have a large number of mappings to fix.

**Comment by peppy** [comment]
I've done one final run (up to row 139, 251 new mappings) and going to call this one completed for now. If any moderators find users which require large assignments feel free to comment on this issue with the specific missing mappings. If they can be fixed by manually assigning (ie. 5 or less beatmaps) then just do it manually from this point forward.
