### ISSUE TITLE
Add a confirmation of some sorts for problem stamps on qualified maps?

### ISSUE THREAD

**Issue by tilda** [ppy/osu-web#8245]
This idea is kind of like a week late but I'd like to see thoughts on it.

I thought this would be a good idea after seeing this:
![image](https://user-images.githubusercontent.com/8301262/138337108-afbff56c-592e-4a32-8793-c36dd8b8566f.png)

That post was originally supposed to be a hype (and the post was quickly deleted and replaced with the intended hype), but the user misclicked on the problem button. I feel like it's a bit too easy to cause chaos in that regard, considering that the entire BN server does get pinged if a problem stamp gets posted on a qualified map.[1]

[1] (well, considering I am not in the BN server myself, having never been in that position, I'd need someone to verify that for me, but yeah)

**Comment by NoffyNoffeh** [comment]
Disregarding discord servers, it also notifies everyone with the setting turned on on the website. Random problem misposts are definitely really common at the moment and confirmation would help

**Comment by tilda** [comment]
> If there's a confirmation step each time a problem is reported, is this not going to become an annoyance for people that use the system as it was meant to be used? Should the confirmation only be shown the first time a user makes a problem report on a specific beatmap?

Seems reasonable to me for the most part, though I'd like input from the other people in this discussion as well.

**Comment by peppy** [comment]
I think we can bump this up in priority if it's seen as important, but does the erroneous posting happen often enough for it to be warranted? Is someone able to look through a month of reports and see how often a false report happens that may be avoided by this?

**Comment by UberFazz** [comment]
Went ahead and checked my notification history. Out of the past ~50 reports starting from Sept 30 until today, I deemed 9 of them as "false reports," whether mistakes or otherwise (note: some won't be publicly viewable as they're deleted): 

https://osu.ppy.sh/beatmapsets/1570222/discussion/-/timeline#/2648555
https://osu.ppy.sh/beatmapsets/1560743/discussion/-/timeline#/2660585
https://osu.ppy.sh/beatmapsets/1604123/discussion/-/timeline#/2679717
https://osu.ppy.sh/beatmapsets/1604123/discussion/-/timeline#/2676607
https://osu.ppy.sh/beatmapsets/1536021/discussion/-/timeline#/2682240
https://osu.ppy.sh/beatmapsets/1579180/discussion/-/generalAll#/2747392
https://osu.ppy.sh/beatmapsets/1620540/discussion/-/generalAll#/2754342
https://osu.ppy.sh/beatmapsets/1514209/discussion/-/generalAll#/2757012
https://osu.ppy.sh/beatmapsets/1627165/discussion/-/generalAll#/2773415

A few others weren't necessary to report but seemed to be attempts at contributing to the map, so I omitted those.

That makes around 20% of reports false, so yeah, I'd say this is pretty important.
