### ISSUE TITLE
Descrepancy in pp values for older songs

### ISSUE THREAD

**Issue by JonScarlet** [ppy/osu-web#8551]
I have images listed here in this forum thread for visuals (hopefully that makes a link).

https://osu.ppy.sh/community/forums/topics/1510173?n=4

The long and short of it is that certain songs that have SS scores from before the Nov. rework have very different pp values given for SS scores. It isn't uniform across years or song types or even players; I can go to one song in 2019 with a no-mod SS and find a player with, say, 125pp while others say 117pp, and then find that same player on another map in the same year saying, like, 110pp while others say 115pp.

As for me personally, I'm less concerned about it being fixed (though I certainly would like to see that!) as I am about knowing which value is supposed to be the correct one.

(apologies if I'm missing other necessary information.)

**Comment by peppy** [comment]
Will need to recalculate these scores (can already do this via `osu-tools` for confirmation), but I believe this will be due to users which have been inactive for a while becoming active again.

Right now, we don't reprocess the scores of users that become active immediately. This is done in batches, usually every month or two. It's one of the areas we plan to improve when new infrastructure comes online, but currently adds too much load to the synchronous update flow we have.

**Comment by peppy** [comment]
So the issue here is that the players in question are *current inactive*. We currently only update pp values of active players. To fix this, we'd need to rethink how this is being done.

It may be that we want to also recalculate all top x plays of every beatmap going forward.
