### ISSUE TITLE
"Unknown error occured" when pressing download button too quickly

### ISSUE THREAD

**Issue by smoogipoo** [ppy/osu-web#8552]
1. Go to https://osu.ppy.sh/beatmapsets/55926#osu/231988
2. Press the download button as soon as it comes visible.

Results in:
![image](https://user-images.githubusercontent.com/1329837/151338675-c0322951-d32a-4cdb-9468-e1e66f51e20d.png)

The beatmap still downloads and there's no error in the console as far as I can see.

**Comment by nanaya** [comment]
Which browser is it? I can't reproduce it in firefox 91 and chrome 97 (or maybe I'm just too slow?).

**Comment by nanaya** [comment]
And whoever impacted, please check if leaderboard on that page is loaded or blank.

**Comment by respektive** [comment]
I get the error on firefox 96.0.2 and the leaderboard is blank saying `No scores yet. Maybe you should try setting some?`

**Comment by nanaya** [comment]
There doesn't seem to be any good solution here. The problem is download click navigates the page away so everything that's currently being loaded are aborted (in a way that's different from xhr abort hence that popup).

Possible solutions:
1. [`download` attribute](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/a#attr-download) but if there's any error, firefox won't show anything while chrome save the html error page to download directory
2. create iframe sourcing the download url but similar to download attribute, no handling of error
3. open download in new tab (`target=_blank` link) is probably the least confusing of all but it creates new tab (and switch to it) while connecting
4. xhr download which I've never tried but from what I gather it involves creating our own download control (progress bar, cancel button, etc)
5. disable download button until score is loaded (and hope it's the last thing loaded)

Pick your poison, I guess? 🤷

**Comment by peppy** [comment]
Which specific component is triggering the error in this case?

**Comment by nanaya** [comment]
The error message comes from scoreboard but the whole page loading is also aborted (images still being loaded will stay blank, etc)

**Comment by peppy** [comment]
I think that's mostly expected behaviour  in such a scenario though? If we can just block the error message from displaying on incomplete data that might be an alright option.

**Comment by nanaya** [comment]
The page may end up in half broken state though which will be carried over on navigation (as it doesn't reset state) although I don't think there's anything else that may end up half broken... or is there 🤔 

(also the score section does need some refactors)

**Comment by smoogipoo** [comment]
> think there's anything else that may end up half broken... or is there

The notifications / chat numbers don't load and show `...` / `Loading unread notifications`, that's the only thing other than the scores that I've found broken.

**Comment by notbakaneko** [comment]
are you using safari?

**Comment by smoogipoo** [comment]
Firefox 94.0.2. Also tested Chromium 96.0 which seems fine.

**Comment by respektive** [comment]
> The notifications / chat numbers don't load and show `...` / `Loading unread notifications`, that's the only thing other than the scores that I've found broken.

they take a bit longer, but load in for me after a few seconds.

**Comment by peppy** [comment]
The download attribute sounds kind of what we want, but it also seems to creates a permission popup on safari on first download, so I'm not sure...

![Safari 2022-02-02 at 05 16 34](https://user-images.githubusercontent.com/191335/152097109-c2fe50ed-30f1-4cf8-befd-0ed8009de060.png)

Options 2/3/4 sound out of question (bad UX) and 5 maybe okay but not sure. Honestly if we can just silence the error that would probably be the best outcome for me. Even if there is an error in the scoreboard, the user doesn't need to know about it (they can see it missing and presume an error if they want).
