### ISSUE TITLE
Allow restricted/banned users to be added in Difficulty Owners

### ISSUE THREAD

**Issue by troke12** [ppy/osu-web#8566]
Some of rest/ban users need to be added to Difficulty Owner because they still need to be appreciate of their works

**Comment by Nivalyx** [comment]
hmm, i'm not sure if this would change/do anything tbh as (for now, at least) the feature's sole purpose is to allow gd owners to resolve open problems on their diff by their own -- and since restricted/banned users cannot participate in modding discussions at all allowing this will only amount to nothing

**Comment by peppy** [comment]
Out of scope, sorry.
