### ISSUE TITLE
Trying to login without referer causes IP ban

### ISSUE THREAD

**Issue by Devocub** [ppy/osu-web#8597]
Trying to login to osu site with this thing (https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Referer) removed from http requests causes IP ban and then "429 Too Many Requests nginx" error shown for everything.

**Comment by Devocub** [comment]
And if you switch IP address but will not remove cookies then new IP address will get banned too.

**Comment by bdach** [comment]
that makes no sense - if it was due to a "lack of the referer header" the site wouldn't be directly reachable by any user if they weren't redirected from another site. it is also demonstrably false - just poked the site with `curl` and minimal headers and got a response just fine.

you're most likely being rate limited, just as the error says. are you trying to use the website or developing an app using web oauth tokens? if it's the former, then do you have any browser-level addons installed to add extra features to the website?

**Comment by peppy** [comment]
If you have an account issue please contact accounts@ppy.sh.
