### ISSUE TITLE
Wrong pp given to all flashlight scores on certain maps 

### ISSUE THREAD

**Issue by Rekunan** [ppy/osu-web#8865]
As reported here: https://twitter.com/TheShadowxdd/status/1519455436717625344

Example maps:
https://osu.ppy.sh/beatmapsets/1552275#osu/3171844
https://osu.ppy.sh/beatmapsets/1545547#osu/315901

Interesting to note that lazer, while it does pull the pp value from the server, calculates a completely different pp value for the [score](https://osu.ppy.sh/scores/osu/3959995857).
![osu_2022-04-28_06-32-22](https://user-images.githubusercontent.com/24501632/165743490-35304e2a-1d4b-4906-9e22-76ec4b493ddd.png)

**Comment by peppy** [comment]
Thanks for the report. Are those the only two known beatmaps with issues?

**Comment by peppy** [comment]
We are a running a full reprocess on all ranked (and eventually all) beatmaps to bring the attributes in line with expectations. After this is done (a day or two) I will reprocess the scores on each of the beatmaps above.

The root cause for this seems to be that the two beatmaps were ranked without being re-submitted in recent times. So they didn't have a chance to reprocess properly.

**Comment by peppy** [comment]
Reprocessing has finished and I've also updated the PP values. This means they will correctly contribute to user totals. As for the display on the beatmap leaderboard, i'll look into whether we can do an isolated reindex of that.

**Comment by Coppertine** [comment]
https://osu.ppy.sh/scores/osu/4155582912
https://osu.ppy.sh/scores/osu/4159334391
https://osu.ppy.sh/scores/osu/4163246186
https://osu.ppy.sh/scores/osu/4165432965
https://osu.ppy.sh/scores/osu/4165790077

I still found these 5 scores not updated correctly and are still at 1pp.
