### ISSUE TITLE
Error downloading old beatmap

### ISSUE THREAD

**Issue by xDololow** [ppy/osu-web#8939]
This map is unable to download: https://osu.ppy.sh/beatmapsets/13758#osu/50686
If you try download from beatmap page, it returns 500 error.

But if you try doing it form beatmap search page it returns this:

```
Warning: sprintf(): Too few arguments in /var/www/html/S3.php on line 742

Warning: Cannot modify header information - headers already sent by (output started at /var/www/html/S3.php:742) in /var/www/html/d.php on line 109
```

**Comment by Nivalyx** [comment]
yeah very old beatmaps that have been Graveyarded for so many years are intentionally made so that they can't be downloaded anymore

http://osu.ppy.sh/community/forums/topics/49310

![image](https://user-images.githubusercontent.com/36564236/169675096-55382a7e-b3be-4d7a-a357-726add09ebcd.png)

**Comment by Nivalyx** [comment]
(if you're still curious about this you can try downloading http://osu.ppy.sh/s/13757 which is 1 mapsetid away from the map that you're trying to download for example and you'll get the same result)

**Comment by respektive** [comment]
There should probably be a better way of communicating this. I think an info box, like it exists on maps that have their audio removed, would probably work well.
![](https://pek.li/ymejm7.png)

**Comment by xDololow** [comment]
> (if you're still curious about this you can try downloading http://osu.ppy.sh/s/13757 which is 1 mapsetid away from the map that you're trying to download for example and you'll get the same result)

You can't even click on username in this one lol

**Comment by Nivalyx** [comment]
@respektive 

> There should probably be a better way of communicating this. I think an info box, like it exists on maps that have their audio removed, would probably work well. ![](https://camo.githubusercontent.com/fbcf96d1322bb43ed5b866f913f727e141f982a77b9ba0143236aab358d24242/68747470733a2f2f70656b2e6c692f796d656a6d372e706e67)

there's already such warning for *very* old Graveyarded beatmaps (like, ~2007/2008) actually but for some reason they don't really show up on newer maps that are affected by this, dunno why :(

![image](https://user-images.githubusercontent.com/36564236/169685262-4add3df7-93f7-4018-a5dc-883455784c8b.png)

---

@xDololow 

> You can't even click on username in this one lol

iirc the sole factor that determines whether a beatmap is still downloadable or not is their age tho, as in "how long has it been since they're last updated".

whether the uploader is restricted or not isn't really considered by the system

**Comment by xDololow** [comment]
> whether the uploader is restricted or not isn't really considered by the system

No, the thing is, it's not even working as supposed to. If player restricted, you'll see it. But in this map link not even clickable.

**Comment by respektive** [comment]
> there's already such warning for very old Graveyarded beatmaps (like, ~2007/2008) actually but for some reason they don't really show up on newer maps that are affected by this, dunno why :(

That's interesting, I haven't seen this one before. So i guess the actual issue here is that the warning isn't shown on all unavailable maps.

> No, the thing is, it's not even working as supposed to. If player restricted, you'll see it. But in this map link not even clickable.

I believe this is due to the user not actually being restricted, but rather completely deleted. I've seen this a few times before for some very old users. I could be wrong though

**Comment by abraker95** [comment]
Going to leave this map here so it can be tracked: https://osu.ppy.sh/beatmapsets/687#osu/4630

As UberFazz#6563 said, it downloads fine but fails to import with this message
![image](https://user-images.githubusercontent.com/4358724/172274272-dceaddbd-9b11-48fa-b362-290d86c59fe3.png)

**Comment by Blooshing** [comment]
> 
I checked the song archive and it doesn't have the mp3 name as `audio`.mp3, but instead, as `10 Mr.Lonely`.mp3, not necessarily sure if this can cause the import failure or if something else is going on @abraker95. (I also tried renaming the audio file and reimporting it but I am not sure how to rename an audio file through 7zip.) :shrug:

**Comment by peppy** [comment]
I'm running a script in the background to fix this issue. It should be done within a day.
