### ISSUE TITLE
Poor visibility/usability of the web reports for moderators

### ISSUE THREAD

**Issue by TicClick** [ppy/osu-web#9079]
(tangentially related to the website)

right now, reports from the web are dumped into a single Discord channel, which impairs their visibility:
- no way to hide handled reports → too many of them, hard to navigate
- can't be filtered easily, for example, by report type (user profile/beatmap discussion/...)
- no way to ensure a report was read → we may (and do) lose some

for what it's worth, the same applies to the chat reports (and even more of them may be lost/ignored due to the sheer volume), but at least they are read — or *assumed* to be read — more often, because the other channel is more popular

**Comment by peppy** [comment]
> * no way to hide handled reports → too many of them, hard to navigate

Have you considered using reactions to mark handled reports? We do this elsewhere and it works well. I don't think they should be hidden because the idea of the whole system is to give visibility over what's happening to more than one party.

> * can't be filtered easily, for example, by report type (user profile/beatmap discussion/...)

What kinda of situation would you want to filter them for?

> * no way to ensure a report was read → we may (and do) lose some

Similar to the first point I guess?

**Comment by RockRoller01** [comment]
> Have you considered using reactions to mark handled reports? We do this elsewhere and it works well. I don't think they should be hidden because the idea of the whole system is to give visibility over what's happening to more than one party.
> It could potentially be automated if that helps.

We do already use emotes to mark the status of reports, however we are still overlooking huge chunks of reports. The issue is that any report past the first half a dozen or so is just lost to the backlog.
A report should **never** be fully hidden, as in inaccesible to moderators, however there should be a clear distinctions between "handled reports" and "open reports". 

The simplest solution to this would to simply seperate these via two different channels and either making use of discord embed buttons: (example image from a random bots help embed)
![image](https://user-images.githubusercontent.com/35633093/177192978-2104c2b2-b2a8-4f36-a887-ba43ee489173.png)

or by using the "Apps" submenu and add an option to move between channels with it: (example image from a bot, that uses this to move something to a channel called "checked"
![image](https://user-images.githubusercontent.com/35633093/177193090-8e5da0ff-44c5-4ca2-851b-f3b13b338a36.png)

> What kinda of situation would you want to filter them for?
Not everyone handles every area of osu. For example, a mapping focused GMT would prefer to be able to filter for beatmap and discussion reports, while a forum moderator might prefer filtering to forums.

Some other people also only handle "general" reports, like e.g. inappropriate avatars and would not touch forums, comments or beatmaps at all.

> Similar to the first point I guess?
Yes, should already be explained in my reply to the first point

**Comment by TicClick** [comment]
+1 to everything written above. we use reactions, true, but that's not enough: the reports keep piling up, and some of them may be missed due to backlog, because they are a responsibility of everyone but no one in particular ("someone else will sort that out")

> What kinda of situation would you want to filter them for?

- some moderators only handle specific areas (mapping + modding is a good example) and aren't very interested in the rest:
- "too much of irrelevant stuff" + "it's hard to navigate in there" are among the top reasons for why web reports aren't checked that frequently by the majority of the team
- about 3/4 of people surveyed (that's 32 of 43 total I think) noted that notifications or similar mechanism for the reports in their area of activity would certainly help them moderate.

**Comment by peppy** [comment]
On the topic of notifications, that could be easily solved by using discord roles and highlighting based on the report type, I think.

**Comment by TicClick** [comment]
> On the topic of notifications, that could be easily solved by using discord roles and highlighting based on the report type, I think.

that would help. language-specific roles (may be taken from [a list of GMTs](https://osu.ppy.sh/wiki/en/People/The_Team/Global_Moderation_Team#team-members)) for a more general usage would be welcome, too!

**Comment by Ephemeralis** [comment]
I've created roles for every channel name (following the schema ``channel-report`` and assigned appropriate GMT to them on the osu!internal Discord as per [this list](https://osu.ppy.sh/wiki/en/People/The_Team/Global_Moderation_Team#grouped-by-languages-moderated).

**Comment by peppy** [comment]
The only thing remaining is to make a list of which reports should specify which tags. Once that's done, implementation should be quite simple from our end.

**Comment by RockRoller01** [comment]
What exactly are your current plans for implementations? Just automatic notifications?

As for what reports should be grouped into:
| group | types |
| :-- | :-- |
| forum | forum posts |
| mapping | beatmaps, discussion posts, mapping forum posts |
| comments | comments |
| users | user profiles |

It might be worth to also add a new report option to user profiles "chat messages" as those do ocassionally get reported via web/lazer and then they could also be seperated into their own group

**Comment by Ephemeralis** [comment]
This needs revisiting, the report situation is deteriorating somewhat in terms of them being handled.

What do you mean 'which tags' exactly, as in, which reports should point to a given Discord role, or?

**Comment by peppy** [comment]
I believe this should now be resolved.

**Comment by RockRoller01** [comment]
> I believe this should now be resolved.

We do not have notifications currently, which is the main thing asked for besides the split

**Comment by peppy** [comment]
Is it not feasible to turn on the notifications for the channel(s) you care about now?

![Discord PTB 2023-03-28 at 02 21 39](https://user-images.githubusercontent.com/191335/228110583-dbd165d3-0a0b-4118-ba0c-d8df3f088c13.png)

**Comment by RockRoller01** [comment]
> I think the overhead isn't that big

fair, I guess especially the forums are so dead that it probably doesn't matter much now. Potentially worth revisiting in the future tho for chat reports, but thats the future
