### ISSUE TITLE
Legal issue with EU Cookie Law

### ISSUE THREAD

**Issue by leonekmi** [ppy/osu-web#910]
The `locale` cookie is programmed to expire in 5 years.

This is illegal in Europe, with set the limits to 13 months, and the Cookie Consent plugin (or similar/self-maked) must be installed.

**Comment by peppy** [comment]
please PR a fix for this if you care enough.

**Comment by Shadoxfix** [comment]
The 13 months time limit for cookie consent is only under the French implementation of the EU cookie law. Additionally this is not an issue since the locale cookie is used for UI customization for which cookie consent is not needed. See section 3.6 of [this source](http://ec.europa.eu/justice/data-protection/article-29/documentation/opinion-recommendation/files/2012/wp194_en.pdf).
