### ISSUE TITLE
Featured Artists | NORMAL HUMAN Beatmap Template has `BeatmapID` and `BeatmapSetID` in .osz

### ISSUE THREAD

**Issue by XetThe** [ppy/osu-web#9157]
Hi.
A friend had an issue with this beatmap template since it wasn't letting him upload it (screenshot below)

![image](https://user-images.githubusercontent.com/87451413/181877204-7c18ef6a-7961-4b9d-b83e-2cdd51a7884a.png)
I figured out the issue was because the template had a `BeatmapID` and `BeatmapSetID` already in the .osu file (screenshot below too)

![image](https://user-images.githubusercontent.com/87451413/181877232-f8a03be2-99b9-4e02-8d02-961f0f661610.png)

Not sure if this is the correct place to report this issue but I hope it is.

**Comment by Nivalyx** [comment]
hmm it doesn't happen to me tho, i just downloaded a fresh copy of NORMAL HUMAN's base .osz from [SOOOO's FA listing](http://osu.ppy.sh/beatmaps/artists/30) and everything seems to be normal for me here :

![image](https://user-images.githubusercontent.com/36564236/181904135-bb7eda3f-e9c4-4b41-861e-2a3f6adc9d94.png)

i think (if any) this is caused by something client-side instead of the base .osz template. you can try uploading the map by setting the `BeatmapID` to `0` and `BeatmapSetID` to `-1` manually tho

**Comment by Nivalyx** [comment]
further details/instructions on how to fix this issue : http://osu.ppy.sh/community/forums/topics/325639
