### ISSUE TITLE
(lazer) Room is not joinable and the host has no connection to it.

### ISSUE THREAD

**Issue by hashelq** [ppy/osu-web#9443]
I am developing https://github.com/hashelq/osu-lazer-room-bot . And I see that after some time players stop joining my lobbies, because they cant. When I try to join any of these lobbies in osu lazer, nothing happens.

When I restart the bot, it says "number of simultaneously active rooms reached".
I am not sure that these lobbies must be destroyed if the host is in the lobby, but I don't understand why the bot is in the lobby after the signalR connection is stopped.

Seems like the osu multi server or osu-web has a serious bug with the connection management?

by the way, rejoining these rooms fixes the problem

**Comment by hashelq** [comment]
pino logs

{"level":50,"time":1667283739107,"pid":16608,"hostname":"vds2350360","msg":"Connection disconnected with error 'Error: WebSocket closed with status code: 1006 (no reason given).'."}
{"level":50,"time":1667283739139,"pid":15656,"hostname":"vds2350360","msg":"Connection disconnected with error 'Error: WebSocket closed with status code: 1006 (no reason given).'."}

**Comment by hashelq** [comment]
Perhaps, I have been kicked because of the expired oauth token, but the bot has not left the lobby.

**Comment by peppy** [comment]
I believe you are hitting the server restart process we have in place. As in, this is expected behaviour, and if this was the osu! client it would be notified that the server is restarting and people cannot join the room anymore.

Do note that interacting with SignalR as you are doing is *not* officially supported so I am hesitant to even give support for what you're doing. Please make sure to get in touch before deploying anything of this nature on production systems.
