### ISSUE TITLE
Hovering over a mapper's username does not show the "This user doesn't exist" card on some beatmap info pages

### ISSUE THREAD

**Issue by TheRealStevie** [ppy/osu-web#9532]
Normally when you hover over a username whose account is restricted/deleted, it will show a "This user doesn't exist" card.
![Screenshot 2022-11-24 000834](https://user-images.githubusercontent.com/75444413/203582986-1975645a-0cac-4ed6-bc1f-5920dbed805e.png)
However on some beatmap info pages ([1](https://osu.ppy.sh/beatmapsets/9255#osu/39201), [2](https://osu.ppy.sh/beatmapsets/10037#osu/39936), and [3](https://github.com/ppy/osu-web/issues/8939#issuecomment-1133835649)) the mapper's username is just plain text. Despite this, on the beatmap listing page ([4](https://osu.ppy.sh/beatmapsets?q=107016) for 1, 2. [5](https://osu.ppy.sh/beatmapsets?q=OoCHKoO&s=graveyard) for 3.) it works as usual.

**Comment by bdach** [comment]
This can in fact get worse as reported at https://github.com/ppy/osu/discussions/23591.

1. Go to https://osu.ppy.sh/beatmapsets?q=1%2C2%2C3%2C4
2. Hover over mapper MCXD's name on first result
3. Card shows for user with username "141". This is extra confusing, because https://osu.ppy.sh/users/141 redirects to https://osu.ppy.sh/users/10193533 (user in question has just changed their username to "141").

**Comment by nanaya** [comment]
The original issue and the comment are two different things.

It behaves differently because the beatmap page has more information on the user (mainly deleted state) and thus it simply doesn't link the user at all if deleted whereas on listing page there's no such info and every mappers are linked regardless of deleted or not.

As for the username 141 thing, it's a bit more involved.

**Comment by TheRealStevie** [comment]
This doesn't seem to be fixed as I can still replicate the original issues above.

**Comment by nanaya** [comment]
The original issue is more or less as intended.
