### ISSUE TITLE
"Cheesed" Not Bluffing medal persisting after unlock condition change.

### ISSUE THREAD

**Issue by chromb** [ppy/osu-web#9535]
For a while ~1y ago, the Not Bluffing medal was achievable on the [Normal] difficulty of it's map, whereas it is intended to only be for the [Hard] difficulty or above. The issue of unlocking the medal is fixed, but the users that obtained the medal this way still have it.
Don't know exactly how possible removing these would be, but if reverting pass/fc medals in taiko has been done in the past, I feel it's only fair to revert these ones as well.

**Comment by cl8n** [comment]
I guess there's a question of how far you'd be willing to go with reverting medals. I personally think it's kind of lame that some people have 9 and 10 star FC medals by using touchscreen, which now has its SR fixed to be dramatically lower. or Not Bluffing from the Normal diff as you mentioned. but others prefer to never revert medals because exploiting an unintended solution can be viewed as part of the fun
