### ISSUE TITLE
Expose the channel's max text length

### ISSUE THREAD

**Issue by novialriptide** [ppy/osu-web#9590]
A follow-up issue from https://github.com/ppy/osu/issues/21330, in order to fix this, we need to expose the channel's max text length to have different max lengths for different chat text boxes as said by @bdach https://github.com/ppy/osu/pull/21397#issuecomment-1325522484.

https://github.com/ppy/osu-web/blob/7d89312883198ebb8ba57d6afc5319db9fcc05b2/config/osu.php#L80

**Comment by bdach** [comment]
The reason why I proposed exposing this is to allow for client-side validation of the message length. Currently it is not possible to know in advance what that max length is, as it depends on the envvar mentioned above, and apparently on the channel itself, too, since as far as I can tell, [announce channels are exempt from it anyways](https://github.com/ppy/osu-web/blob/571a3645e9358e61198b24d5fb9c4ea2ce22a60c/app/Models/Chat/Channel.php#L419).

**Comment by peppy** [comment]
Rather than exposing, can we just change osu-web to auto-truncate like what bancho did?

**Comment by loma-baldsson** [comment]
In my opinion it'd be better UX to have a char limit client-side anyways, so you'd know when your message will be truncated.

And for that, the character limit must be exposed

**Comment by novialriptide** [comment]
I feel as if auto-truncating would be mean to the user who typed a long message and didn't know about the auto-truncating.

**Comment by peppy** [comment]
That would not be the case as messages should be resolved by the client with the actual final content.

**Comment by novialriptide** [comment]
> That would not be the case as messages should be resolved by the client with the actual final content.

By client do you mean the actual program or the user?

**Comment by nanaya** [comment]
Adding the limit info in the channel json shouldn't be too difficult...

as a bonus osu-web frontend can use it as well as it's currently limited to 1k for all types to accommodate announce message

**Comment by novialriptide** [comment]
> Adding the limit info in the channel json shouldn't be too difficult...

I can probably work on it after my finals if no one else wants to work on it.
