### ISSUE TITLE
Country Flag for XX is missing

### ISSUE THREAD

**Issue by RockRoller01** [ppy/osu-web#9704]
example: https://osu.ppy.sh/users/4341397

![image](https://user-images.githubusercontent.com/35633093/210281848-b1a205ec-a541-49c1-b6d8-8f2cb6953524.png)

**Comment by peppy** [comment]
There won't be a flag for this country code. It's not valid or used in normal scenarios. I've given osu!team a proper country.

**Comment by nanaya** [comment]
Any flags (`/assets/images/flags/xxxx-xxxx.svg`) should have fallback to `/images/flags/fallback.png` which apparently isn't working on production (or more like has been forgotten since migration to docker). For non-local nginx with no file access it should be something like `error_page 404 = /images/flags/fallback.png` in `location ^~ /assets/images/flags/` block.

...the fix isn't to be done here though since the nginx config for deployment is somewhere else 🤷‍♀️ @ThePooN maybe should look into this.

**Comment by ThePooN** [comment]
Okay, that required some refactoring due to the way ingress-nginx works; the Helm chart for osu-web now supports multiple Ingress objects.

The changes have been applied in the following commit: https://github.com/ppy/helm-charts/commit/a2d2a10b4d538d887f875090c8dfcc85e6a3205e

@nanaya I have already deployed this to dev.ppy.sh. Please inspect headers on every path we need special rules and make sure they match your expectation so we can deploy this to production soon.

**Comment by nanaya** [comment]
Seems correct apart of occasionally returning 504.

**Comment by ThePooN** [comment]
Hmm... managed to reproduce it on the blank flag redirection (same as the one you ran through per my logs), then reloaded ingress-nginx and I can no longer. Made sure I'm bypassing cache too. Strange.

**Comment by ThePooN** [comment]
Okay, I think I can reproduce consistently by omitting the `INGRESSCOOKIE` (used by ingress-nginx for sticky sessions). I'll look into it...

**Comment by ThePooN** [comment]
Hah, it's a pretty logical one in the end.

For every client request, ingress-nginx has a list of candidate upstreams (octane instances). If the first upstream failed (which it does when it returns a 4xx or 5xx), it wants to request to another one, but there is only one octane instance running on dev.ppy.sh.
I can't see how to disable that behavior, not that we would really want to in 99.9% of scenarios, so I just bumped it up to 2 replicas by default.

Let me know if you find anything else.

**Comment by nanaya** [comment]
wait, why is 4xx considered upstream failure?

**Comment by ThePooN** [comment]
> wait, why is 4xx considered upstream failure?

I think it's based on [proxy_intercept_errors](https://nginx.org/en/docs/http/ngx_http_proxy_module.html#proxy_intercept_errors).

> heck, even 5xx if it comes from octane itself then doing the same on other instance will probably just result in same thing

It doesn't retry FWIW, it just decides to use a different upstream for the next request in that session.

**Comment by nanaya** [comment]
> I think it's based on [proxy_intercept_errors](https://nginx.org/en/docs/http/ngx_http_proxy_module.html#proxy_intercept_errors).

That's definitely not what it does... Or at least for a normal nginx.

**Comment by ThePooN** [comment]
It is internal lua logic, see https://github.com/kubernetes/ingress-nginx/blob/26fe69cb47295f6677576fa8585afa98d72536e2/rootfs/etc/nginx/lua/balancer/sticky.lua
