### ISSUE TITLE
add an option to view translation in forum posts

### ISSUE THREAD

**Issue by Lyawi** [ppy/osu-web#9865]
since the forum is used by people from all over the world and english skills aren't the best with everyone, this could help communicate.

...maybe depending on what language you've chosen on the website, or even better, it detects where you're from automatically.

https://www.deepl.com/translator could be used for it but some languages are still missing sadly

![dd](https://user-images.githubusercontent.com/32525896/219040265-9ce71f2b-52ec-4515-b11d-57ef0e3580e0.png)

(couldn't find a similar topic to this)

**Comment by nanaya** [comment]
Note that those kind of services aren't free for non-trivial non-personal use.

**Comment by Blooshing** [comment]
This can probably be closed because depending on the browser you use if you right click there is an option to translate text/page to your preferred language. 

Anything else seems to be out of scope and not really important enough. If you really have a stake in a forum thread then you can easily just bring up another tab and translate it if the right-click service is not available.

**Comment by peppy** [comment]
I think relying on browsers for this functionality is best.
